### ISSUE TITLE
pio_swapm performance test

### ISSUE THREAD

**Issue by kmpaul** [NCAR/ParallelIO#1]
The pio_spmd.c has several high performance alternatives for mpi functions:

fc_gather : MPI_Gather
fc_gatherv : MPI_Gatherv
pio_swapm: MPI_Alltoallw

Each of these functions has several options including a simple pass through to mpi.

We need a test function that analyses the best options for a given platform and model configuration.
This could be a standalone program or a function called at initialization.

**Comment by jedwards4b** [comment]
Moved to Jira 
https://jira.ucar.edu/secure/RapidBoard.jspa?rapidView=73&projectKey=PIO&view=planning.nodetail&selectedIssue=PIO-1
