### ISSUE TITLE
Mixing types in iodesc causes wrong fill values to be used?

### ISSUE THREAD

**Issue by edhartnett** [NCAR/ParallelIO#1037]
It's possible to mix different types in the same decomposition, as long as the types are of the same size.

But if we do this, I believe the code below (from write_darray_multi_par()) will use the fill values for the first variable's type:

```
    /* Point to var description scruct for first var. */
    vdesc = file->varlist + varids[0];

    /* Set these differently for data and fill writing. */
    int num_regions = fill ? iodesc->maxfillregions: iodesc->maxregions;
    io_region *region = fill ? iodesc->fillregion : iodesc->firstregion;
    PIO_Offset llen = fill ? iodesc->holegridsize : iodesc->llen;
    void *iobuf = fill ? vdesc->fillbuf : vdesc->iobuf;

```
We need a test to check this.

**Comment by edhartnett** [comment]
I am about to put up a PR which includes new test, test_darray_multivar3.c. In this test I create a file with two ints and one float, and use the same decomposition. The decomposition has holes, and the SUBSET rearranger is used.

This demonstrates the problem with fill values. The resulting file shows that when fill values are not provided, the default fill value of NC_INT is used for the float.

```
netcdf data_test_darray_multivar3_iotype_2_use_fv_0 {
dimensions:
	timestep = UNLIMITED ; // (1 currently)
	x = 4 ;
	y = 4 ;
variables:
	int Kirk(x, y) ;
	int Spock(timestep, x, y) ;
	float McCoy(timestep, x, y) ;
data:

 Kirk =
  0, 1, 2, _,
  10, 11, 12, _,
  20, 21, 22, _,
  30, 31, 32, _ ;

 Spock =
  0, 1, 2, _,
  10, 11, 12, _,
  20, 21, 22, _,
  30, 31, 32, _ ;

 McCoy =
  0.5, 1.5, 2.5, -1.401298e-45,
  10.5, 11.5, 12.5, -1.401298e-45,
  20.5, 21.5, 22.5, -1.401298e-45,
  30.5, 31.5, 32.5, -1.401298e-45 ;
}

```

An additional, possibly related problem occurs with pnetcdf files. In that case, the float data values are corrupted, in addition to the fill values being incorrect. This problem occurs even if the fill values are provided.

```
netcdf data_test_darray_multivar3_iotype_1_use_fv_1 {
dimensions:
	timestep = UNLIMITED ; // (1 currently)
	x = 4 ;
	y = 4 ;
variables:
	int Kirk(x, y) ;
	int Spock(timestep, x, y) ;
	float McCoy(timestep, x, y) ;
data:

 Kirk =
  0, 1, 2, -42,
  10, 11, 12, -42,
  20, 21, 22, -42,
  30, 31, 32, -42 ;

 Spock =
  0, 1, 2, -42,
  10, 11, 12, -42,
  20, 21, 22, -42,
  30, 31, 32, -42 ;

 McCoy =
  1.056965e+09, 1.069548e+09, 1.075839e+09, -1.037435e+09,
  1.09314e+09, 1.094189e+09, 1.095238e+09, -1.037435e+09,
  1.101267e+09, 1.101791e+09, 1.102316e+09, -1.037435e+09,
  1.10651e+09, 1.107034e+09, 1.107427e+09, -1.037435e+09 ;
}


netcdf data_test_darray_multivar3_iotype_1_use_fv_0 {
dimensions:
	timestep = UNLIMITED ; // (1 currently)
	x = 4 ;
	y = 4 ;
variables:
	int Kirk(x, y) ;
	int Spock(timestep, x, y) ;
	float McCoy(timestep, x, y) ;
data:

 Kirk =
  0, 1, 2, _,
  10, 11, 12, _,
  20, 21, 22, _,
  30, 31, 32, _ ;

 Spock =
  0, 1, 2, _,
  10, 11, 12, _,
  20, 21, 22, _,
  30, 31, 32, _ ;

 McCoy =
  1.056965e+09, 1.069548e+09, 1.075839e+09, -2.147484e+09,
  1.09314e+09, 1.094189e+09, 1.095238e+09, -2.147484e+09,
  1.101267e+09, 1.101791e+09, 1.102316e+09, -2.147484e+09,
  1.10651e+09, 1.107034e+09, 1.107427e+09, -2.147484e+09 ;
}

```

**Comment by edhartnett** [comment]
Short-term fix is to disable writing in an iodesc defined for another type.

Long-term fix is to move the type information out of the decomposition, which would be type-neutral. The code needs to be modified to use the correct fill values regardless of the decomposition. But this is a fair amount of work.

**Comment by jedwards4b** [comment]
I agree, ultimately as long as variables have the same decomposition we should be able to use the same decomposition descriptor regardless of the datatype of the variable.
