### ISSUE TITLE
pio1 fails to open netcdf4 classic format file with typename='pnetcdf'

### ISSUE THREAD

**Issue by jedwards4b** [NCAR/ParallelIO#104]
pnetcdf cannot read files in netcdf4 format but pio1 used to failover to use netcdf when this happened, it doesn't seem to be doing that any longer

**Comment by jayeshkrishna** [comment]
I see the code that should be doing the failover to netcdf4 from pnetcdf. Let me try some cases and see if it works.

**Comment by jayeshkrishna** [comment]
A simple test on master (3f0fd7c319f77d037ad93e5cdb7db52933360a7a) seems to show that the failover to netcdf4 is working as expected. @jedwards4b : Do you have _NETCDF4 enabled in your build?

**Comment by edhartnett** [comment]
This is for PIO1, correct? This is not PIO2?

**Comment by jayeshkrishna** [comment]
Yes, this is for PIO1

**Comment by edhartnett** [comment]
Good because I am still stuck on the ncid bug! ;-)

**Comment by jedwards4b** [comment]
Hi Jayesh, 
The file that caused the problem was 

inputdata/lnd/clm2/urbandata/CLM45_tbuildmax_Oleson_2016_0.9x1.25_simyr1849-2106_c160801.nc

I've put a copy on cetus in /projects/ccsm/inputdata/lnd/clm2/urbandata

**Comment by jayeshkrishna** [comment]
Thanks, I will try it out.

**Comment by jayeshkrishna** [comment]
Looks like the file was created with a newer version of netcdf+hdf5 . ncdump (/soft/libraries/netcdf/4.3.3-f4.4.1/cnk-xl/V1R2M2-20150213) does not work on the file on Cetus but it works on my laptop (netcdf 4.4.0).
Do you want me to try installing netcdf on cetus and see if it works?

**Comment by jayeshkrishna** [comment]
Ok, my ncdump on Cetus was /soft/libraries/netcdf/4.3.0-f4.2/fen-xl/current/bin/ncdump , retrying with /soft/libraries/netcdf/4.3.3-f4.4.1/cnk-xl/V1R2M2-20150213

**Comment by jayeshkrishna** [comment]
Just verified that /soft/libraries/netcdf/4.3.3-f4.4.1/cnk-xl/V1R2M2-20150213/bin/ncdump works on the file. 
Going to try out some pio tests.

**Comment by jayeshkrishna** [comment]
I am able to recreate the issue with a simple pio test program. Looking into it.

**Comment by jayeshkrishna** [comment]
It looks like pio1 is able to read the file (/projects/ccsm/inputdata/lnd/clm2/urbandata/CLM45_tbuildmax_Oleson_2016_0.9x1.25_simyr1849-2106_c160801.nc) successfully. A simple pio program was able to open/read attributes/close the file.
However I noticed that the file does not have write permissions for group/everyone and hence the file cannot be opened for writing (My sample program initially tried to open the file for writing and hence failed).

**Comment by jayeshkrishna** [comment]
@jedwards4b : Can this issue be closed?
