### ISSUE TITLE
Everyone ready for new release V2.2.2?

### ISSUE THREAD

**Issue by edhartnett** [NCAR/ParallelIO#1041]
All,

Now that async darray writes are working, I would like to release V2.2.2. There is a draft release announcement here: https://github.com/NCAR/ParallelIO/releases/tag/untagged-d99e9ca7f26b45840191

I would like to do this at the end of the week. Please let me know if this is a problem for anyone.

If there are any features or bugs that were added/fixed since the last release, that you want mentioned in the release notes, let me know.

**Comment by jedwards4b** [comment]
I thought that the pnetcdf and netcdf4p types were also ready?

**Comment by edhartnett** [comment]
Yes, thanks for noticing. I have updated the release notes. pnetcdf and netcdf4p IOTYPEs do work with darray writes.

**Comment by jayeshkrishna** [comment]
@edhartnett : Why do we need pnetcdf 1.8.1 or newer?

**Comment by edhartnett** [comment]
As I recall there was a fix in 1.7.0 which applied to our code, and now tests will fail if PIO is build with 1.7.0. 

If you want to give it a try and see what fails, you can get more details.

**Comment by jayeshkrishna** [comment]
ok, are your referring to the fix in pnetcdf that set the max fortran name length to the same as the C length (Issue #554 ) ?
In that case we should probably specify the version of pnetcdf required as 1.7.0 (you could however recommend users to use the latest version)

**Comment by edhartnett** [comment]
I will do this release after issue #1044 is resolved.

**Comment by edhartnett** [comment]
Released.
