### ISSUE TITLE
The number of pnetcdf requests is calculated incorrectly

### ISSUE THREAD

**Issue by dqwu** [NCAR/ParallelIO#1044]
This bug can be reproduced with pioperf with 4 MPI tasks (it seems that no existing unit tests reproduce it)
1) Build latest PIO master branch with pnetcdf
2) Modify tests/performance/pioperformance.F90, line 60, change the default nframes to 6
nframes = 6
3) Build pioperf from pioperformance.F90
4) Use gensimple.pl to generate simple.dat (with 4 tasks), for example:
```
version 2001 npes 4 ndims 1 
16 
0 4
1 2 3 4 
1 4
5 6 7 8 
2 4
9 10 11 12 
3 4
13 14 15 16 
```
5) Create pioperf.nl like below:
```
&pioperf
decompfile = "./simple.dat"
pio_typenames = 'pnetcdf'
niotasks = 2
rearrangers = 2
nvars = 1
/
```
6) Run pioperf with 4 MPI tasks
mpiexec -n 4 ./pioperf

The performance test will fail with MPI_Abort.

With some debugging work on vdesc->request array and vdesc->nreqs, it is observed that:
t1: Array capacity = 16, nreqs = 1, expected nreqs = 1
t2: Array capacity = 16, nreqs = 3, expected nreqs = 2
t3: Array capacity = 16, nreqs = 6, expected nreqs = 3
t4: Array capacity = 16, nreqs = 10, expected nreqs = 4
t5: Array capacity = 16, nreqs = 15, expected nreqs = 5
t6: Array capacity = 16, nreqs = 21, expeced nreqs = 6
We can see that at nframe 6, nreqs are larger than the array capacity, this will cause some pnetcdf requests to have undefined values.

The bug is from pio_darray_int.c, line 313 (original introduced by commit f397173 in Nov 25, 2015):
`vdesc->nreqs += reqn + 1;`

It should be changed to
`vdesc->nreqs = reqn + 1;`

**Comment by dqwu** [comment]
@jedwards4b 
Is reqn useful in the following code?
```
int reqn = 0;
if (vdesc->nreqs % PIO_REQUEST_ALLOC_CHUNK == 0 )
{
    ...
    reqn = vdesc->nreqs;
}
else
    while(vdesc->request[reqn] != NC_REQ_NULL)
        reqn++;
...
vdesc->nreqs += reqn + 1;
```
In pio_varm.c, there are similar code, but reqn is not used, and "vdesc->nreqs++" avoids the bug above caused by using reqn.
```
case PIO_IOTYPE_PNETCDF:
vdesc = file->varlist + varid;
if (vdesc->nreqs%PIO_REQUEST_ALLOC_CHUNK == 0 ){
...
}
request = vdesc->request+vdesc->nreqs;
...
vdesc->nreqs++;
```

**Comment by dqwu** [comment]
@jedwards4b 
A more general question. Is the request and nreqs members in var_desc_t only used by ncmpi_wait_all()?
```
typedef struct var_desc_t
{
    ...
    /** ID of each outstanding pnetcdf request for this variable. */
    int *request;

    /** Number of requests bending with pnetcdf. */
    int nreqs;
    ...
}
```
Since pnetcdf 1.7.0, there is a new feature that relinquishes users from the responsibility of tracking the IDs of pending requests (see https://trac.mcs.anl.gov/projects/parallel-netcdf/wiki/ReleaseNotes-1.7.0). It states that:

> Using NC_REQ_ALL as the 2nd argument "num" in ncmpi_wait_all/ncmpi_wait APIs will flush all the pending nonblocking requests. In this case, the 3rd and 4th arguments "array_of_requests" and "array_of_statuses" will be ignored and thus these two arguments can be NULLs

With this new feature we might be able to remove the data structure and bookkeeping code for pnetcdf pending requests (there are a lot of realloc calls)

**Comment by jedwards4b** [comment]
Yes you can go ahead and remove reqn, replacing it with vdesc->nreqs as illustrated.   I think that pnetcdf 1.7.0 has been around long enough that you can also implement the nc_req_all argument.   Thanks

**Comment by dqwu** [comment]
@jedwards4b 
OK, for the short term I can provide a quick fix without using reqn (similar to the code in pio_varm.c). 
We can create a new issue (enhancement to be implemented later) to require PIO to be built with pnetcdf 1.7.0 or higher, such that we can remove a lot of code tracking the IDs of pending pnetcdf requests using NC_REQ_ALL.

**Comment by dqwu** [comment]
Besides pioperf test, an existing Fortran unit test can also be updated to reproduce this issue.

Edit tests/general/pio_decomp_frame_tests.F90.in (line 99), change NFRAMES from 3 to 6
integer, parameter :: NFRAMES = 3

Build PIO with AddressSanitizer, and run the following test with
`ctest -R pio_decomp_frame_tests`

ASan reported a heap-buffer-overflow in src/clib/pio_darray_int.c:1263
```
for (reqcnt = 0; reqcnt < vdesc->nreqs; reqcnt++)
  request[rcnt++] = max(vdesc->request[reqcnt], NC_REQ_NULL);
```
In this test, the size of request array (allocated by realloc) is 16 (PIO_REQUEST_ALLOC_CHUNK), while vdesc->nreqs is incorrectly calculated as 21.

**Comment by dqwu** [comment]
For now, this bug is only reproducible when PIO_USE_MALLOC is OFF (use bget package). 
As mentioned in issue #940, when PIO_USE_MALLOC is ON, maxfree will always be calculated as -1 and needsflush will always be set to true. With frequent flushes, pending pnetcdf requests will not be accumulated to reproduce this bug.

**Comment by edhartnett** [comment]
BTW from a quick look, a few weeks ago, it seemed to me that all the PIO builds on your jenkins server use PIO_USE_MALLOC=On. So none of them are testing bget code. Is that intentional? Do you guys not find bget helpful?

**Comment by dqwu** [comment]
@edhartnett 
It seems that PIO_USE_MALLOC=OFF will take more test time (tested with ACME and CIME). On our jenkins server, we set PIO_USE_MALLOC=ON to most builds (on develop branch, result sent to cdash). However, we do still keep a few builds with default PIO_USE_MALLOC=OFF (on master branch, result not sent to cdash).

**Comment by dqwu** [comment]
@edhartnett 
The performance of PIO_USE_MALLOC=OFF (it is the default CMake option) is much worse than PIO_USE_MALLOC=ON. Do you know the reason? Maybe we should create an issue to investigate it.
