### ISSUE TITLE
Clarify requirements for PIOc_Init_intracomm() and PIOc_finalize().

### ISSUE THREAD

**Issue by edhartnett** [NCAR/ParallelIO#109]
Naively, when I first started this project, I assumed all calls to PIOc_Init_intracomm_init would occur on all tasks, as would all calls to PIOc_finalize().

But I see from the test pio_iosystems3.F90.in that I am not correct. Apparently there is an idea that PIOc_Init_intracomm() can be called by just a subset of the total number of processors.

In that case, is it reasonable to require that the exact same subset of tasks call PIOc_finalize() for that iosystemid?

**Comment by jedwards4b** [comment]
Yes the finalize (and all of the calls in between) are collective on the communicator comp_comm used in the call to the initialize function.

**Comment by edhartnett** [comment]
There was a problem in finalize with the buffer pool.

There is only one CN_bpool pointer, so if finalize is called on a subset of tasks and then called on all tasks (for a different iosystemid), then there is a problem because some of the tasks (the ones in the subset) will already have null, and others won't. And there is a function that calls MPI_Reduce in order to distribute some performance data about the buffer.

In order to avoid this, I put in the following code:

    /* Free the buffer pool. */
    int niosysid;
    if ((ierr = pio_num_iosystem(&niosysid)))
	return ierr;
    LOG((2, "%d iosystems are still open.", niosysid));

    /* Only free the buffer pool if this is the last open iosysid. */
    if (niosysid == 1)
    {
	free_cn_buffer_pool(*ios);
	LOG((2, "Freed buffer pool."));
    }


This will only attempt to free the buffer pool if finalize is being called on the last open iosystemid.

**Comment by jayeshkrishna** [comment]
Why do these functions take the iodesc as a parameter then (Ideally these functions should be performing iodesc-specific stuff, right?)?

**Comment by jayeshkrishna** [comment]
IMO,
* The pool buffers should be iosys-specific OR
* There should be reference counts for the pool buffer (move the logic of freeing the pool correctly to pool management logic)

**Comment by edhartnett** [comment]
I have not spent a lot of time looking at the buffer code.

On first look, I also wonder why there is not a separate buffer for each iosystem. Since each one will be doing different IO, how can they use the same buffers? But I haven't looked at the code.

**Comment by edhartnett** [comment]
I am going to close this ticket. It's clear that finalize should be called only on the tasks that participated in the init. This is the way the code now works on the ejh_ncid_issue branch, and this will soon be merged to master.
