### ISSUE TITLE
Some C tests won't handle builds with missing iotypes

### ISSUE THREAD

**Issue by edhartnett** [NCAR/ParallelIO#110]
I recently realized that a bunch of the async tests won't handle cases win which the library is built without pnetcdf or netCDF (i.e. only one of them is present).

This needs to be fixed by dynamically generating the number of iotypes to test, based on what is in the build.

**Comment by jayeshkrishna** [comment]
The PIO testing framework used by the tests in tests/general create the iotypes used for the tests based on the build (The code is in Fortran not C though)

**Comment by jayeshkrishna** [comment]
I will start adding some async tests to the existing set of tests (tests/general)

**Comment by edhartnett** [comment]
I am familiar with the Fortran testing framework that creates the iotypes array. In fact, that's how I realized that I was doing it wrong. ;-)

In general both Fortran and C tests are needed, but to do detailed debugging of the C library I need to translate your tests into C. I have a hard time debugging C code from Fortran tests.

**Comment by edhartnett** [comment]
I believe these are all fixed now on my current branch. Need to set up some Jenkins testing next...

**Comment by edhartnett** [comment]
The only remaining issue is detecting if netCDF-4 is present, but netCDF-4 parallel is not. I am working on that now...

**Comment by edhartnett** [comment]
The following tests are failing CDash because of this issue: test_intercomm2, test_async_4proc, test_async_3proc, and test_async_simple. The fail with some variation of this message:

ERROR: iotype 3 not defined in build /scratch/cluster/katec/dashboard/src/src/clib/pio_file.c 427

**Comment by edhartnett** [comment]
I believe these are all fixed on the pull request that I have up currently.

**Comment by edhartnett** [comment]
CDash results show that these bugs have been fixed, so I will close this issue.
