### ISSUE TITLE
Strong dimension-checking for pio_setframe broke some ESMCI/cime tests

### ISSUE THREAD

**Issue by dqwu** [NCAR/ParallelIO#1128]
For a long time, the Fortran interface pio_setframe just sets the record dimension value for a variable, without checking the dimensions.

In PR #1084, a strong dimension-checking logic was added. Only when the first dimension is unlimited, the rec_var flag is set to true for a variable. If rec_var is false, PIO_EINVAL will be returned from 
PIOc_setframe().

However, this enhancement has caused existing ESMCI/cime tests/cases to fail.

1) Failed X case:
cime code calls pio_setframe on a variable (to be written to an output file) that does not have time dimensions, and passed -1 as the frame number.
This bug could be fixed on cime side: when there is no time sample, pio_setframe should not be called.

2) Failed cime_developer tests:
cime code calls pio_setframe on a variable (read from an input file) that has a time dimension, and the frame number is also valid.
The issue is, the time dimension is not an unlimited one, which will prevent PIO from setting the rec_var flag to true.

For example, in inputdata/atm/datm7/NYF/nyf.gxgxs.T62.051007.nc 
```
lat = 94 ;
lon = 192 ;
time = 12 ;
...
float prc(time, lat, lon) ;
        prc:short_name = "prc" ;
        prc:long_name = "Precipitation" ;
        prc:units = "mm/day" ;
```
The new dimension-checking logic requires that the time dimension be unlimited, like:
time = UNLIMITED ; // (12 currently)

[Question]
For ACME/CESM, since there are many existing legacy input files like nyf.gxgxs.T62.051007.nc, should we use a weak dimension-checking for pio_setframe such that the time dimension does not have to be unlimited?

**Comment by jedwards4b** [comment]
These are cime issues and an issue should be opened in that repo.  I don't think that it will be overly difficult to fix the issue on that end.

**Comment by edhartnett** [comment]
I have no objection to rolling back the checking of dimensions in setframe() if that is helpful. I can do that today, either as a temporary or permanent solution.

In case 1, where setframe is being called with a -1, I agree with Jim that this is best fixed in the caller.

In case 2, are you then doing darray calls on a var without an unlimited dimension, but treating one of the dimensions as a record dimension? Does that work?

**Comment by dqwu** [comment]
@jedwards4b 
On cime side, case 1 can be easily fixed.
For case 2, it could not change existing legacy input files where the time dimension in those files is not unlimited. The fix should be on PIO side, thoughts?

**Comment by edhartnett** [comment]
For case 2, I agree, PIO should support that. I just didn't know it was possible.

I will put together a test for this and make sure it works properly.

**Comment by dqwu** [comment]
@edhartnett 
For case 2,  the input file has "time = 12" and cime code calls pio_setframe on prc with frame number 1 to 12 (0 to 11 in PIOc_setframe). This is valid so PIO should not require that the time dimension be unlimited. 
PS, how to identify whether a dimension is a time dimension (especially when it is a limited one)?

**Comment by dqwu** [comment]
@edhartnett 
In NC readers/writers of MOAB, we use name matching ("time", "Time" or "t") to decide if a dimension is a time dimension.

**Comment by jedwards4b** [comment]
I don't think that we can rely on variable names for this.  We sometimes use dimensions other than time as the record dimension.  If a dimension is to be used as a record dimension, it's always the first one.

**Comment by dqwu** [comment]
A quick workaround for the tests fro pass is to not return pio_err() from PIOc_setframe. Log a warning for users if possible.

**Comment by gold2718** [comment]
I'm not sure if this matters for this discussion but CAM uses `ncol` as the unlimited dimension for satellite diagnostic output.

**Comment by edhartnett** [comment]
The dimension will always be the first one, the name will nor matter.

I will check in a branch with the error returns for non-record dims removed.

I will also add a test so that this does not break again in the future.
