### ISSUE TITLE
pio_decomp_fillval test fails on master

### ISSUE THREAD

**Issue by jayeshkrishna** [NCAR/ParallelIO#114]
The pio_decomp_fillval (pio_decomp_fillval.F90.in) fails on master (70c910bfa307108ac20d594a30698c089bb9dffb).

**Comment by jayeshkrishna** [comment]
This (pio_decomp_fillval) test was removed and replaced by a less extensive test (pio_decomp_fillval2) in 17634e98556cdf8ff2b7538cd6626d7a3ef0a3d0 and hence this bug was not exposed by the test suite. Please refer to PR #113 that re-introduces the original test

**Comment by jayeshkrishna** [comment]
A bisect shows that this test was broken in f60c4a7c6e71104be90985cb2c29cab406f5d0ae

**Comment by jayeshkrishna** [comment]
Although the test was broken in f60c4a7c6e71104be90985cb2c29cab406f5d0ae , that issue was fixed later (?). The current issue (pio_decomp_fillval fail) on master is due to 93d430583fefbe2ef3c5f6407a7a4aea74e37301

**Comment by edhartnett** [comment]
So does this PR cause any additional test failures?

**Comment by jayeshkrishna** [comment]
If you are referring to PR #117 , with that change I don't know of any additional test failures. Did you see any?

**Comment by edhartnett** [comment]
No, I haven't run it, I was just making sure I understood the PR. Thanks!

**Comment by edhartnett** [comment]
When I check out master and run tests, it hangs in pio_decomp_fillval.

Is that expected?

**Comment by edhartnett** [comment]
According to CDash this test is still failing on three builds.

**Comment by jayeshkrishna** [comment]
@jedwards4b : Are you looking into this issue (or do you want me to work on it?)?

**Comment by jayeshkrishna** [comment]
The changes in jayeshkrishna/fix_fillval_tests were included (inadvertently) in c0884e57a25e283768b451d4a1bcefb676c6ac8a . So this test should pass now on master.

**Comment by jayeshkrishna** [comment]
The CDash errors might not be related to the issue discussed here. @edhartnett : Can you create a separate issue for this (can you recreate this failure)?

**Comment by edhartnett** [comment]
I am just seeing what is on cdash

http://my.cdash.org/index.php?project=PIO&date=2016-10-20

This test passes for me on my builds, so I assume the remaining problems are some porting issues to the environments that it is failing on.
