### ISSUE TITLE
ACME smoke test failed due to removed code

### ISSUE THREAD

**Issue by dqwu** [NCAR/ParallelIO#1177]
In PR #1088 (commit b572628), some code were removed:
```
line 820:
         if (fndims > ndims)
         {
             ndims++;
-            if (vdesc->record < 0)
-                vdesc->record = 0;
         }

line 1021:
-        if (fndims > ndims)
-        {
-            if (vdesc->record < 0)
-                vdesc->record = 0;
-        }
```
One ACME smoke test (SMS_D_Ln5.ne16_ne16.FC5AV1C) failed due to this change. If we add the code back that test can pass as before: looks like a regression. 

Is there any reason that these code should be removed? I checked previous versions of PIO2, in pio2_0_1 (Aug 2014), pio_darray.c has code like below:
```
 int pio_read_darray_nc(file_desc_t *file, io_desc_t *iodesc, const int vid, void *IOBUF)
 {
     ...
     if(fndims>ndims){
       ndims++;
       if(vdesc->record<0) 
	 vdesc->record=0;
     }
     ...
 }
```
This means the removed code has been in PIO2 for about 3 years. There should be a reason why this logic is needed in the initial version of PIO2.

**Comment by edhartnett** [comment]
Do we know what the test was doing when it encountered this bug?
I would like to write a C test for this...

**Comment by edhartnett** [comment]
@dqwu can you tell me what this test was doing when it failed so I can try to reproduce?

Thanks.

**Comment by dqwu** [comment]
@edhartnett @jedwards4b 
The logic below is in pio2_0_1 (in pio_darray.c). Do you have SVN history to see when it was first added and what was the purpose of this special handling? You can also check whether PIO1 have this logic or not.
```
     if(fndims>ndims){
       ndims++;
       if(vdesc->record<0) 
	 vdesc->record=0;
     }
```
My guess is that on CESM/ACME side, it might forget to call pio_setframe for a variable, such that vdesc->record < 0. However, it still tries to read the first frame (record 0). On PIO2 side, fndims>ndims tells us that this variable is a record variable so we should set the default record number to 0 (instead of -1). Without this logic, CESM/ACME test will fail to read data from frame 0 of this variable, causing the test to fail later due to missing data.

**Comment by dqwu** [comment]
@edhartnett @jedwards4b 
This logic has been ported to PIO1 (since pio1_9_1) in piodarray.F90.in:
```
  subroutine read_darray_nf_{TYPE} (File,varDesc,ioDesc,array, iostat)
  ...
    if (IOproc) then
! This is for pio2 compatablity
       if(fndims > size(iodesc%start) .and. vardesc%rec<0) then
          vardesc%rec =  1_PIO_OFFSET
       endif
  ...
```
I tested ACME with PIO1. If this logic above is removed, SMS_D_Ln5.ne16_ne16.FC5AV1C fails.

Since PIO1 retains this logic (as a patch/workaround?), maybe we should restore it for PIO2.

**Comment by dqwu** [comment]
@edhartnett 
It is confirmed that on ACME side, pio_setframe might not be called on a record variable.
For this test, there is a 3D variable with a time dimension:
```
ncol = 13826 ;
time = UNLIMITED ; // (1 currently)
lev = 72 ;
double U(time, lev, ncol) ;
```
On PIO2 side, rec_var is set to true, but record is still -1 as pio_setframe is never called on variable U.

On ACME side, it needs to read data for U:
```
    fieldname = 'U'
    call infld(fieldname, ncid_ini, 'ncol', 'lev', 1, npsq,          &
         1, nlev, 1, nelemd, tmp, found, gridname='GLL')
```
However, the matched infld routine does not have a timelevel argument. Therefore, pio_setframe is not called:
```
subroutine infld_real_2d_3d(varname, ncid, ..., timelevel)
  ...
  integer, optional, intent(in)     :: timelevel
  ...
  if(ndims == 3) then
    if(present(timelevel)) then
      call pio_setframe(ncid, varid, int(timelevel,kind=pio_offset_kind))
    end if
  end if
  ...
  call pio_read_darray(ncid, varid, iodesc, field, ierr)
  ...
```

**Comment by dqwu** [comment]
@edhartnett @jedwards4b 
So here are some questions:
1) Must the client code (e.g. ACME) call pio_setframe for a record variable before calling pio_read_darray? Can it be optional?
2) If client side forgets to call pio_setframe, should PIO set a default record (frame) number for a record variable?

**Comment by edhartnett** [comment]
I am not in favor of assuming a frame of 0.
The frame should be explicitly set by the calling program.

**Comment by edhartnett** [comment]
I have long thought of introducing a new write_darray() function, which would have the frame as a parameter of the function.

Such a function would obviate this error state for future PIO users.

What we could also usefully do is have the write_darray() call return a newly-defined error code for this, which would at least be more clear to users how to fix this problem.

For existing users, we could at least return

**Comment by edhartnett** [comment]
OK, upon mature reflection I agree that I broke the code by changing the default frame assumption. I will put it back in...

**Comment by edhartnett** [comment]
Not sure if it will fix the ACME smoke test, but I am about to put up a PR with the fix that assumes a record of 0 for darray reads where setframe has not been called.

**Comment by edhartnett** [comment]
OK, the PR has been merged, and I have added a test that confirms that 0 is the default frame value for reads when no frame has been set. Can you guys run this test and let me know what happens?

**Comment by dqwu** [comment]
@edhartnett 
ACME smoke test SMS_D_Ln5.ne16_ne16.FC5AV1C can pass with latest master branch, thanks.

**Comment by edhartnett** [comment]
Awesome, thanks for checking. I will close this issue.
