### ISSUE TITLE
MPAS v5.2: memory request exceeds block size

### ISSUE THREAD

**Issue by climbfuji** [NCAR/ParallelIO#1182]
Hi there, this is maybe not an Issue in the Github sense, but I wanted to report a problem (?) that I get when using PIOv2 with MPASv5.2. Every MPI task writing data to a netCDF file (pnetCDF as well as netCDF4) is spitting out a message

ParallelIO/src/clib/bget.c 778 memory request exceeds block size 108724248 33554432

Looking at the source code of PIOv2, this might or might not cause a problem (lines 777-782 in bget.c)? If it is not, is there a parameter that I could reconfigure to avoid getting this error message? I think lots of MPAS users will be confused by this.

Thanks,

Dom

NB: MPASv5.2 with PIOv2 (cloned 2017-09-01) on HLRS Hazel Hen (Cray XC40) with Intel 16 compilers. PIOv2 cmake config:

tar -xvzf pio-2.x.y_20170901.tar.gz
cd pio-2.x.y_20170901
cd ParallelIO
export PIOSRC=`pwd`
export CC=cc
export FC=ftn
export CXX=CC
#
cd ..
mkdir pio
cd pio
cmake \
-DNetCDF_C_PATH=/opt/cray/netcdf-hdf5parallel/4.4.1.1.3/INTEL/16.0 \
-DNetCDF_Fortran_PATH=/opt/cray/netcdf-hdf5parallel/4.4.1.1.3/INTEL/16.0 \
-DPnetCDF_PATH=/opt/cray/parallel-netcdf/1.8.1.3/INTEL/16.0 \
-DCMAKE_INSTALL_PREFIX=SOME_VALID_PATH/pio-2.x.y_20170901 \
-DPIO_ENABLE_TIMING=OFF \
-DCMAKE_VERBOSE_MAKEFILE=1 \
$PIOSRC 2>&1 | tee log.cmake

**Comment by edhartnett** [comment]
PIO can be built with or without using bget. (Bget is a memory management package that may improve performace.)

Try building with PIO_USE_MALLOC=On.

**Comment by climbfuji** [comment]
@edhartnett Thanks, this worked!

**Comment by rjtrapp** [comment]
Greetings - I'm having this same issue, but it's not clear to me exactly where/how this option:

PIO_USE_MALLOC=On

is set. I'm using PIO2 2.4.4.

**Comment by climbfuji** [comment]
@rjtrapp in the above cmake call, simply adding
```
-DPIO_USE_MALLOC=ON
```
should do the trick.

**Comment by jedwards4b** [comment]
You can also adjust the blocksize with a call to pio_set_blocksize, or PIOc_set_blocksize.    The first value in the warning is the size you should set to.
