### ISSUE TITLE
Implement PIO1 rearranger flow control options in PIO2

### ISSUE THREAD

**Issue by jayeshkrishna** [NCAR/ParallelIO#120]
PIO1 allows user to set flow control options (the internal flow
control parameters that determine how the data exchange
during data rearrangement works) at runtime by passing
the information via PIO_Init. We need to implement this
in PIO2.
The related Fortran namelists were added to PIO2 in
6aa3586fd2077aca74f39471488abcad17555b1a . See
PR #115

**Comment by jedwards4b** [comment]
What is the status of this work?

**Comment by jayeshkrishna** [comment]
Not started yet. Will start soon.

**Comment by jayeshkrishna** [comment]
This work is in progress.

**Comment by jayeshkrishna** [comment]
PR #479 fixed this issue.
