### ISSUE TITLE
Increase default buffer from 10MB

### ISSUE THREAD

**Issue by edhartnett** [NCAR/ParallelIO#1203]
In pio_darray.c we have:

```
/* 10MB default limit. */
PIO_Offset pio_buffer_size_limit = 10485760;

```
10 MB seems very low. I think we could easily go to 100 MB or even 1 GB. Most systems that are running PIO will have much more memory than 10 MB.

@jedwards4b any thoughts on this?

**Comment by jedwards4b** [comment]
yes, this is pretty small

**Comment by edhartnett** [comment]
OK, shall I make it 100 MB?

Anyone else want to chime in with an opinion?
