### ISSUE TITLE
test_common should provide correct ntasks for tests 

### ISSUE THREAD

**Issue by jedwards4b** [NCAR/ParallelIO#121]
Each test passes in the target_ntasks for its test,  if the *ntasks value is
less than target ntasks then it makes sense to fail the test, but if it is 
greater than target_ntasks pio_test_init should return a communicator initialized to the 
requested size.

**Comment by edhartnett** [comment]
Not sure I understand this issue.

I  have some simple tests that rely on having 2, 3, or 4 tasks. They are currently not written to handle more tasks than that. Is that not OK?

**Comment by jedwards4b** [comment]
This issue is resolved in the current master: pio_init_test now returns test_comm based on the number of tasks requested in the test so that as long as you started the job with at least the number of tasks you need it completes correctly.   In general I would like to avoid tests that require a fixed number of tasks and write them to adapt to the number of tasks provided.

**Comment by edhartnett** [comment]
OK I will keep this in mind for the future...
