### ISSUE TITLE
Improve cmake error message

### ISSUE THREAD

**Issue by jedwards4b** [NCAR/ParallelIO#1225]
I'm moving up to the latest (2_3_0) PIO now that MPAS-A supports it.
I especially wanted to be able to run the regression-tests, for validating the PIO install.
Here's one oddity in the build: I use this variable to specify the NetCDF/Fortran location

-D NetCDF_Fortran_PATH=.....
which is ok, but if I *don't* set it, I get this message:
-- Could NOT find NetCDF_Fortran (missing:  NetCDF_Fortran_LIBRARY NetCDF_Fortran_INCLUDE_DIR) 
CMake Error at src/flib/CMakeLists.txt:267 (message):
  Must have PnetCDF and/or NetCDF Fortran libraries
Setting these two variables doesn't do anything, can you have the message give the right variable?
As it was, I had to grep through the source to find the right variable to set.
Thanks,

                     Carl Ponder

**Comment by edhartnett** [comment]
I believe this is fixed in the current master and in 2.3.1. I will close this ticket.
