### ISSUE TITLE
MPI hang in allreduce

### ISSUE THREAD

**Issue by jedwards4b** [NCAR/ParallelIO#1228]
This issue presents in a cesm test ERS_D.f19_f19.FHIST_DEV.cheyenne_intel
I have not yet been able to reproduce in a simple test.
The case is using 72 total tasks and 2 io tasks.
The issue is that all tasks arrive at subroutine cn_buffer_report (pio_darray_int.c) with collective = 1
but the iotasks arrive with CN_bpool=NULL while all others have values > 0.  This results
in an MPI hang at line 1412.

I have traced the problem to the brel call in pio_darray.c at line 761 which is called only for iotasks and may free CN_bpool through a call to bpool_free made from line 1024 of bget.c 

I have found that commenting out the call at line 1024 of bget.c eliminates the problem.  I think that a very similar problem occurs with PIO_USE_MALLOC - I still need to pursue this more to be certain.

**Comment by edwardhartnett** [comment]
There have been many changes since this issue. I'm going to assume it is no longer relevant and close it. Please reopen it if necessary.
