### ISSUE TITLE
Incorrect type for `mpi_type` in pioc_support.c

### ISSUE THREAD

**Issue by mgduda** [NCAR/ParallelIO#1229]
The type for `mpi_type` in the routines `inq_file_metadata` and `PIOc_openfile_retry` in `pioc_support.c` is `int` but should be `MPI_Datatype` because `mpi_type` is used in calls to, e.g., `MPI_Type_size` (https://www.open-mpi.org/doc/v2.0/man3/MPI_Type_size.3.php). In most implementations of MPI, the size of `MPI_Datatype` is the same as the size of `int`, but in some versions of OpenMPI, `MPI_Datatype` actually has a size of 8. This leads to memory errors and segfaults in PIO.

**Comment by mgduda** [comment]
I've addressed this issue with the changes in this commit: https://github.com/mgduda/ParallelIO/commit/426af22 . Perhaps these can serve as a starting point for a more solid fix from someone with a better understanding of the code in `pioc_support.c`.

**Comment by edhartnett** [comment]
Yes, I agree. Thanks for the PR. I will see if I can get these changes in.

**Comment by mgduda** [comment]
It looks like PR #1231 has already been merged to `master`.

**Comment by jedwards4b** [comment]
This issue appears to be resolved.
