### ISSUE TITLE
Generated files in repo?

### ISSUE THREAD

**Issue by gold2718** [NCAR/ParallelIO#1230]
There are some generated files in the repo which are clutter (IMHO).
Can they be removed?
```
doc/CMakeFiles/CMakeOutput.log
doc/CMakeFiles/cmake.check_cache
```

**Comment by jedwards4b** [comment]
yes they should be removed and added to the .gitignore

**Comment by edhartnett** [comment]
These files are not in the repo, so I am going to close this ticket.
