### ISSUE TITLE
 pio_iosystem_tests3 fails on nwsc-caldera07 in an interesting way

### ISSUE THREAD

**Issue by edhartnett** [NCAR/ParallelIO#124]
(t_initf)  profile_global_stats= T  profile_papi_enable= F
 PIO_TF: Starting three_files_two_iosystems_with_overlap
MPI_Group_range_incl: more than 1 proc in group
forrtl: error (76): Abort trap signal

**Comment by jayeshkrishna** [comment]
What is the environment on the machine (mpi lib etc.)? Can you run multiple MPI processes on the node (is it a login node ?)?

**Comment by edhartnett** [comment]
CDash output is here: http://my.cdash.org/testDetails.php?test=28045868&build=1068453

**Comment by jedwards4b** [comment]
As suggested by the build name this is a serial build of the library, the only functional method is netcdf and there is only one task.  This test should be skipped.

**Comment by jayeshkrishna** [comment]
Ok, I will make sure that the test works for netcdf-only cases.
