### ISSUE TITLE
bug in PIOc_inq_unlimdims

### ISSUE THREAD

**Issue by jedwards4b** [NCAR/ParallelIO#1242]
In inq_unlimdims_handler unlimdimidsp is set to 
int unlimdimids;  
this is wrong because it is an array of integers and not just a single one.

**Comment by edwardhartnett** [comment]
OK but this is merely academic and untestable as well, since PIO cannot open files with multiple unlimited dimensions. ;-)

**Comment by edwardhartnett** [comment]
The mandatory limit of one unlimited dim is checked on file open. I will close this ticket.
