### ISSUE TITLE
Can't open perl script "../bin/genf90.pl": No such file or directory,    for version 1.7.1

### ISSUE THREAD

**Issue by xinzhang8noaa** [NCAR/ParallelIO#1245]
I try to compile the version 1.7.1 follow the instructions. but get the errors as::

Any help is appreciated.

Thanks,

checking for xlc... no
checking for cc... no
checking for gcc... gcc
checking for C compiler default output file name... a.out
checking whether the C compiler works... yes
checking whether we are cross compiling... no
checking for suffix of executables... 
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking whether byte ordering is bigendian... no
checking for gfortran... gfortran
checking whether we are using the GNU Fortran compiler... yes
checking whether gfortran accepts -g... yes
checking for Fortran flag to compile .F90 files... none
checking for Fortran flag needed to accept free-form source... none
checking for Fortran flag needed to accept 132 column source lines... none
checking for Fortran flag to compile preprocessed .F files... none
checking how to define symbols for preprocessed Fortran... -D
checking for ftn... mpif90
checking for MPI_Init... yes
checking for mpif.h... yes
checking for Fortran flag to compile .F90 files... (cached) none
checking for mpi.mod... yes
checking Fortran support for c_sizeof()... yes
checking MPI-IO support in MPI implementation... no
Full hostname= 944b932d3656
Hostname=944b932d3656
Machine=x86_64
OS=Linux
checking Fortran 90 module extension... mod
checking Fortran 90 module inclusion flag... -I
using PNETCDF_PATH from environment
checking for pnetcdf.inc in /usr/local/include... yes
checking for libpnetcdf.a in /usr/local/lib... yes

Output Variables: {CC=gcc} {FC=gfortran} {CXX=} {MPICC=} {MPIFC=mpif90}{MPICXX=} {FPPFLAGS=} {LD=mpif90} {OPT=} {BIT64=} {REAL8=} {ENDIAN=} {FFLAGS= } {CFLAGS=-g -O2} {FCFLAGS=-g -O2} {FC_DEFINE=-D} {MPI_INC=} {MPI_LIB=} {MODINC=} {AR=ar} {ARFLAGS=cq} {USE_PNETCDF=yes} {PNETCDF_PATH=/usr/local} {USE_NETCDF=no} {NETCDF_PATH=} {USE_COMPRESSION=no} {CPPDEFS= -DSPMD -DHAVE_MPI -DSYSLINUX -D_NONETCDF -D_PNETCDF} {INCLUDEPATH= -I/usr/local/include} {LDLIBS= -L/usr/local/lib -lpnetcdf} {DEBUG=no}

configure: creating ./config.status
config.status: creating Makefile.conf
config.status: creating config.h
Please check the Makefile.conf
Have a nice day!
Making dependencies for pio.F90 --> pio.d
Making dependencies for pio_kinds.F90 --> pio_kinds.d
Making dependencies for nf_mod.F90 --> nf_mod.d
Making dependencies for ionf_mod.F90 --> ionf_mod.d
Making dependencies for pio_types.F90 --> pio_types.d
Making dependencies for calcdecomp.F90 --> calcdecomp.d
Making dependencies for piolib_mod.F90 --> piolib_mod.d
Making dependencies for pio_mpi_utils.F90 --> pio_mpi_utils.d
Making dependencies for pio_nf_utils.F90 --> pio_nf_utils.d
Making dependencies for pio_utils.F90 --> pio_utils.d
Making dependencies for pio_msg_mod.F90 --> pio_msg_mod.d
Making dependencies for calcdisplace_mod.F90 --> calcdisplace_mod.d
Making dependencies for pio_msg_callbacks.F90 --> pio_msg_callbacks.d
Making dependencies for pio_support.F90 --> pio_support.d
Making dependencies for C_interface_mod.F90 --> C_interface_mod.d
Making dependencies for pionfatt_mod.F90 --> pionfatt_mod.d
Making dependencies for pionfread_mod.F90 --> pionfread_mod.d
Making dependencies for pionfwrite_mod.F90 --> pionfwrite_mod.d
/usr/bin/perl ../bin/genf90.pl pionfput_mod.F90.in > pionfput_mod.F90
Can't open perl script "../bin/genf90.pl": No such file or directory
make: *** [pionfput_mod.F90] Error 2
Makefile:125: recipe for target 'pionfput_mod.F90' failed
The command '/bin/sh -c git clone -b pio1_7_1  https://github.com/NCAR/ParallelIO.git     && cd ParallelIO     && export MPIFC=mpif90     && export PNETCDF_PATH=${PNETCDF}     && cd pio     && ./configure --prefix=/usr/local --disable-netcdf     && make     && make install     && rm -fr ParallelIO' returned a non-zero code: 2

**Comment by jedwards4b** [comment]
It should have downloaded genf90 from https://github.com/PARALLELIO/genf90
you can get it manually.
are you using cmake or autoconf to build?

**Comment by gold2718** [comment]
1.7.1 is an old tag that was probably trying to download:
https://parallelio.googlecode.com/svn/genf90/trunk_tags/genf90_130402
which has been shut down. I think @jedwards4b's suggestion to download genf90 manually into the bin directory is your best bet.

**Comment by xinzhang8noaa** [comment]
Many Thanks ! It solve my problem
