### ISSUE TITLE
test_pioc, test_darray, pio_decomp_fillval fails for PIO 2.x.x with netCDF-c 4.5.0 

### ISSUE THREAD

**Issue by mhros** [NCAR/ParallelIO#1248]
I get 
```
97% tests passed, 3 tests failed out of 95

Total Test time (real) = 795.48 sec

The following tests FAILED:
     14 - test_pioc (Failed)
     18 - test_darray (Failed)
     89 - pio_decomp_fillval (Failed)
```
when building PIO 2.x.x with [Intel Cluster Toolkit 2017.1.132 and GCC 6.3.0](https://github.com/easybuilders/easybuild-easyconfigs/blob/master/easybuild/easyconfigs/i/intel/intel-2017a.eb) and [MVAPICH and GCC 4.9.3-2.25](https://github.com/easybuilders/easybuild-easyconfigs/blob/master/easybuild/easyconfigs/g/gmvolf/gmvolf-2016a.eb), respectively.

All tests pass when changing netCDF version to 4.4.1.1

Other deps: hdf5-1.8.20, netcdf-fortran-4.4.3, pnetcdf-1.8.1

**Comment by jedwards4b** [comment]
@edhartnett I can confirm this result, are you aware of it?

**Comment by edhartnett** [comment]
Before I swing back and take a look at this, I need to finish some work I'm doing on the netcdf library...

I will see if I can take a look next week.

**Comment by jedwards4b** [comment]
This is an issue in netcdf-4.5.0 https://github.com/Unidata/netcdf-c/issues/730

**Comment by edhartnett** [comment]
I just built the C PIO library and all tests pass with (something like) the netCDF master branch.

NetCDF is going to release 4.6.0 this week or next, and hopefully then we can close this issue.

**Comment by edhartnett** [comment]
I take that last comment back. We are not working well with the current netCDF master. I will continue to work on that.

**Comment by edhartnett** [comment]
I am putting up a PR now with some fixes for the latest netCDF releases. Now all C tests pass with netcdf 4.5.0 and the latest netCDF master. The fortran test pio_decomp_fillval also now passes.

But the fortran test pio_decomp_frame_tests fails. I am working on that next.

**Comment by edwardhartnett** [comment]
I will close this issue, as we no longer support netcdf-4.5.0. At least 4.6.1 is required for the current release.
