### ISSUE TITLE
Turn off any support for varm functions in PIO

### ISSUE THREAD

**Issue by edhartnett** [NCAR/ParallelIO#1269]
The varm functions (nc_get_varm_int(), nc_put_varm_int(), etc.) are deprecated in netCDF. They are completely unnecessary, since everything they do can also be done by the vars functions + some user code to transpose arrays (and the user should be the one to write and maintain that for themselves).

In practice, no one uses the varm functions in the netCDF world. They are too complicated to figure out.

The varm functions in PIO are old code that I have never touched. They are not tested anywhere and do not support async mode. Nor do I intend to add code to support async mode, or to add tests.

Basically, unless someone wants to immediately step up and provide good support for these functions (including C tests), they should be removed. Otherwise we are shipping untested code that we hope no user ever uses. That's just silly.

No users should use the varm functions in netCDF, and certainly not in PIO. I don't even want to imagine how much time and energy would be required to get these working and tested, only for them to remain unused. (Or, if used, we will get some incredibly complicated support questions we don't want to figure out.)

So we should simply remove all the varm functions from the PIO library. 

In the netCDF integration, using the varm functions with NC_PIO will result in an NC_EINVAL error. This will bother no one, since, in practice, no one in their right mind uses the varm functions.

@jedwards4b speak now or forever hold your peace. ;-)

**Comment by jedwards4b** [comment]
I'm pretty sure it's the case that noone uses these functions.  pio's reordering capabilities should be used instead.

**Comment by edhartnett** [comment]
OK, I will remove them. 2.3.1 will be the last PIO release with the varm functions.
