### ISSUE TITLE
DOF with holes does not read correctly with mpi-serial

### ISSUE THREAD

**Issue by gold2718** [NCAR/ParallelIO#1277]
I'm currently running into this on Hobart with a current (very close to master) version of CIME. I'm not sure how to get the PIO or NetCDF version in this situation.
The issue is doing a read_darray in serial mode seems to leave out the zero DOF entries so that the destination array has packed values.
With 1 task using MPI, things work fine and get the same answer as 48 tasks. The DOF arrays being passed to pio_initdecomp are the same but the read-in arrays are different.

As an example:

I have an array initially set to -1
The DOF is `1,  2,  3,  0,  4,  5,  0,  6,  7`
The values on file are `1,  2,  3,  4,  5,  6,  7'

With holes, the correct read is:

`array = 1,   2,   3,   -1,  4,  5,  -1,   6,   7`

that is, the positive numbers were read into the correct places. In serial mode, I get:

`array = 1,   2,   3,    4,  5,  6,   7,  -1,   -1`

I see this behavior with both PIO1 (Nag) and PIO2 (PGI) on Hobart.

**Comment by jedwards4b** [comment]
@edhartnett is there a test of read with holes in the repo?  So far unable to reproduce this problem and think it may be netcdf version.   @gold2718 the netcdf version is listed in env_mach_specific

**Comment by jedwards4b** [comment]
@gold2718 I am not able to reproduce the problem as you describe it above, although I can reproduce the original cam-se problem.

**Comment by jedwards4b** [comment]
I figured out a test case, the problem is in mpi-serial and I will report it there.

**Comment by jedwards4b** [comment]
Moved to https://github.com/MCSclimate/MCT/issues/53

**Comment by gold2718** [comment]
Moved to MCSclimate/mpi-serial#11
