### ISSUE TITLE
try to access genf90 while compiling

### ISSUE THREAD

**Issue by hxmhuang** [NCAR/ParallelIO#1280]
I failed to compile ParallelIO on a cluster that cannot access the internet. 
seems it trying to access internet to get genf90, any suggestions?
============================
[ 48%] Performing download step (git clone) for 'genf90'
Initialized empty Git repository in /GPFS/cess/sxzhang/Projects/ParallelIO/build/src/flib/genf90/src/genf90/.git/
error: Couldn't resolve host 'github.com' while accessing https://github.com/PARALLELIO/genf90/info/refs

**Comment by jedwards4b** [comment]
Access it from another machine and then copy it into place on the machine you need it on.

**Comment by cmyf123** [comment]
when i try to download the genf90 form  https://github.com/PARALLELIO/genf90/info/refs, it shows that Page not found. what should i do? thanks.

**Comment by edwardhartnett** [comment]
Can you try the autotools build instead of the CMake build?
