### ISSUE TITLE
enable run with mpirun instead of mpiexec

### ISSUE THREAD

**Issue by edhartnett** [NCAR/ParallelIO#1282]
When I run ctest, they all fail because it’s using mpiexec instead of mpirun for the MPI launch command.  On Theia with IMPI it needs mpirun because that’s how they’ve configured the system.  I tried fiddling with the cmake config to fix it, but couldn’t make it work since I’m a cmake newbie.  I just couldn’t find the spot where that gets set.

Do you know the magic sauce to tell ctest to use mpirun instead of mpiexec when executing the tests?

Thanks for and words of wisdom you may have,

Chris
-----------------------------------------------------------------------------------------------------------
Christopher W. Harrop

**Comment by jedwards4b** [comment]
Hi Chris,
The mpi formulas are defined in the ctest subdirectory in the files mpiexec.*.  You will need to figure out from the cmake log which environment you are invoking or define and invoke a new one.

**Comment by christopherwharrop-noaa** [comment]
Hi,

I was able to get Theia added to the configuration by creating a new "cmake/mpiexec.theia" file with the proper launch command.  I also had to add a "elseif" stanza in the "cmake/LibMPI.cmake" file.  

I am really concerned about this method of defining the launch command for the tests.  The entire point of CMake is to increase portability without using brittle constructs that have to be manually maintained.  Having specific machine dependencies is the exact problem that CMake was designed to solve.  In the case of Theia, the machine detection is based on the hostname starting with "tfe" which may not be unique.  There has to be a better way to do this.

**Comment by christopherwharrop-noaa** [comment]
One possibility might be to default to a "mpiexec -np $NP" unless the user specified something different.  And the user could use a -D in the cmake command to tell it what command to use.  For example, when building HDF5, you can tell it what to use like this:

`export RUNPARALLEL='mpirun -n $${NPROCS:=6}' `

Could something similar be adopted for PIO?

**Comment by jedwards4b** [comment]
Of course something like this could be adopted, it's mostly a matter of resources to make it happen, contributions are welcome.

**Comment by christopherwharrop-noaa** [comment]
Understood.  It's usually easier said than done.  If I come up with anything I'll certainly send it your way.  In the mean time I'll probably just submit a PR to get the command for Theia Intel into the current setup.

**Comment by christopherwharrop-noaa** [comment]
It's a bit worse than I thought.  I was in the process of putting together my PR to get Theia defined and then realized that it's not that simple.  On Theia, if one is using Intel MPI, then the launch command is mpirun.  But, if one is using mvapich2, then it is mpiexec.  In the "cmake/LibMPI.cmake" file, I don't know how to check what MPI stack was specified/found, so I don't know how to write the two "elseif" clauses to set the platform name.  We'll need two platform names: theia-impi and theia-mvapich2.

**Comment by edhartnett** [comment]
Better to allow the user to set the command I think.

This problem also exists in netCDF. When doing a parallel build, the parallel tests all use mpiexec. I would welcome a general solution.

I can substitute in a user command, and as long as it uses the same arguments (ex. -n 4 ./tst_program) then it will work. This will handle most cases.

**Comment by christopherwharrop-noaa** [comment]
Yeah, for NetCDF4, I do this:

`# Replace mpiexec with mpirun in "make check" scripts if we are using impi
if [ "${MPI}" == "impi" ]; then
  set +e
  for file in `ls -1 *test*/*.sh`; do
    grep mpiexec ${file} > /dev/null
    err=$?
    if [ ${err} -eq 0 ]; then
      sed 's/mpiexec/mpirun/g' ${file} > ${file}.new
      mv ${file}.new ${file}
      chmod ugo+x ${file}
    fi
  done
  set -e
fi
`
That's a bit more complicated than it needs to be, but... yeah.  It's a pain.

**Comment by jedwards4b** [comment]
Looking at the code in cmake/LibMPI.cmake it should do the right thing if your platform is "unknown"   if you add this line to the top level CMakeLists.txt at line 91 what do you get?
  message("MPIEXEC is ${MPIEXEC}, MPI_NUMPROC_FLAG is ${MPIEXEC_NUMPROC_FLAG}")

**Comment by christopherwharrop** [comment]
The problem is that IMPI does provide a mpiexec command and cmake manages to find it.  The reason that's a problem is because the way IMPI is installed on Theia, mpiexec is broken and is unusable.  So, users have been told, and this is in the user documentation, that they need to use mpirun for IMPI.  So, unfortunately, leaving it as "unknown" won't work.  Believe me, the fact that they leave broken tools lying around is baffling and frustrating.  But, there's not much I can do about that.

```
$ grep -i mpiexec build/CMakeCache.txt
MPIEXEC:FILEPATH=/apps/intel/impi/5.1.2.150/intel64/bin/mpiexec
MPIEXEC_MAX_NUMPROCS:STRING=2
//Flag used by MPI to specify the number of processes for MPIEXEC;
MPIEXEC_NUMPROC_FLAG:STRING=-np
//These flags will come after all flags given to MPIEXEC.
MPIEXEC_POSTFLAGS:STRING=
// run by MPIEXEC.
MPIEXEC_PREFLAGS:STRING=
//ADVANCED property for variable: MPIEXEC
MPIEXEC-ADVANCED:INTERNAL=1
//ADVANCED property for variable: MPIEXEC_MAX_NUMPROCS
MPIEXEC_MAX_NUMPROCS-ADVANCED:INTERNAL=1
//ADVANCED property for variable: MPIEXEC_NUMPROC_FLAG
MPIEXEC_NUMPROC_FLAG-ADVANCED:INTERNAL=1
//ADVANCED property for variable: MPIEXEC_POSTFLAGS
MPIEXEC_POSTFLAGS-ADVANCED:INTERNAL=1
//ADVANCED property for variable: MPIEXEC_PREFLAGS
MPIEXEC_PREFLAGS-ADVANCED:INTERNAL=1
$ 
```
