### ISSUE TITLE
Is NetCDF required by PIO?

### ISSUE THREAD

**Issue by wkliao** [NCAR/ParallelIO#1291]
The master branch does not seem to support PnetCDF-only build.
I got errors complaining about undefined references to NetCDF APIs.

**Comment by jedwards4b** [comment]
Although we test to make sure that we can do a netcdf only build we don't currently do this for pnetcdf only.

**Comment by wkliao** [comment]
In that case, may I suggest to revise README.md to reflect this fact?  In particular, the sentence:
"PIO can use NetCDF (version 4.3.3+) and/or PnetCDF (version 1.6.0+) for I/O."

**Comment by edhartnett** [comment]
At least netCDF classic is required. I will modify the README as you
suggest.
