### ISSUE TITLE
time for a new tag?

### ISSUE THREAD

**Issue by jedwards4b** [NCAR/ParallelIO#1301]

**Comment by jedwards4b** [comment]
Yes, we've had a request for a new release.   I'm looking into #1265 - would like to try to resolve it first.

**Comment by edhartnett** [comment]
Ok, great, I would like to resolve it too!

**Comment by jedwards4b** [comment]
@edhartnett I am continuing to work on #1265, but could you go ahead and make a new release tag.  Thanks

**Comment by edhartnett** [comment]
OK, it's been a long time, but I would like to do a release.

Unfortunately I can't get the fortran tests to build. Are they working?

I can do a C-only library release - should I do that?

**Comment by jedwards4b** [comment]
Nope, if you look at the cash page you'll see that they are building and working fine. 
https://my.cdash.org/index.php?project=PIO&date=2019-01-05
Perhaps I can help you resolve the issue on your platform?
