### ISSUE TITLE
Building PIO using ESMF's "mpiuni"?

### ISSUE THREAD

**Issue by bekozi** [NCAR/ParallelIO#1310]
Hi. I am working towards building PIO using ESMF's "mpiuni" stub library. For the record, I am definitely not expecting this to work out of the box! Right now, I am stuck on the PIO build configuration. _Note: I did change "mpi-serial" to "esmf"  and "mpi.mod" to "esmf.mod" in `FindMPISERIAL.cmake`._

From what you can tell, do I at least have the appropriate build flags / locations (I left out the netCDF flags, etc.)?:
```
PIO_DIR=.../ParallelIO
ESMF_DIR=.../esmf
ESMF_INSTALL_DIR=.../sandbox/esmf/master-mpiuni/install

ESMF_MPIUNI_DIR=${ESMF_DIR}/src/Infrastructure/stubs/mpiuni

cmake -DPIO_USE_MPISERIAL=ON \
      -DMPISERIAL_INCLUDE_DIRS="${ESMF_MPIUNI_DIR} ${ESMF_INSTALL_DIR}/mod" \
      -DMPISERIAL_C_LIBRARY="${ESMF_INSTALL_DIR}/lib/libesmf.so" \
      -DMPISERIAL_Fortran_LIBRARY="${ESMF_INSTALL_DIR}/lib/libesmf.so" \
      <netCDF build flags> \
      ${PIO_DIR}
```
Contents of `.../stubs/mpiuni` ([SF source link](https://sourceforge.net/p/esmf/esmf/ci/master/tree/src/Infrastructure/stubs/mpiuni/)):
```
makefile  mpi.c  mpif.h  mpi.h  mpirun
```
This is the CMake Error:
```
-- Importing CMake_Fortran_utils
-- Importing CMake_Fortran_utils - success
CMake Error at /usr/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:148 (message):
  Could NOT find MPISERIAL_C (missing: MPISERIAL_C_LIBRARY
  MPISERIAL_C_INCLUDE_DIR)
Call Stack (most recent call first):
  /usr/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:388 (_FPHSA_FAILURE_MESSAGE)
  cmake/LibFind.cmake:302 (find_package_handle_standard_args)
  cmake/FindMPISERIAL.cmake:40 (find_package_component)
  CMakeLists.txt:92 (find_package)
  ```
  Thanks!

**Comment by jedwards4b** [comment]
It's looking for a compiled library.  It looks like what you have there is just source code.

**Comment by bekozi** [comment]
`libesmf.so` is compiled. Is it expecting static libraries? I noticed that mpi-serial seems to only compile a static library.

**Comment by jedwards4b** [comment]
LibFind.cmake should find either a shared or static library.   You'll need to debug the cmake to figure out what is going on.   I hope that you can make your modifications to FindMPISERIAL.cmake and whatever else you need to change in a backward compatible manner.

**Comment by bekozi** [comment]
In your mind, could there eventually be a PIO build option like `PIO_MPISERIAL_MODE=mpi-serial/esmf`? Is it worth considering a FindESMFMPIUNI.cmake? I'm wondering how this may eventually look when configuring PIO with mpiuni.
> I hope that you can make your modifications to FindMPISERIAL.cmake and whatever else you need to change in a backward compatible manner.

Sorry, only forward. 😉

**Comment by jedwards4b** [comment]
Before we can propose fixes to the problem we need to identify exactly what the problem is.  Introducing a new find module for esmf is not the most attractive solution.

**Comment by bekozi** [comment]
PR https://github.com/NCAR/ParallelIO/pull/1311 allows me to set user-defined package components using environment variables. I can now do something like below to move past configuration and get build errors.
```cmake
set(PIO_USE_MPISERIAL "ON")
set(ESMF_MPIUNI_DIR ".../esmf/src/Infrastructure/stubs/mpiuni")
set(MPISERIAL_C_INCLUDE_DIR ${ESMF_MPIUNI_DIR})
set(MPISERIAL_Fortran_INCLUDE_DIR ${ESMF_MPIUNI_DIR})
set(MPISERIAL_C_LIBRARY ${ESMF_INSTALL_DIR}/lib/libesmf.so)
set(MPISERIAL_Fortran_LIBRARY ${ESMF_INSTALL_DIR}/lib/libesmf.so)
```
It might be nice sometime to get an ESMF mpiuni build supported directly but that can definitely wait.

**Comment by edwardhartnett** [comment]
Is this still active?

**Comment by bekozi** [comment]
I think it is fine to close for now. It can be reopened if needed.
