### ISSUE TITLE
Cant build on HPC theia...

### ISSUE THREAD

**Issue by edhartnett** [NCAR/ParallelIO#1313]
When attempting to build on theia I see:

-- Check size of long long - failed
CMake Error at src/clib/CMakeLists.txt:162 (message):
  size_t and long long must be the same size!

Why must size_t and long long be the same size?

**Comment by jedwards4b** [comment]
git blame says that you added that section @edhartnett 
But I think that it may have something to do with making sure that MPI datatypes and c datatypes are consistent.

**Comment by edhartnett** [comment]
Well I am an idiot.

Not sure what to do now...
