### ISSUE TITLE
Error dependencies of target examplePio_f90

### ISSUE THREAD

**Issue by yuemaaa** [NCAR/ParallelIO#1315]
I use cmake to build PIO by
`cmake -DNetCDF_C_PATH=$NETCDF -DNetCDF_Fortran_PATH=$NETCDF -DPnetCDF_PATH=$PNETCDF -DCMAKE_INSTALL_PREFIX=$LIBBASE -DPIO_ENABLE_TIMING=OFF $PIOSRC`
While making pio, the problem as follow
`Scanning dependencies of target examplePio_f90
[ 90%] Building Fortran object examples/f03/CMakeFiles/examplePio_f90.dir/examplePio.f90.o
/gpfs01/home/mayue2017/MPAS/sources/ParallelIO/examples/f03/examplePio.f90:148.8:

        class(pioExampleClass), intent(inout) :: this
        1
Error: Unclassifiable statement at (1)
/gpfs01/home/mayue2017/MPAS/sources/ParallelIO/examples/f03/examplePio.f90:157.47:

        call MPI_Comm_rank(MPI_COMM_WORLD, this%myRank, ierr)
                                               1
Error: Syntax error in argument list at (1)
/gpfs01/home/mayue2017/MPAS/sources/ParallelIO/examples/f03/examplePio.f90:158.47:

        call MPI_Comm_size(MPI_COMM_WORLD, this%ntasks , ierr)
                                               1
Error: Syntax error in argument list at (1)
/gpfs01/home/mayue2017/MPAS/sources/ParallelIO/examples/f03/examplePio.f90:164.8:

        this%stride        = 1
        1
Error: Unclassifiable statement at (1)
/gpfs01/home/mayue2017/MPAS/sources/ParallelIO/examples/f03/examplePio.f90:165.8:

        this%numAggregator = 0
        1
Error: Unclassifiable statement at (1)
/gpfs01/home/mayue2017/MPAS/sources/ParallelIO/examples/f03/examplePio.f90:166.8:

        this%optBase       = 1
        1
Error: Unclassifiable statement at (1)
/gpfs01/home/mayue2017/MPAS/sources/ParallelIO/examples/f03/examplePio.f90:167.8:

        this%iotype        = PIO_iotype_netcdf
        1
Error: Unclassifiable statement at (1)
/gpfs01/home/mayue2017/MPAS/sources/ParallelIO/examples/f03/examplePio.f90:168.8:

        this%fileName      = "examplePio_f90.nc"
        1
Error: Unclassifiable statement at (1)
/gpfs01/home/mayue2017/MPAS/sources/ParallelIO/examples/f03/examplePio.f90:169.8:

        this%dimLen(1)     = LEN
        1
Error: Unclassifiable statement at (1)
/gpfs01/home/mayue2017/MPAS/sources/ParallelIO/examples/f03/examplePio.f90:171.8:

        this%niotasks = this%ntasks ! keep things simple - 1 iotask per MPI pro
        1
Error: Unclassifiable statement at (1)
/gpfs01/home/mayue2017/MPAS/sources/ParallelIO/examples/f03/examplePio.f90:175.26:

        call PIO_init(this%myRank,      & ! MPI rank
                          1
Error: Syntax error in argument list at (1)
/gpfs01/home/mayue2017/MPAS/sources/ParallelIO/examples/f03/examplePio.f90:188.8:

        this%arrIdxPerPe = LEN / this%ntasks
        1
Error: Unclassifiable statement at (1)
/gpfs01/home/mayue2017/MPAS/sources/ParallelIO/examples/f03/examplePio.f90:190.16:

        if (this%arrIdxPerPe < 1) then
                1
Error: Syntax error in IF-expression at (1)
/gpfs01/home/mayue2017/MPAS/sources/ParallelIO/examples/f03/examplePio.f90:191.21:

            call this%errorHandle("Not enough work to distribute among pes", ER
                     1
Error: Syntax error in CALL statement at (1)
/gpfs01/home/mayue2017/MPAS/sources/ParallelIO/examples/f03/examplePio.f90:192.11:

        endif
           1
Error: Expecting END SUBROUTINE statement at (1)
/gpfs01/home/mayue2017/MPAS/sources/ParallelIO/examples/f03/examplePio.f90:194.8:

        this%ista = this%myRank * this%arrIdxPerPe + 1
        1
Error: Unclassifiable statement at (1)
/gpfs01/home/mayue2017/MPAS/sources/ParallelIO/examples/f03/examplePio.f90:195.8:

        this%isto = this%ista + (this%arrIdxPerPe - 1)
        1
Error: Unclassifiable statement at (1)
/gpfs01/home/mayue2017/MPAS/sources/ParallelIO/examples/f03/examplePio.f90:197.21:

        allocate(this%compdof(this%ista:this%isto))
                     1
Error: Syntax error in ALLOCATE statement at (1)
/gpfs01/home/mayue2017/MPAS/sources/ParallelIO/examples/f03/examplePio.f90:198.21:

        allocate(this%dataBuffer(this%ista:this%isto))
                     1
Error: Syntax error in ALLOCATE statement at (1)
/gpfs01/home/mayue2017/MPAS/sources/ParallelIO/examples/f03/examplePio.f90:199.21:

        allocate(this%readBuffer(this%ista:this%isto))
                     1
Error: Syntax error in ALLOCATE statement at (1)
/gpfs01/home/mayue2017/MPAS/sources/ParallelIO/examples/f03/examplePio.f90:201.8:

        this%compdof(this%ista:this%isto) = (/(i, i=this%ista,this%isto, 1)/)
        1
Error: Unclassifiable statement at (1)
/gpfs01/home/mayue2017/MPAS/sources/ParallelIO/examples/f03/examplePio.f90:202.8:

        this%dataBuffer(this%ista:this%isto) = this%myRank + VAL
        1
Error: Unclassifiable statement at (1)
/gpfs01/home/mayue2017/MPAS/sources/ParallelIO/examples/f03/examplePio.f90:203.8:

        this%readBuffer(this%ista:this%isto) = 0
        1
Error: Unclassifiable statement at (1)
/gpfs01/home/mayue2017/MPAS/sources/ParallelIO/examples/f03/examplePio.f90:211.8:

        class(pioExampleClass), intent(inout) :: this
        1
Error: Unclassifiable statement at (1)
/gpfs01/home/mayue2017/MPAS/sources/ParallelIO/examples/f03/examplePio.f90:216.8:

        start(1) = this%ista
        1
Error: Unclassifiable statement at (1)
Fatal Error: Error count reached limit of 25.
make[2]: *** [examples/f03/CMakeFiles/examplePio_f90.dir/examplePio.f90.o] Error 1
make[1]: *** [examples/f03/CMakeFiles/examplePio_f90.dir/all] Error 2
make: *** [all] Error 2
`

I have no idea how to fix it.

**Comment by jedwards4b** [comment]
I believe that the fortran compiler you are using is too old to support these f2003 statements.   Nearly all recent compilers support these features - can you update to a newer compiler.

**Comment by yuemaaa** [comment]
I only have a non-root account and the GNU version is 4.4.6. It may looks like too old for building PIO2.

**Comment by jedwards4b** [comment]
You might try disabling the examples with -DPIO_ENABLE_EXAMPLES=OFF 
But you really need to contact your system administrators and request a compiler update.
