### ISSUE TITLE
autotools build not working on current master

### ISSUE THREAD

**Issue by edhartnett** [NCAR/ParallelIO#1320]
I just checked out master and tried to build, but got a failure:

`autoreconf -i && CC=mpicc CPPFLAGS=-I/usr/local/netcdf-c-4.6.2_mpich-3.2/include LDFLAGS=-L/usr/local/netcdf-c-4.6.2_mpich-3.2/lib ./configure && make check
`
and I get:

`FAIL: run_tests.sh`

Running the test itself I see the problem is test_pioc:

```
mpiexec -n 4 ./test_pioc

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   PID 4448 RUNNING AT mikado
=   EXIT CODE: 139
=   CLEANING UP REMAINING PROCESSES
=   YOU CAN IGNORE THE BELOW CLEANUP MESSAGES
===================================================================================
YOUR APPLICATION TERMINATED WITH THE EXIT STRING: Segmentation fault (signal 11)
This typically refers to a problem with your application.
Please see the FAQ page for debugging suggestions
ed@mikado:~/tmp/ParallelIO/tests/cunit$ 
```

**Comment by jedwards4b** [comment]
Can you provide more information?  Compiler version, os, etc - typically this error (segfault with no other output) indicates a problem with mpi and not with the test itself.

**Comment by edhartnett** [comment]
This turns out to be a bug in netCDF 4.6.2. I am fixing now...

**Comment by edhartnett** [comment]
Well it's also a PIO issue. I now have to change the PIO code to not rely on NULL being a valid stride (standing for all 1's).

An annoyance, but required if PIO is to work with netCDF 4.6.2. So I will reopen this issue and submit a PR with those changes.

**Comment by jedwards4b** [comment]
I just want to make sure I'm understanding this - [netcdf 4.6.2 is broken](https://github.com/Unidata/netcdf-c/issues/1265) and this will be fixed in the next netcdf release but we still want to put a hack in pio so that it works with that version.   Is that right?

**Comment by edhartnett** [comment]
Yes, otherwise we will have to constantly answer support questions about why PIO is broken with netcdf 4.6.2. ;-)

It's a simple hack that won't affect performance.

**Comment by jedwards4b** [comment]
Hi Ed - what is the ETA on this change?

**Comment by edhartnett** [comment]
Will try to get to it next week...

**Comment by edhartnett** [comment]
Working on this now...
