### ISSUE TITLE
 errors occur while Performing download step (git clone) for 'genf90'

### ISSUE THREAD

**Issue by cmyf123** [NCAR/ParallelIO#1324]
when I try to make, some errors occur. 
error:  while accessing https://github.com/PARALLELIO/genf90/info/refs
fatal: HTTP request failed

And,I found that there is no such page in github: https://github.com/PARALLELIO/genf90/info/refs
what should I do?

**Comment by jedwards4b** [comment]
Here is the genf90 repo 
https://github.com/PARALLELIO/genf90/
