### ISSUE TITLE
cmake fortran test build failing due to MPI_SCATTER

### ISSUE THREAD

**Issue by edhartnett** [NCAR/ParallelIO#1328]
The cmake fortran build is failing for me:

```
cd /home/ed/tmp/ParallelIO/build/tests/general && /usr/local/bin/mpifort -DCPRGNU -DHAVE_MPI -DINCLUDE_CMAKE_FCI -DLINUX -DLOGGING -DNETCDF_C_LOGGING_ENABLED -DTIMING -DUSE_PNETCDF_VARN -DUSE_PNETCDF_VARN_ON_READ -D_NETCDF -D_NETCDF4 -D_PNETCDF -I/home/ed/tmp/ParallelIO/src/flib -I/home/ed/tmp/ParallelIO/build/src/flib -I/usr/local/netcdf-fortran-4.4.4_c_4.4.1.1_mpich-3.2/include -I/usr/local/pnetcdf-1.11.0_shared/include -I/home/ed/tmp/ParallelIO/src/clib -I/usr/local/netcdf-c-4.6.2_mpich-3.2/include -I/home/ed/tmp/ParallelIO/src/gptl -I/home/ed/tmp/ParallelIO/build/src/gptl  -ffree-line-length-none -c /home/ed/tmp/ParallelIO/build/tests/general/pio_decomp_tests_1d.F90 -o CMakeFiles/pio_decomp_tests_1d.dir/pio_decomp_tests_1d.F90.o
/home/ed/tmp/ParallelIO/build/tests/general/pio_decomp_tests_1d.F90:1260:26:

   use mpi, only : MPI_INT, MPI_SCATTER
                          1
Error: Symbol ‘mpi_scatter’ referenced at (1) not found in module ‘mpi’
/home/ed/tmp/ParallelIO/build/tests/general/pio_decomp_tests_1d.F90:1491:26:

   use mpi, only : MPI_INT, MPI_SCATTER
                          1
Error: Symbol ‘mpi_scatter’ referenced at (1) not found in module ‘mpi’
/home/ed/tmp/ParallelIO/build/tests/general/pio_decomp_tests_1d.F90:1722:26:

   use mpi, only : MPI_INT, MPI_SCATTER
                          1
Error: Symbol ‘mpi_scatter’ referenced at (1) not found in module ‘mpi’

```

Does anyone know what this MPI_SCATTER is error? I don't recognize it...

**Comment by wkliao** [comment]
Try replacing MPI_INT with MPI_INTEGER. MPI_INT is for C.

**Comment by edhartnett** [comment]
Good catch! I will try it.

**Comment by edhartnett** [comment]
The build works for me until this commit:

https://github.com/NCAR/ParallelIO/commit/219699459c71af50276aa3a34400addfed2a338e

This is the commit where @jedwards4b added this test code.

**Comment by edhartnett** [comment]
If I change this line:

`  use mpi, only : MPI_INTEGER, MPI_SCATTER`

To

`  use mpi
`

Perhaps this is a compiler issue. @jedwards4b what fortran compiler are you using? Is anyone else using the same as me:


```
ed@mikado:~/tmp/ParallelIO/build$ mpifort --version
GNU Fortran (Ubuntu 7.3.0-27ubuntu1~18.04) 7.3.0
```

**Comment by edhartnett** [comment]
I can't find any documentatnion of the use statement in GNU fortran, but I did find this list of compatibilities with fortran standard:
```

* USE statement with INTRINSIC and NON_INTRINSIC attribute; supported intrinsic modules: ISO_FORTRAN_ENV, ISO_C_BINDING, OMP_LIB and OMP_LIB_KINDS, and OPENACC.
* Renaming of operators in the USE statement.

```

Since support for ONLY is not explicitly mentioned, perhaps it is not supported?

**Comment by edhartnett** [comment]
In my reading of the use statement, it also seems that procedures don't get listed in the only-clause. At least, I can't find any example where anyone shows that. So perhaps the problem is that MPI_SCATTER should not be listed here.

**Comment by jedwards4b** [comment]
Hi Ed, the only clause is part of the fortran standard and procedures are listed there.  Gnu fortran has 
an issue in that the mpi.mod file has to have been built with exactly the same version of the compiler that you are using - is that what is going on here?   As a fortran developer it is my practice to always use the only clause and I'm pretty adamant about using it.   I just tried with gnu 7.10. and openmpi 3.1.0 and successfully built all tests.

**Comment by edhartnett** [comment]
OK, I'm rebuilding mpich, which was built with a previous version of gfortran. I'll let you know how it works...

**Comment by edhartnett** [comment]
Rebuilding mpich did not solve the problem.

@jedwards4b I note this is the only place in the code where the only clause is used with mpi, and also seems to be the only only-clause used which lists a procedure not a type. Are you sure that procedures are supposed to be listed here?

Have you tried MPICH?

**Comment by jedwards4b** [comment]
okay fine, take out the only clause. Let's get a release out there.
