### ISSUE TITLE
Internal data conversion needs to work 

### ISSUE THREAD

**Issue by jedwards4b** [NCAR/ParallelIO#1334]
Currently the check https://github.com/NCAR/ParallelIO/blob/master/src/clib/pio_darray.c#L650
is preventing pio from converting datatypes internally - this is an important feature for many users of pio - (converting double to single precision before a write or single to double after a read).  Reimplement support for this important feature.

**Comment by edhartnett** [comment]
How has this worked in the past? Or did you mean in pio1?

**Comment by jedwards4b** [comment]
I mean pio2, it used to work in pio2 and it currently works in pio1.

**Comment by edhartnett** [comment]
What happens if you just take the check out. Does any test fail?

**Comment by jedwards4b** [comment]
I haven't checked tests - but the case I am working with fails with error NC_ERANGE when I use pnetcdf but not when I use netcdf.  I am checking the latest pnetcdf version now.
