### ISSUE TITLE
test_darray_multivar3

### ISSUE THREAD

**Issue by jedwards4b** [NCAR/ParallelIO#1336]
I'm confused as to why this test would work.  var0 has no record dimension while var1 and var2 do have but the call to ncmpi_iput_varn expects all of the vars to have the same dimensionality.   It seems to me that calling PIOc_write_darray_multi should require that all variables have the same dimensionality.

**Comment by edhartnett** [comment]
I will take a look...

**Comment by jedwards4b** [comment]
this issue was addressed by PR #1335
