### ISSUE TITLE
Very slow IO time when writing sub-hourly data

### ISSUE THREAD

**Issue by johnmauff** [NCAR/ParallelIO#1339]
When sub-hourly data is turned on in CESM2, the write call gets progressively slower. There is what looks like a linear cost term that is based on the number of calls to PIO_write_darray. I believe it is due to the use of a single linked list in the subroutine "add_data_to_buffer" in the piodarray.F90.in file. Because each write is so small when generating sub-hourly data, the linked list file%data_list_top gets to be very long before the buffer data is actually written to disk. A reduction in the pio_buffer_size_limit appears to significantly increase IO performance because it reduces the maximum length of the linked list. Replacing a single linked list with a double linked list should resolve this issue while still maximizing the size of IO to disk.

**Comment by jedwards4b** [comment]
John,
If I understand you correctly we don't really need a doubly linked list - we just need another variable in the File structure that always points to the end of the list so that you don't have to traverse the entire list whenever you want to append.

**Comment by johnmauff** [comment]
Jim,

  Yes that is potentially another solution that would likely be simpler.

**Comment by jedwards4b** [comment]
I've pushed a branch to my fork at https://github.com/jedwards4b/ParallelIO/
branch name pio1_linkedlist_opt 
please give it a shot.

**Comment by johnmauff** [comment]
Thanks for the new code.    That reduced I/O time for this particular configuration by 40x.

**Comment by rljacob** [comment]
Which system was this observed on?

**Comment by jedwards4b** [comment]
@rljacob cheyenne/intel  but it's a pretty system independent optimization.
