### ISSUE TITLE
Next pio tag?

### ISSUE THREAD

**Issue by jedwards4b** [NCAR/ParallelIO#1359]
@edhartnett When you are happy with the state of things I think we should make a new tag.

**Comment by edhartnett** [comment]
Ok let's shoot for tomorrow afternoon.

**Comment by edwardhartnett** [comment]
@jedwards4b I have filled out draft release notes on the releases page. Can you edit and add a description of the changes you've made since the last release?

**Comment by jedwards4b** [comment]
done

**Comment by jedwards4b** [comment]
@edhartnett - are we ready to release?

**Comment by edhartnett** [comment]
No, sorry. I am trying to build with the latest release of netcdf and hdf5,
and seeing an error. Let me see what can be done. Can we wait until Monday?

**Comment by jedwards4b** [comment]
Yes, no worries - have a nice weekend.

**Comment by edwardhartnett** [comment]
OK, I did the release. Take a look and let me know if you find anything wrong.
