### ISSUE TITLE
Incorrect declaration of ival in get_vara_text_internal

### ISSUE THREAD

**Issue by mgduda** [NCAR/ParallelIO#1360]
In the `get_vara_text_internal` routine, I think the [declaration of ival at L.453](https://github.com/NCAR/ParallelIO/blob/pio2_4_0/src/flib/pionfget_mod.F90.in#L453) should be:
```
character(len=*), intent(out) :: ival(*)
```
I.e., the declaration is missing `(len=*)`.

**Comment by jayeshkrishna** [comment]
Yes, @dqwu  found this issue when testing on our fork.

**Comment by jedwards4b** [comment]
thanks

**Comment by jedwards4b** [comment]
Fixed in pio2.4.1
