### ISSUE TITLE
Should bget be removed from the code? (was: Possible memory-related bug)

### ISSUE THREAD

**Issue by davidedelvento** [NCAR/ParallelIO#1371]
Michael Duda reported what follows:

> What I've found is that if I compile PIO
> with a different option (`-DPIO_USE_MALLOC=ON`) the crashes disappear.
> Unfortunately, I have no idea why using PIO's memory manager as opposed to
> malloc never caused problems in the past, but sometimes even small changes
> in computing environments can trigger memory-related bugs.

My understanding is that this is for the latest version of PIO and when used in MPAS. I'm providing this as FYI, in case you want to investigate.

**Comment by edhartnett** [comment]
Thanks, I am investigating this...

**Comment by jedwards4b** [comment]
My latest testing seems to indicate that PIO_USE_MALLOC is significantly faster at least on cheyenne with intel.  I plan to change this to be the default.

**Comment by davidedelvento** [comment]
Sounds great, thanks for letting us know!

**Comment by edwardhartnett** [comment]
@jedwards4b shall I remove bget from the code?

It has never worked in the autotools build, and apparently there are crashes when it is used on the cmake build, and the cmake build has been using the malloc for default for some time now.

So I think we can retire bget.
