### ISSUE TITLE
improve testing on HPC systems by allowing --disable-tests, and supporting slurm

### ISSUE THREAD

**Issue by edhartnett** [NCAR/ParallelIO#1396]
Our tests don't run well on real HPC systems as they depend on launching with mpiexec.

So building them on a HPC doesn't work because the first run_tests.sh we hit fails, and the build of tests stops. So users cannot even run the tests their own way. ;-(

So we need a --disable-tests, which will allow the user to build tests but not run the run_tests.sh scripts that run them on our CI systems. 

We could also add a slurm script that could be used for those HPC systems that support it.

**Comment by jedwards4b** [comment]
I know this won't get far, but this works with cmake.

**Comment by jedwards4b** [comment]
The other approach that most hpc systems support is to open an interactive session and build there.

**Comment by edhartnett** [comment]
There is now an option called --disable-test-runs. If used, make check will build tests but not attempt to run them with mpiexec.
