### ISSUE TITLE
PIO_USE_MALLOC component interaction error

### ISSUE THREAD

**Issue by jedwards4b** [NCAR/ParallelIO#1398]
We have discovered an issue in running cesm development tests using pio2 with PIO_USE_MALLOC=ON.    This is an intermittent problem and doesn't occur every time but in the test SMS_Vnuopc_Ln5.f19_f19_mg17.I2000Clm50SpGs.cheyenne_intel.clm-nuopc_cap it seems to occur most of the time.   History files written by this test may contain invalid and nonsensical data.  The problem only seems to affect the content of output files and not the model evolution.   We have thus far only found the problem to occur in interactions with the ctsm (clm) component model, but if the ctsm component is used the problem may occur in history files not directly related to that model - mosart and cpl history files have both also been observed to be corrupted in this test.   Turning off PIO_USE_MALLOC appears to solve the problem. 

I also tried this test using the E3SM-Project:master with the same result when PIO_USE_MALLOC=ON, but when I tried this branch with PIO_USE_MALLOC=OFF I got a hang writing the first output file and was unable to complete the test.

**Comment by rljacob** [comment]
PInging @dqwu  and @jayeshkrishna .

**Comment by jedwards4b** [comment]
Relevant software: intel/17.0.1, mpt/2.19, pnetcdf1.11.0 
rebuilding with intel/19.0.2 appears to solve the problem.  

I'm going to explore the optimization space in 17.0.1 to see if I can pinpoint a compiler issue.

**Comment by edwardhartnett** [comment]
Is this still an active issue?

One suggestion would be to run the tests with valgrind on that platform, if valgrind is available.

**Comment by edwardhartnett** [comment]
Is this still happening?

**Comment by jedwards4b** [comment]
No, I think this was fixed.
