### ISSUE TITLE
time for a new tag?

### ISSUE THREAD

**Issue by jedwards4b** [NCAR/ParallelIO#1399]
I would like a new tag whenever you are ready @edhartnett

**Comment by edhartnett** [comment]
OK, there are draft release notes for the next release. Why don't you update them with whatever changes you made since last release...

**Comment by jedwards4b** [comment]
Done - thanks!

**Comment by edhartnett** [comment]
OK, I'll release tomorrow morning when I'm fresh. ;-) Less chance of a mistake...

**Comment by edhartnett** [comment]
OK, I did the release Friday. I will announce it in various places today. I will close this ticket.

**Comment by jedwards4b** [comment]
Thanks!
