### ISSUE TITLE
support for binary files in PIO 

### ISSUE THREAD

**Issue by jedwards4b** [NCAR/ParallelIO#140]
From ESMF developers:
We recently had a situation where a ESMF user community keeps their binary data files in big-endian format.  To read/write the files on little-endian machines, they use Fortran compilers (e.g., gfortran and Intel) which can non-Standardly specify endian in the OPEN statement.  In the case of ESMF, we would like to use PIO - which of course doesn't use vanilla Fortran I/O.

NetCDF keeps the endian-ness of its files, so I think it can perform the necessary conversions.  It also has an API to specify non-default endian.  However in this particular case we needed binary file reads.  So it would require byte-/half-word swapping in the PIO layer depending on data type.

As you know, we are using the older Fortran version of PIO which does not do anything about endian specification and conversion.  We were wondering if the newer C version does?

Interestingly I see you have a PIOc_def_var_endian function now – though the PIO Users Guide seems to think this call is for chunksizes, not endian setting.  Nonetheless, if it does call nc_def_var_endian under the surface, then it would do what we would need for NetCDF files.  But binary would remain an issue.

**Comment by edhartnett** [comment]
Not sure that the pio2 c library has any support for non netcdf files.

**Comment by edhartnett** [comment]
I'm going to close this. I believe we have all agreed that there is no good place to support proprietary formats in PIO. It is possible to add such support in netCDF, and then PIO can take advantage of it too.
