### ISSUE TITLE
why is netcdf-4 sequential with compression so dang slow?

### ISSUE THREAD

**Issue by edhartnett** [NCAR/ParallelIO#1409]
I'm running tests at different numbers of processors etc., but one consistent result is the slowness of netcdf-4 sequential, with compression. For example (results from jet):

```
ntasks  nio     rearr   fill    format  time(s) data size (MB)  performance(MB/s)
2048    16      1       0       0          1.834         10240.0        5582.423
2048    16      1       0       1          7.301         10240.0        1402.489
2048    16      1       0       2         46.902         10240.0         218.328
2048    16      1       0       3          4.037         10240.0        2536.244
2048    16      1       1       0          1.880         10240.0        5446.304
2048    16      1       1       1          6.546         10240.0        1564.208
2048    16      1       1       2         47.041         10240.0         217.684
2048    16      1       1       3          4.059         10240.0        2522.646

```

NetCDF-4 sequential with compression is format (i.e. IOTYPE) 2. It's an order of magnitude slower.

Why? Compression should not cost this much performance. A good thing to turn off compression and see what the straight-up netcdf-4 serial performance is. It should be pretty similar to the netcdf classic performance.

**Comment by edhartnett** [comment]
This may be a netcdf-c problem. See https://github.com/Unidata/netcdf-c/issues/1436

**Comment by edwardhartnett** [comment]
The answer was bad chunksizes. Setting better chunksizes considerably improved performance.
