### ISSUE TITLE
pio_decomp_tests_2d_4p_2iop_2str failure on cdash

### ISSUE THREAD

**Issue by edhartnett** [NCAR/ParallelIO#141]
Cdash output here:

http://my.cdash.org/viewTest.php?onlyfailed&buildid=1069647

**Comment by jayeshkrishna** [comment]
I don't have access to hobart, so someone else will have to take a look at this. I will try recreating this on the ANL machines and see if I get these failures.

**Comment by Katetc** [comment]
As of Oct 24, every test is running on Hobart. Must have been a machine glitch.
