### ISSUE TITLE
pio_decomp_fillval failures on CDash

### ISSUE THREAD

**Issue by edhartnett** [NCAR/ParallelIO#142]
There are three builds that are failing this test:

http://my.cdash.org/index.php?project=PIO&date=2016-10-21

**Comment by jayeshkrishna** [comment]
I don't have access to caldera, so someone else will have to take a look at this failure. I will try to recreate the issue on the ANL machines.

**Comment by edhartnett** [comment]
These are still failing...

**Comment by edhartnett** [comment]
There now seems to be some more failing tests:

*Tests failing* (first 5)
pio_decomp_tests_3d_4p_1agg (http://my.cdash.org/testDetails.php?test=28218309&build=1076221)
pio_decomp_frame_tests (http://my.cdash.org/testDetails.php?test=28218319&build=1076221)
pio_decomp_tests_3d_4p_3agg (http://my.cdash.org/testDetails.php?test=28247587&build=1076221)
pio_decomp_tests_1d_1p (http://my.cdash.org/testDetails.php?test=28278615&build=1076221)
pio_decomp_tests_1d_2p (http://my.cdash.org/testDetails.php?test=28278616&build=1076221)

**Comment by edhartnett** [comment]
There has been vast improvement in this issue. Now, almost all cdash tests pass almost all the time. So thanks for that, because it is really helpful.

But on hobart we still see some failures which are unexplained. Sometimes the message that the test has succeeded is printed, and yet the test reports failure.

Any thoughts on what might be going on with hobart?

**Comment by jedwards4b** [comment]
Hobart is failing on MPI finalize after all tests have passed.  I'm not sure this problem is within our control.

**Comment by edhartnett** [comment]
Well that's pretty lame. Why does it do that? 

Where is hobart? Is that an NCAR machine?

**Comment by jedwards4b** [comment]
Yes, it's a ncar/cgd machine.

**Comment by edhartnett** [comment]
I am going to close this old issue.
