### ISSUE TITLE
are we adding ADIOS to PIO?

### ISSUE THREAD

**Issue by edhartnett** [NCAR/ParallelIO#1421]
In Jayesh's large PR #1410 we have a new iotype for ADIOS.

Is this going to be added to PIO?

If not, should we provide some plug-in mechanism so that @jayeshkrishna can choose to use the PIO library, and still support ADIOS?

**Comment by jedwards4b** [comment]
Note that the PR only adds a write capability for ADIOS.  I am interested in the proposal of a plug-in mechanizm for this.

**Comment by edhartnett** [comment]
I know someone has mentioned it, but what is ADIOS?

**Comment by jedwards4b** [comment]
https://www.olcf.ornl.gov/center-projects/adios/

**Comment by edhartnett** [comment]
OK, so I am seeing some system whereby external XML files are used to control how C/Fortran programs work with data.

This looks specific to Oak Ridge so I wish them luck with it, but it does not look like something that should be in PIO, unless a lot more NOAA and NCAR scientists start using ADIOS.

Let us absorb all the changes we can from the PR and then circle back to the idea of a plugin architecture to support ADIOS, if that is something @jayeshkrishna is interested in.

**Comment by edhartnett** [comment]
OK, I'm going to close this ticket, since the answer is apparently that we are not adding ADIOS as a new iotype.

I spoke too soon on the plug-in architecture. I'm not sure it's going to be easy, and since adding pluging support will not return our wayward programmers to the fold in any case, it doesn't seem worth the effort.

Access to new "iotypes" is available via the use of PIOc_create()/PIOc_open() which use mode flags instead of iotype. In this way the user can get, for example, a netCDF-4 sequential IOTYPE without compression.

I am not keen on the concept of keeping metadata in a file outside the data file in any case. It seems that such metadata should be either associated with the data as netCDF attributes, or associated with the software that is using the data.
