### ISSUE TITLE
Let us finally remove the varm functions, they are deprecated in netCDF, and no one uses them

### ISSUE THREAD

**Issue by edhartnett** [NCAR/ParallelIO#1422]
Let us just remove the varm functions.

No one uses them (or even understands them) in netCDF, and they are deprecated in the netCDF API.

Frankly, the idea of trying to support this code makes me want to take up work as a longshoreman.

So let's just remove these from the API before we unleash PIO on NOAA.

**Comment by edhartnett** [comment]
@jedwards4b any objections, or have I finally worn you down on this one?

**Comment by jedwards4b** [comment]
No objections.

**Comment by edhartnett** [comment]
![image](https://user-images.githubusercontent.com/4533212/57935579-5bedc680-787f-11e9-9a38-dd75ad0a755f.png)

**Comment by edhartnett** [comment]
OK, looks like I already did this anyway. They're gone!
