### ISSUE TITLE
test 30 timeout on master

### ISSUE THREAD

**Issue by jedwards4b** [NCAR/ParallelIO#1423]
```
   Start 30: test_darray_async_many

30: Test command: /glade/u/home/jedwards/sandboxes/ParallelIO/cmake/mpiexec.nwscla "5" "/glade/u/home/jedwards/sandboxes/ParallelIO/bld/tests/cunit/test_darray_async_many"
30: Test timeout computed to be: 240
30: 1 Error 1112 in /glade/u/home/jedwards/sandboxes/ParallelIO/tests/cunit/test_darray_async_many.c, line 227
30: 2 Error 1112 in /glade/u/home/jedwards/sandboxes/ParallelIO/tests/cunit/test_darray_async_many.c, line 227
30: 3 Error 1112 in /glade/u/home/jedwards/sandboxes/ParallelIO/tests/cunit/test_darray_async_many.c, line 227
^Cqsub: wait for job 5849242.chadmin1 interrupted by signal 2
```
Line 227 is only netcdf4 and is a reference to type PIO_INT64

**Comment by edhartnett** [comment]
Where is this happening?

**Comment by jedwards4b** [comment]
Cheyenne
Currently Loaded Modules:
  1) ncarenv/1.2    3) intel/19.0.2          5) mpt/2.19           7) pnetcdf/1.11.0
  2) python/3.6.8   4) ncarcompilers/0.4.1   6) netcdf-mpi/4.6.1

**Comment by cponder** [comment]
I see this happening with the new 2_4_3 release and these components:
```
  1) cmake/3.11.1                    5) zlib/1.2.11     9) hdf5/1.10.5
  2) PrgEnv/PGI+OpenMPI/2019-05-23   6) hwloc/1.11.12  10) pnetcdf/1.11.2
  3) cuda/10.1.168.0                 7) openmpi/3.1.4  11) netcdf-c/4.7.0
  4) pgi/19.5                        8) szip/2.1.1     12) netcdf-f/4.4.5
```
I'm running on Ubuntu 16.03.
The problem first showed up for me with 2_4_1.

**Comment by edhartnett** [comment]
I recently turned on some comment-ed out test code. It ran on my machine, it worked on travis, so I figured it was fine, and merged to master.

Well, looks like I was wrong. I will look at this again when I finish with my current MPE work. But this test failure does not represent any change in the library code, this is some old test code that had been turned off, without comment.

**Comment by jedwards4b** [comment]
I am seeing this problem intermittently in the cdash test with error:
MPT ERROR: Not enough slots from job scheduler for requested ranks
	(HPE MPT 2.19  12/07/18 05:32:16)

**Comment by wkliao** [comment]
I did not test this but have seen that OpenMPI error message before.
The problem can be resolved by adding command-line option `--oversubscribe`.
For example,
`~/OpenMPI/4.0.1/bin/mpirun --oversubscribe -n 16 ./hello_world`
