### ISSUE TITLE
change to gh-pages branch for documentation

### ISSUE THREAD

**Issue by edhartnett** [NCAR/ParallelIO#1431]
There are two ways that github can serve our documentation:

1 - We have a "docs" directory with the built documentation on the master branch.
2 - We have a branch called "gh-pages" which contains nothing but the built documentation.

Right now we are using 1. But it results in some inconvenience when working on docs. Specifically, it keeps checking in changes to the built docs when I am working on the docs, which I don't want, since they must stay equal to what they were when the current version was released. Also, it's confusing, because we have our documentation source in directory "doc" and built documentation in directory "docs".

So I am going to switch us to method 2. As I understand this, I just create a branch called gh-pages, delete everything on that branch, add the built docs to the branch, and then I can remove the awkward "docs" directory from master.

**Comment by jedwards4b** [comment]
Method 2 is used in a number of other repos that I am working with.
