### ISSUE TITLE
pio_types.F90 is written to handle pnetcdf-only builds, but the C library doesn't support that anyway

### ISSUE THREAD

**Issue by edhartnett** [NCAR/ParallelIO#1436]
The PIO C library requires netcdf to build.

But the pio_types.F90 code is written to accommodate pnetcdf-only builds; this can be simplified.

Also it see that it does not really use CDF5 format when using the classic library, but that is quite possible now.

**Comment by jedwards4b** [comment]
yes, let's make cdf5 the default for classic and pnetcdf.   Thanks

**Comment by edhartnett** [comment]
This was fixed recently and was in the last release. The changing of CDF5 to default is a separate issue (#1437).
