### ISSUE TITLE
Question about comments like !eop in the fortran code

### ISSUE THREAD

**Issue by edhartnett** [NCAR/ParallelIO#1453]
As I work on the fortran documentation, I see comments like this in the code:
```
  !eop
  !boc

```

What's up with these? Is this another language within a language for some additional fortran pre-processing somewhere?

Or are these historical gunk that should be removed from our beautiful code?

**Comment by jedwards4b** [comment]
historical gunk

**Comment by edhartnett** [comment]
Roger that.
