### ISSUE TITLE
Update published user doc to latest

### ISSUE THREAD

**Issue by jedwards4b** [NCAR/ParallelIO#147]
The published doxygen docs for pio2 should be updated to the latest available.

**Comment by Katetc** [comment]
Done for now. Looks like there will be more changes and some rearranging from discussion on pr#146 .

**Comment by edhartnett** [comment]
There was talk of us having a PIO website (other than github) which could host documentation. Is that going to happen?

If so, I suggest we start dating our documentation, and putting it on the website.

Is there a way to make the published docs on github automatically reflect the state of the repository?

**Comment by edhartnett** [comment]
I think we can close this issue for now. The docs were updated.
