### ISSUE TITLE
strnlen implicit in intel19

### ISSUE THREAD

**Issue by jedwards4b** [NCAR/ParallelIO#1471]
When compiling with intel/19.0.2 I get a warning:
```
/glade/u/home/jedwards/sandboxes/ParallelIO/tests/cunit/test_iosystem3.c(59): warning #266: function "strnlen" declared implicitly
      if ((ret = PIOc_put_att_text(ncid, varid, attname, strnlen(filename, PIO_TF_MAX_STR_LEN),
```
I found this reference to the problem: https://software.intel.com/en-us/forums/intel-c-compiler/topic/308745
and confirmed that adding 
#define _GNU_SOURCE 
to config.h solves the problem.   But I'm not sure if that's the best solution or of the best way to add this to config.h

**Comment by edhartnett** [comment]
In configure.ac do this:
```
# Define to solve intel compiler warning.
AC_DEFINE([_GNU_SOURCE], [1], [solve strnlen declared implicitly warning on intel compiler])

```

also in CMakeLists do:

`set(_GNU_SOURCE, 1)`
