### ISSUE TITLE
stop using the GPTL timing library?

### ISSUE THREAD

**Issue by edhartnett** [NCAR/ParallelIO#1480]
I got involved in the GPTL project to add a modern build system, get it all tested and stable, and operationally read. Unfortunately, I am about to abandon that goal, as I cannot convince the GPTL programmer to use CI or other modern methods which would allow me to use the library with confidence and recommend it to NOAA as operationally ready (which, at the moment, it certainly is not.)

Basically there is no easy, versioned releases of GPTL which work well. The developer is now working on branches that don't get merged to master, and there is no CI. Users are directed to clone the repo and build a branch to get a working copy of GPTL. This is obviously not sufficient.

Meanwhile, our former collaborators apparently abandoned GPTL and introduced their own timer using MPI. Any reason this is not just as good at GPTL? But without all the baggage that comes with GPTL?

@jedwards4b do you have any special reasons to prefer GPTL?

Have you considered the MPE library for timing? It's very well-tested, as a great heritage, yields very nice plots, and does not have to be in any way maintained by us...

**Comment by jedwards4b** [comment]
The GPTL library is also used by cesm.  If you would like to implement a different timing library can we do it in a way that keeps a compatible API?   I added ESMF timers to cesm by just changing the calls in perf_mod.F90 - can we do something similar for MPE?  Our e3sm collaborators have not responded to any questions we had about timing, I don't think we should consider that code.

**Comment by edhartnett** [comment]
There are actually only 19 calls to the timing library in our code, so not many at all.

In terms of the API, it kind of sucks. Instead of giving errors with return code, we get error messages printed to console. Very basic!

Is the concern that we must provide GPTL timing for CESM? Or that CESM already uses GPTL so you want to keep the code similar?

**Comment by jayeshkrishna** [comment]
The timing interfaces that we added in our fork are just higher level interfaces to use GPTL or MPI timers under the hood (to make measuring certain events easier). We are not planning to abandon GPTL.

**Comment by edhartnett** [comment]
@jedwards4b I have been looking at the MPE library.

When you say that you are willing for GPTL to be removed from PIO, how do you see that working?

Firstly, PIO will not report any PIO times to the CESM GPTL. Is that OK?

Secondly, we would have to make changes to pioperformance.F90 to remove GPTL.

**Comment by edhartnett** [comment]
I am going to shelve this issue. Moving forward I am going to do some timing tests with MPE. But I will leave GPTL alone...
