### ISSUE TITLE
fortran initdecomp documentation is incomplete

### ISSUE THREAD

**Issue by jedwards4b** [NCAR/ParallelIO#1492]
The documentation at https://ncar.github.io/ParallelIO/group___p_i_o__initdecomp.html
only shows 2 of the 11 fortran interfaces to pio_initdecomp()

**Comment by edhartnett** [comment]
Stand by, I will fix.

We will need to do a new release before we update the docs on the web. I have added some functions and they will appear in the docs, so they better be in the library. ;-) (The *_vard_* functions).
