### ISSUE TITLE
use of DOTHIS macro causing most code in init_intercomm() to be ignored?

### ISSUE THREAD

**Issue by edhartnett** [NCAR/ParallelIO#1534]
In piolib_mod.F90 I see this:

```
  subroutine init_intercom(component_count, peer_comm, comp_comms, io_comm, iosystem)
    use pio_types, only : pio_internal_error, pio_rearr_box
    integer, intent(in) :: component_count
    integer, intent(in) :: peer_comm
    integer, intent(in) :: comp_comms(component_count)   !  The compute communicator
    integer, intent(in) :: io_comm     !  The io communicator

    type (iosystem_desc_t), intent(out)  :: iosystem(component_count)  ! io descriptor to initalize
#ifdef DOTHIS
    integer :: ierr

```

And it goes on. The ifdef DOTHIS covers the entire function.

I cannot find anywhere where DOTHIS is set. So what's going on here? @jedwards4b do you have any clue?

**Comment by jedwards4b** [comment]
The intercomm interface to fortran is commented out - I think that I never resolved the changes to the c library api.

**Comment by edhartnett** [comment]
OK, I will add a ticket to fully test the async features from Fortran. Whatever parts of the Fortran API are missing, I will fill in.

I have commented out this code for now to fix warnings. I will close this ticket.
