### ISSUE TITLE
improper use of pre-processor macros in pio.h

### ISSUE THREAD

**Issue by edwardhartnett** [NCAR/ParallelIO#1576]
In pio.h we have:

```
#ifdef _NETCDF
#include <netcdf.h>
#ifdef _NETCDF4
#include <netcdf_par.h>
#endif
#endif
#ifdef _PNETCDF
#include <pnetcdf.h>
#endif

```
and later:

`#if defined( _PNETCDF) || defined(_NETCDF)
`

Well this will not work! The user will have to defind _NETCDF and/or _PNETCDF to get PIO to work. That should not be required.

In fact, _NETCDF can always be assumed. PIO will not build without netcdf.

For the pnetcdf header, I'm not sure what we should do.

**Comment by jedwards4b** [comment]
Somehow we need to know what libraries pio was built with, we've already figured it out in the configure or cmake step - can we use that info here?

**Comment by edwardhartnett** [comment]
I believe we can just remove the pnetcdf include, and the netcdf library is always present...

**Comment by jedwards4b** [comment]
what about https://github.com/NCAR/ParallelIO/blob/master/src/clib/pio.h#L769

**Comment by edwardhartnett** [comment]
That line can be safely removed.
