### ISSUE TITLE
Time for a new tag?

### ISSUE THREAD

**Issue by jedwards4b** [NCAR/ParallelIO#1585]
There have been a few bug fixes - in particular a user wants #1584

**Comment by edhartnett** [comment]
Sure. Can you edit the release notes and add a description of the bugs?

**Comment by edhartnett** [comment]
OK, I've done a new release and updated the docs.

Give it a try. I will announce it on the mailing list after a few people have tried it, so let me know how it works for you.

**Comment by jedwards4b** [comment]
I'm seeing a problem when trying to configure with cmake:
CMake Error: File /glade/u/home/jedwards/src/pio-2.4.4/cmake_config.h.in does not exist.
CMake Error at CMakeLists.txt:155 (configure_file):
  configure_file Problem configuring file

**Comment by edhartnett** [comment]
OK, the problem here is that you are downloading the autotools build, and then using cmake.

For the cmake builds, try: https://github.com/NCAR/ParallelIO/archive/pio2_4_4.tar.gz

However, I will also fix the autotools build and move the tag so that the 2.4.4 release works for both cmake and autotools. Stand by...

**Comment by edhartnett** [comment]
OK, fixed that, commited changes, and moved the tag. So now the 2.4.4 tarball allows either autotools or cmake builds.

Give it another try and let me know if it works for you.

**Comment by jedwards4b** [comment]
okay - the cmake build is working now, thanks!  I think I found a problem in the autoconf build, it appears that flag --enable-timing doesn't work, at least I couldn't figure out the method.

**Comment by edhartnett** [comment]
Well there always has to be something for the next release! ;-)

The CESM people use the timer but build with cmake, right?

And I think anyone that builds with autotools does not use the GPTL. So I think this can be fixed in the next release...

**Comment by jedwards4b** [comment]
Sure - do we have a place for listing known issues?

**Comment by edhartnett** [comment]
We did a release and are working on the next one, so I will close this.
