### ISSUE TITLE
warning in pio_darray.c

### ISSUE THREAD

**Issue by edhartnett** [NCAR/ParallelIO#1596]
Here's a new warning:

```
pio_darray.c:268:102: warning: suggest parentheses around ‘&&’ within ‘||’ [-Wparentheses]
     if (iodesc->llen > 0 || (file->iotype==PIO_IOTYPE_NETCDF || file->iotype == PIO_IOTYPE_NETCDF4C) && ios->iomaster)
                             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~

```

I will fix and put up a PR.

**Comment by jedwards4b** [comment]
It should be 
if ((iodesc->llen > 0 || (file->iotype==PIO_IOTYPE_NETCDF || file->iotype == PIO_IOTYPE_NETCDF4C)) && ios->iomaster)

**Comment by jedwards4b** [comment]
Sorry that's wrong, it's the other way:
if (iodesc->llen > 0 || ((file->iotype==PIO_IOTYPE_NETCDF || file->iotype == PIO_IOTYPE_NETCDF4C) && ios->iomaster))

**Comment by edhartnett** [comment]
Yes, I agree with the second one. ;-)

PR is up now, take a look.
