### ISSUE TITLE
NetCDF_C_LOGGING_ENABLED defined when it isn't 

### ISSUE THREAD

**Issue by jedwards4b** [NCAR/ParallelIO#1604]
According to nc-config:
 --has-logging   -> no
but when I compile with DEBUG == True the cmake seems to think it is because
NetCDF_C_LOGGING_ENABLED is True.  
This is with netcdf 4.6.3

**Comment by jedwards4b** [comment]
I should mention that in my build DEBUG=True triggers PIO_ENABLE_LOGGING

**Comment by edhartnett** [comment]
Cmake or autotools build?

**Comment by jedwards4b** [comment]
cmake

**Comment by edwardhartnett** [comment]
OK, let me know if you want help. BTW netcdf-c is up to 4.7.1, so you should upgrade.

**Comment by edhartnett** [comment]
Any clarity on whether this is a PIO issue or not?

**Comment by jedwards4b** [comment]
I think that it was a system issue - closing.
