### ISSUE TITLE
Unreasonable size of bss section

### ISSUE THREAD

**Issue by aprokop** [NCAR/ParallelIO#1621]
While compiling a code (MPAS-O) depending on ParallelIO (1.9.23), I'm getting errors during the final linking stage
```
mpas_ocn_particle_list.F:(.text+0x3418): relocation truncated to fit:
R_X86_64_PC32 against symbol `mpi_fortran_statuses_ignore_' defined in
COMMON section in driver/mpas.o
```
After some investigation (going through all object files and libraries linked in and dumping the results of `size`), I found out that `libpio.a` was the culprit. Specifically, certain object files built when building PIO
have surprising sizes (as output by the `size` command):
```
   text data          bss           dec         hex   filename
  10964    0  17179869180   17179880144   400002ad0   pio_msg_callbacks.F90.o (ex libpio.a)
  17784    0  51539607548   51539625332   c00004574   pionfread_mod.F90.o (ex libpio.a)
  21760    0  51539607548   51539629308   c000054fc   pionfwrite_mod.F90.o (ex libpio.a)
 156172    0  17179869176   17180025348   400026204   pionfget_mod.F90.o (ex libpio.a)
  83371    4 103079215128  103079298503  18000145c7   piodarray.F90.o (ex libpio.a)
```
This seems to depend on platform, though. This is on my workstation with gcc/7.4.0. On NERSC/Cori, they seem to contain reasonable values.

I'm very confused and am looking for any help.

**Comment by edwardhartnett** [comment]
Can you get any further visibility into where that static storage is going?

Are you working with a very large decomposition? What darray function are you calling? Read or write?

**Comment by jedwards4b** [comment]
Some older versions of PIO are incompatible with some newer versions of netcdf because netcdf used to have variables like NF_MAX_VAR_DIMS that were used internally and externally to define max sizes for some arrays.   When netcdf stopped using these internal they left them in place but redefined them to be MAX_INT or some other really large value.   This causes the really large sizes you see.   You might try updating pio to pio1.10.1 or to the latest pio2.5.0

**Comment by aprokop** [comment]
> Can you get any further visibility into where that static storage is going?

I'd love to, but so far I am not sure how to do that.

> Are you working with a very large decomposition? What darray function are you calling? Read or write?

I don't think I understand the question. I would expect this has to do nothing with calling anything, just about linking statically allocated things.

> Also what version of PIO?

1.9.23

> Some older versions of PIO are incompatible with some newer versions of netcdf because netcdf used to have variables like NF_MAX_VAR_DIMS that were used internally and externally to define max sizes for some arrays. When netcdf stopped using these internal they left them in place but redefined them to be MAX_INT or some other really large value. This causes the really large sizes you see.

@jedwards4b Interesting, thank you for the insight. I looked through the PIO file, and saw some of the arrays using those variables. Did not realize they were coming from netcdf. That would explain the issue. I'll try updating to pio 1.10.1 and post the results (unfortunately, the code I'm using has issues using pio2).

**Comment by aprokop** [comment]
I tried 1.10.1, and indeed, the sizes are now reasonable.

**Comment by edwardhartnett** [comment]
Glad the problem was resolved! I will close this issue.
