### ISSUE TITLE
Incorrect documentation?

### ISSUE THREAD

**Issue by gold2718** [NCAR/ParallelIO#1623]
In pionfget_mod.F90.in, there is documentation of the form:
```
!! @ingroup PIO_get_var
!! @brief Writes an netcdf attribute to a file
```
which I think are incorrect. This happens 5 times in that file.

**Comment by edwardhartnett** [comment]
Thanks, I will fix this after AGU.

**Comment by edwardhartnett** [comment]
This has been fixed.
