### ISSUE TITLE
A problem about  the application of ParallelIo

### ISSUE THREAD

**Issue by yuyangyang0709** [NCAR/ParallelIO#1624]
I need ParallelIo to compile MPAS model, but I'm not familiar with ParallelIo. In the makefile of MPAS, it uses a test program to test ParallelIO. The program are as follow:

program pio2; 
use pio; 
integer, parameter :: MPAS_IO_OFFSET_KIND = PIO_OFFSET_KIND; 
integer, parameter :: MPAS_INT_FILLVAL = PIO_FILL_INT; 
end program

Then, I tried compiling this program use the command:
mpif90 pio2.f90 -I/home/lulv/yuyy/software/pio/usr/local/include -L/home/lulv/yuyy/software/pio/usr/local/lib -o pio2.out

Compilation of MPAs failed. The error messages are:
_IO_OFFSET_KIND = PIO_OFFSET_KIND; integer, parameter :: MPAS_INT_FILLVAL = PIO
                                                                           1
Error: Parameter 'pio_fil' at (1) has not been declared or is a variable, which does not reduce to a constant expression
Error: Unexpected end of file in 'pio2.f90'

Is there a problem with the test program in MPAS model? How to judge whether PIO is installed correctly? I would appreciate it if you could reply me. Thank you.

**Comment by jedwards4b** [comment]
It looks to me like there is something wrong with the format and parsing of your test program.
In your error message you have _IO_OFFSET_KIND when I would expect MPAS_IO_OFFSET_KIND and pio_fil when I would expect to see PIO_FILL_INT.
