### ISSUE TITLE
host memory balloons to large values when pio-2.4.4 is compiled using the Portland Group C compiler, pgcc

### ISSUE THREAD

**Issue by walkup** [NCAR/ParallelIO#1625]
When the MPAS atmosphere model is linked with a PIO library built with pgcc as the C compiler, the host memory utilization balloons out, and can result in out-of-memory errors. In contrast, if the identical MPAS object files and libraries are linked with a PIO library built with the GNU C compiler, the host memory utilization looks reasonable. Here is an example :

link to a pgcc build of pio-2.4.4 (options -g -O2 -c11)
memory_usage_max: 176098770944
memory_usage_max: 137790029824
memory_usage_max: 138783948800
memory_usage_max: 80325443584
memory_usage_max: 63485181952
memory_usage_max: 64096894976
memory_usage_max: 130629107712
memory_usage_max: 155443396608
memory_usage_max: 117871214592
memory_usage_max: 87660167168

link to a gcc build of pio-2.4.4 (options -g -O2 -std=c11)
memory_usage_max: 33266008064
memory_usage_max: 33366278144
memory_usage_max: 33390264320
memory_usage_max: 33453506560
memory_usage_max: 33568980992
memory_usage_max: 33318895616
memory_usage_max: 33331347456
memory_usage_max: 33491255296
memory_usage_max: 33475592192
memory_usage_max: 32676249600

Each line for "memory_usage_max" comes from one node of a 10-node job, and the units are bytes. So the gcc build of PIO is using ~33GB per node on all 10 nodes, while the pgcc build is eating up anywhere from ~63GB to ~176GB per node ... more than a 5x increase in memory utilization for the worst-cases. The per-node pattern is reproducible.  This is using the stock pio-2.4.4 release.

By the trial and error, we found that the problem arises specifically from compilation of clib/pio_rearrange.c with the PGI C compiler, pgcc.  In my tests I was using pgcc vrsion 19.9.  Also, it turns out that we see very little difference in the memory footprints when testing jobs that have small input files, but the effect becomes quite dramatic for large inputs.  The data above was collected with inputs for a 15 km global case, where the input file has about 22 GB of data.  

We do not understand how compilation of pio_rearrange.c is affecting the memory footprint … any insight would be appreciated.  In the mean time, we will just gcc as the underlying C compiler when building PIO.

**Comment by walkup** [comment]
I think the issue is in the box_rearrange_create() function.  There is a set of nested loops where PIO_Offset lcoord[ndims] is declared inside the loop :  for (int k = 0; k < maplen; k++) { ...}.  With the pgcc compiler, it appears that this results in a rather dramatic increase in the memory footprint, depending on the extent of the k-loop, maplen.  The logic in this section of the code is not easy to follow.  Can the declaration for lcoord[ndims] be moved above the k-loop   ... and should there be some initialization for lcoord?

**Comment by jedwards4b** [comment]
I don't see any reason that you couldn't move that declaration outside the k loop and there should not be any need to initialize it.  Can you try it and let us know if it helps?

**Comment by walkup** [comment]
Yes ... I did that and the memory with the PGI compiler drops down to match the footprint with gcc.  I think it is a good idea to move the declaration up, but I would not consider this to be a PIO bug.  Instead I think it is probably undesirable behavior from pgcc, and so I plan to ask them about it.

**Comment by jedwards4b** [comment]
@edhartnett What do you think is the best way to handle this?

**Comment by edwardhartnett** [comment]
The best way is to change to use malloc/free explicitly.  I will change it when I get back from agu.

**Comment by walkup** [comment]
The profile data for my test cases show that a significant fraction of initialization time for a large model is spent inside this k-loop in the box_rearrange_create() function.  If you use malloc/free, it would really be best to move the pointer declaration and malloc/free calls outside the k-loop, else performance will suffer.

**Comment by edhartnett** [comment]
@walkup yes absolutely. If you want to submit a PR, that would be welcome. Otherwise I'll take a look early next week.

**Comment by walkup** [comment]
I am just getting back to this after the holiday break.  From the perspective of an end user, it was sufficient to move the declaration for lcoord[ndims] to just above the loop : for (int k = 0; k < maplen; k++) { …}.  So anything that has the equivalent effect would be fine.  I trust the PIO team to make a minor code adjustment.  I put together a stand-alone test case that demonstrates the memory growth problem when using the pgcc compiler, and have made an attempt to get that to the PGI compiler staff.  This test case is not dependent on PIO, it shows the expected memory behavior with gcc and IBM’s xlc, but blows up with the current pgcc.  My hope is that at some point there will be a fix for pgcc, but I am definitely in favor of adjusting the PIO code to minimize risk.

**Comment by edwardhartnett** [comment]
I have a PR up for this...
