### ISSUE TITLE
 How can I get the type of the variable in pio2?

### ISSUE THREAD

**Issue by xiaohumengdie** [NCAR/ParallelIO#1626]
I have added pio1 to the roms. Now I want to test pio2 in the roms. Before writing the variable, I need to determine the type of the variable. In pio1, I get it through var_desc_t% type. How can I get it in pio2?

**Comment by xiaohumengdie** [comment]
I have solved it by modifying the code（pio_types.F90,pio_nf.F90）.

**Comment by edwardhartnett** [comment]
Can you tell us what the modification was?

**Comment by xiaohumengdie** [comment]
in the ROMS(Regional Ocean Modeling System), I added pio1 and work well . now I want to use pio2 in roms,Before calling pio_write_darray, I need to know the type of vardesc(vardesc% type in pio1).

in pio2 ,the modifacation as follows:
(1)&nbsp;pio_types.F90


(2)&nbsp;pio_nf.F90(add vardesc%type = type)






------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Edward Hartnett"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月19日(星期四) 晚上7:41
收件人:&nbsp;"NCAR/ParallelIO"<ParallelIO@noreply.github.com&gt;;
抄送:&nbsp;"人海孤鸿"<1593487999@qq.com&gt;;"State change"<state_change@noreply.github.com&gt;;
主题:&nbsp;Re: [NCAR/ParallelIO]  How can I get the type of the variable in pio2? (#1626)




Can you tell us what the modification was?

**Comment by xiaohumengdie** [comment]
in the ROMS(Regional Ocean Modeling System), I added pio1 and work well . now I want to use pio2 in roms,Before calling pio_write_darray, I need to know the type of vardesc(vardesc% type in pio1).

in pio2 ,the modifacation as follows:
(1) pio_types.F90(add integer(id) :: type)
type, public :: Var_desc_t
  #ifdef SEQUENCE
       sequence
  #endif
       integer(i4) :: varID !< variable id
       integer(i4) :: ncid  !< file id
       integer(i4) :: type  !< variable type
 end type Var_desc_t
(2) pio_nf.F90(add vardesc%type = type)
integer function def_var_md_desc(File,name,type,dimids,vardesc) result(ierr)
     type (File_desc_t), intent(in)  :: File
     character(len=*), intent(in)    :: name
     integer, intent(in)             :: type
     integer, intent(in)             :: dimids(:)
     type (Var_desc_t), intent(inout) :: vardesc
     vardesc%type = type 
     ierr = def_var_md_id(file%fh,name,type,dimids,vardesc%varid)
end function def_var_md_desc

integer function def_var_0d_desc(File,name,type,vardesc) result(ierr) 
     type (File_desc_t), intent(in)  :: File
     character(len=*), intent(in)    :: name
     integer, intent(in)             :: type
     type (Var_desc_t), intent(inout) :: vardesc
     integer :: dimids(0)
     vardesc%type = type
      ierr = def_var_md_id(File%fh,name,type,dimids,vardesc%varid)
end function def_var_0d_desc

**Comment by edwardhartnett** [comment]
Is this still an active issue?

**Comment by xiaohumengdie** [comment]
no , close it
