### ISSUE TITLE
use pio2 in cesm1_3_beta17

### ISSUE THREAD

**Issue by xiaohumengdie** [NCAR/ParallelIO#1627]
I want to use pio2 in the model cesm1_3_beta17.However, there are some questions that I can’t solve. For exmaple, the programme always blocks in pio_finalize (create_newcase -compset C -res T62_g16 -mach test -case case4). How can I solve it ? I would appreciate it if you could reply me. Thank you.

**Comment by edhartnett** [comment]
I need some more information. ;-)

**Comment by xiaohumengdie** [comment]
the compiler is intelmpi2017. lib version is netcdfc4.6.2，netcdff4.4.4,hdf1.10.4,pnetcdf1.10.0.

**Comment by edhartnett** [comment]
I am not a cesm programmer. Can you isolate the problem into a small PIO program that demonstrates what is going on?

**Comment by xiaohumengdie** [comment]
ok,thank you . Actually, the problem is located. The blocking happens when sub function data_set (visc_file, 'close') is called in the hmix_aniso.F90 . In this process, the sub function data_set(visc_file,'close') only calls pio_finalize. So can you give me some suggests that what i should do next?

**Comment by jedwards4b** [comment]
pio_finalize is a collective operation and thus should be called by all io tasks.  Can you verify that all tasks are getting to the pio_finalize routine?

**Comment by jedwards4b** [comment]
I was able to run to completion using pio2 in cesm1_3_beta17, I ran the test SMS.T62_g16.C.cheyenne_intel
I am using netcdf/4.7.1 and pnetcdf/1.11.1 and intel/19.0.2

**Comment by xiaohumengdie** [comment]
thank you for your reply.  
I tested pio2 in cesm2.1.1 and the program still crashes.  in our QNLM machine ,intel2019 compiler is not available,can you test intel2017?
