### ISSUE TITLE
Some unit tests fail with the same MPI error

### ISSUE THREAD

**Issue by dqwu** [NCAR/ParallelIO#163]
When PIO is built with GCOV flags, 9 unit tests fail with the same MPI error.
4:test_async_simple
5:test_async_3proc
6:test_async_4proc
7:test_iosystem2_simple
8:test_iosystem2_simple2
9:test_iosystem2
10:test_iosystem3_simple
11:test_iosystem3_simple2
12:test_iosystem3

test_async_simple fails like this:
Error 1111 in tests/unit/test_async_simple.c, line 110
Attempting to use an MPI routine after finalizing MPICH

**Comment by jayeshkrishna** [comment]
This issue occurs because pio_test_finalize() calls MPI_Finalize and some tests (the ones above) use the ERR() macro, that uses MPI_Finalize(), to check the return code from pio_test_finalize().
MPI_Finalize() is being called twice when pio_test_finalize() fails.

**Comment by dqwu** [comment]
In fact, calling MPI_Finalize() twice is only one issue. Even if we remove a duplicate call the tests will still fail. In pio_test_finalize(), there is no return statement at the end, so the actual returned value will be undefined (depends on the compiler, could be a random value). It seems that when PIO is not built with GCOV flags, the returned value happens to be 0 (that is why the unit tests will pass). We should explicitly add return PIO_NOERR at the end in test_common.c

**Comment by edhartnett** [comment]
What are the GCOV flags? That's not something I find in either PIO1 or PIO2.

Are you building with the TIMING flag enabled? If so, can you try without that flag?

@jayeshkrishna the issue with finalize is that I am calling ERR() if PIOc_finalize() fails. But by the time it has failed, it has already called MPI_finalize() and so when ERR tries to call it, it fails. Is that what you meant?

I will fix these tests so that a failure in PIOc_finalize() does not call ERR() macro, but there will still be the timing library problem that is causing this issue in the first place.

**Comment by dqwu** [comment]
The CGOV flags (-fprofile-arcs -ftest-coverage) are used for code coverage, see
https://gcc.gnu.org/onlinedocs/gcc/Gcov.html

In fact, there are two issues:
1) MPI_Finalize() are called twice when pio_test_finalize() returns a value that is not 0

2) pio_test_finalize() might return a non-zero value, because the return statement is missing at the end. The return value is undefined (compiler dependent), it could be 0, or some other values like 1. When PIO is built with GCOV flags, we get a non-zero value, which is a false error.

**Comment by edhartnett** [comment]
I have just put up a pull request with fixes for both of those issues.

Do you have results for your gcov runs available anywhere?

We should like to set up gcov runs here as part of our continuous integration. How did you do it? Can you send me the command you run?

**Comment by jayeshkrishna** [comment]
Issue #167 will add support for code coverage report generation in PIO.
