### ISSUE TITLE
Large number of `Read -1` messages when running tests

### ISSUE THREAD

**Issue by Helumpago** [NCAR/ParallelIO#1630]
I recently built PIO and am getting some strange messages from `make check`. All tests pass, but, several of them (for example, `test_rearr`) print out a large number of messages like:

```
[a3fe8b9b35d7:09770] Read -1, expected 131072, errno = 1
``` 

These messages are also being printed by the codes I'm running that use PIO.

I'm using:
- [PIO 2.4.4](https://github.com/NCAR/ParallelIO/releases/tag/pio2_4_4)
- [Parallel NetCDF 1.12.0](http://cucis.ece.northwestern.edu/projects/PnetCDF/Release/pnetcdf-1.12.0.tar.gz)
- [NetCDF 4.7.3](https://www.unidata.ucar.edu/downloads/netcdf/ftp/netcdf-c-4.7.3.tar.gz)

I'm not sure what these messages mean. Any thoughts on where to start digging to figure out what's wrong?

Thank you!

**Comment by jedwards4b** [comment]
I don't see anything in PIO that would print this message - have you checked the pnetcdf and netcdf libraries?

**Comment by jedwards4b** [comment]
It could also be generated in the mpi-io library. You didn't say what mpi library you are using.

**Comment by Helumpago** [comment]
Thanks for the response! The test cases for NetCDF and ParallelNetCDF do not print out the `Read -1` messages. I'm using OpenMPI 4.0.1

I'll keep on digging.

**Comment by jedwards4b** [comment]
Please reopen if you find this to be a pio issue.
