### ISSUE TITLE
compression should not be automatically turned on for netcdf-4 sequential files

### ISSUE THREAD

**Issue by edwardhartnett** [NCAR/ParallelIO#1632]
Currently, if IOTYPE PIO_IOTYPE_NETCDF4C, zlib compression is always turned on for every var.

This kills performance. Probably few are using PIO_IOTYPE_NETCDF4C because of the terrible performance.

Without compression, netCDF-4 sequential is pretty fast. Also, now there are new compression options for the user, including szip and compression with parallel I/O.

I could add a new iotype for non-compressed netCDF-4 sequential data. But I rather doubt that anyone is using this iotype as it is, so I'm inclined to just change it. @jedwards4b what do you think?

**Comment by jedwards4b** [comment]
You are correct that the option is too slow and thus rarely used - but the PIO_IOTYPE_NETCDF already does non-compressed sequential IO.  Is there any value added in having a netcdf-4 sequential option?  

How do you propose implementing the new compression scheme?

**Comment by edwardhartnett** [comment]
The value of a netCDF-4 sequential option is that the output is netcdf/HDF5 instead of netCDF classic.

Also, the new compression options can be applied. That is, the user can select either szip or zlib (and more compression filters are coming). So it makes sense that PIO_IOTYPE_NETCDF4C would give you vars with no compression turned on, allowing the user to select compression settings themselves.

(Similarly it's going to be possible to use PIO_IOTYPE_NETCDF4P and turn on either szip or zlib compression.)

Szip compression is supported with the new nc_def_var_szip() in the netcdf-c library. (I just added it - it's still not released.)

Other forms of compression will be supported by the CCR project, which will provide bzip2, lz4, blosc, and some other compression filters. These will each get their own nc_def_var_* functions in the CCR library (but not in netcdf-c).

PIO will detect the presence or absence of these functions, and will support them with PIOc_ equivalents. They will also be supported for netCDF integration code in their nc_* forms.

**Comment by jedwards4b** [comment]
So the user would have to choose the compression scheme on a per-variable basis in the call to def_var?  What is CCR?

**Comment by edwardhartnett** [comment]
When the user is defining the var, they may select compression, zlib or szip (for now). If they do not turn on any compression, the var is uncompressed. (This is much faster). This matches the way the netCDF API works.

CCR is the Community Codec Repo for netCDF.  It is under development, but will be a library that can be installed, and will offer additional compression filters for netCDF (and, also, HDF5). See https://github.com/ccr/ccr.

My idea is that PIO will detect the presence of CCR and offer access to those compression options. However, first I've got to get CCR working better. ;-)

**Comment by jedwards4b** [comment]
So the user would need to go into model code and specify before compiling which variables should be compressed?  I understand that this matches the netcdf api - but its problematic for model users.  In general the user isn't defining the var, developers are, and the developers are not using the system the user is and have no idea how compression may fare on that system.  It seems like we need to have some kind of runtime control over this.

**Comment by edwardhartnett** [comment]
If models want to allow users to tinker with compression, then they must include some parameters in their own configuration which transfer those values from the user to the PIO layer. (They will have to do that to take advantage of parallel I/O writes with compression, which will be a lot faster.) Or else the model developers may make the compression choices and the users can learn to live with them.

However, that is an orthogonal issue. Currently the model users also have no control over compression, except by messing with the metadata code, and turning off compression for PIO_IOTYPE_NETCDF4C does not change that.

Since no one is using PIO_IOTYPE_NETCDF4C now, this seems like it would be OK. However, if you object, we can continue as we are. Users of the PIOc_ API may not be able to use szip compression with netCDF-4 sequential files, because I'm note sure netcdf-c lets you turn zlib on, then off again.

**Comment by edwardhartnett** [comment]
OK, I have just submitted a PR which allows deflate to be used with parallel netCDF-4. It is not turned on automatically, the user must turn it on by calling PIOc_def_var_deflate() (or fortran equivalent), and users can select deflate level, which has a significant impact on speed, and the size of the result. So this is best left in user hands.

I have reread this thread, and I still think that deflate should not be automatically turned on for netCDF-4 serial files. I would like to change this. Since no one is using netcdf-4 serial, due to performance, this should not have much impact. If anyone is using it, they would have to add a call to PIOc_def_var_deflate() after their call to PIOc_def_var().

This will cause the PIOc API to match the functioning in the netCDF APIs, and also the netCDF integration API.

**Comment by edwardhartnett** [comment]
Closed by mistake. ;-)
