### ISSUE TITLE
detect presence of z5 library in CMake and autotools builds

### ISSUE THREAD

**Issue by edwardhartnett** [NCAR/ParallelIO#1637]
For the Zarr changes, we first need to identify whether or not Z5 is present on the build machine.

Z5 can be found here: https://github.com/constantinpape/z5

Best way to install is to start by installing ananconda. The Z5 is installed with conda.

@halehawk any input would be welcome. Can you describe how you attempt to detect Z5 in CMake?

**Comment by edwardhartnett** [comment]
ALso, it seems that we need to detect if Z5 was built with each of the following options:
with_zlib, with_blosc, with_lz4

**Comment by halehawk** [comment]
@Ed Hartnett <edwardjameshartnett@gmail.com>

In ParallelIO/CMakeLists.txt, we have
if (DEFINED Z5_DIR)
   set(Z5_DIR CACHE PATH "z5 location")

So, my cmake command has the following, I passed Z5_DIR as an option to
cmake. Also I added WITH_ZLIB, WITH_LZ4, WITH_BLOSC option, and BLOSC_ROOT,
LZ4_ROOT, MARRY_INCLUDE_DIR.

CC=mpicc CXX=mpicxx FC=mpif90 cmake
-DCMAKE_INSTALL_PREFIX=~/dev/install_pr/ParallelIO/
-DZ5_DIR=/glade/u/home/weile/miniconda3/envs/z5-py36/include -DWITH_ZLIB=ON
-DZLIB_ROOT=/glade/u/home/weile/miniconda3/envs/z5-py36/
-DBOOST_ROOT=/glade/u/home/weile/miniconda3/envs/z5-py36
-DWITH_MARRAY=ON -DWITH_BLOSC=ON
-DBLOSC_ROOT=/glade/u/home/weile/miniconda3/envs/z5-py36
-DWITH_LZ4=ON -DLZ4_ROOT=/glade/u/home/weile/miniconda3/envs/z5-py36
-DMARRAY_INCLUDE_DIR=/glade/u/home/weile/miniconda3/envs/z5-py36/include
-DCMAKE_VERBOSE_MAKEFILE=ON ..

In the src/clib/CMakeLists.txt, Z5_DIR is used.

Please use z5 release 1.5.0 for testing my z5 wrapper. Z5 2.0.0 has large
change in their APIs.
