### ISSUE TITLE
Tests timing out on Laramie

### ISSUE THREAD

**Issue by Katetc** [NCAR/ParallelIO#164]
While the nightly tests are still not quite working due to cron issues on Laramie, when I run them manually, four tests fail.

test_intercomm2,60.01,Completed (Timeout),Failed,
test_async_simple,60.01,Completed (Timeout),Failed,
test_async_3proc,60.01,Completed (Timeout),Failed,
test_async_4proc,60.01,Completed (Timeout),Failed,

The tests also timeout when given more time (4 minutes) in a manual session. They have been consistently failing for the last 48 hours.

**Comment by Katetc** [comment]
The test_intercomm2 test is hanging in MPI_Intercomm_create . Log output looks like:
1 intracomm created for union cmp = 1 union_rank = 1 union_comm = 6
0 intracomm created for union cmp = 1 union_rank = 0 union_comm = 6
0 my_iosys->io_comm = 5
0 about to create intercomm for IO component to cmp = 1 my_iosys->io_comm = 5
1 my_iosys->io_comm = 5
1 about to create intercomm for IO component to cmp = 1 my_iosys->io_comm = 5
...
2 intracomm created for union cmp = 1 union_rank = 2 union_comm = 5
3 intracomm created for union cmp = 1 union_rank = 3 union_comm = 5
3 about to create intercomm for cmp = 1 my_iosys->comp_comm = 4
2 about to create intercomm for cmp = 1 my_iosys->comp_comm = 4
[and then hangs]

**Comment by Katetc** [comment]
Update: All 4 tests hang at this same point in the code.

**Comment by edhartnett** [comment]
I believe this is all resolved and this issue can be closed...

**Comment by Katetc** [comment]
I believe so as well, but Laramie has not been up to show the results in the nightly tests (my home directory disappeared). I'll open a new PR if the problem pops back up again.
