### ISSUE TITLE
Starting with netcdf-c-4.7.4 zlib compression may be used with NETCDF4P IOTYPE

### ISSUE THREAD

**Issue by edwardhartnett** [NCAR/ParallelIO#1642]
We have some fortran tests that need to be changed. From ncdf_tests.F90:

```
    print*, 'testing PIO_def_var_deflate' 
    shuffle = 0
    deflate = 1
    deflate_level = 2
    deflate_level_2 = 4
    ret_val = PIO_def_var_deflate(pio_file, pio_var, shuffle, deflate, &
         deflate_level)

    ! Should not have worked except for netCDF-4/HDF5 serial.
    if (iotype .eq. PIO_iotype_netcdf4c .and. ret_val .ne. PIO_NOERR) then
       err_msg = "Could not turn on compression for variable foo2222"
       call PIO_closefile(pio_file)
       return
    else if (iotype .eq. PIO_iotype_pnetcdf .and. ret_val .eq. PIO_NOERR) then
       err_msg = "Did not get expected error when trying to turn deflate on for pnetcdf file"
       call PIO_closefile(pio_file)
       return
    else if (iotype .eq. PIO_iotype_netcdf .and. ret_val .eq. PIO_NOERR) then
       err_msg = "Did not get expected error when trying to turn deflate on for netcdf classic file"
       call PIO_closefile(pio_file)
       return
    else if (iotype .eq. PIO_iotype_netcdf4p .and. ret_val .eq. PIO_NOERR) then
       err_msg = "Did not get expected error when trying to turn deflate on for parallel netcdf-4 file"
       call PIO_closefile(pio_file)
       return
    end if

```

**Comment by nichannah** [comment]
There is still library code preventing deflate from being called for PIO_iotype_netcdf4p:

https://github.com/NCAR/ParallelIO/blob/master/src/clib/pio_nc4.c#L87

**Comment by edwardhartnett** [comment]
@nichannah did you try commenting out those lines to see if this worked?

**Comment by nichannah** [comment]
This is working well for me. I've done a test comparing ParallelIO to using the parallel netcdf4.7.4p (and MPI ompio) directly and have found a reasonable speed-up with ParallelIO. The test has about 120 2d and 20 3d fields on a 3600x2700 grid running across ~700 PEs. Do you have any suggestions as to why ParallelIO should be faster here?

**Comment by edwardhartnett** [comment]
You would need to tell me a lot more about how you are doing the write. For example with PIO intracomm or async? And how many IO nodes?

**Comment by nichannah** [comment]
Thanks - any discussion is helpful for me to better understand things. I'm using intracomm, rearr_box, 1 aggregator and 1 IO node. Also, significantly, each PE is outputting 8 geographically distributed 'blocks' of data. this is done to improve load balancing. 

I think my problem is that I don't understand what PIO is doing differently or in addition to parallel netcdf+MPIO. e.g. the relationship between PIO io nodes and MPI aggregators.

**Comment by jedwards4b** [comment]
@nichannah   Here are some slides that may help https://docs.google.com/presentation/d/1xndUaEsAMzm-swRhOinVA1JYed-FC05JZKuqu14tOxQ/edit?usp=sharing  With rearr_box and num IO tasks== num PES what you are doing is an all to all rearrangement of data prior to writing.  If you use rearr_subset and num IO tasks == num PES you should get the performance of the underlying library (pnetcdf or netcdf4) - if you reduce the number of IO tasks You will start to see the real advantage of PIO in intracomm mode.

**Comment by edwardhartnett** [comment]
This issue is now fixed in master branch.
