### ISSUE TITLE
cmake failed because of genf90 issue in offline computer

### ISSUE THREAD

**Issue by daxiawj** [NCAR/ParallelIO#1648]
in a computer which cannot access the internet, cmake failed because it need to download genf90 in github. how can I resolve this? thanks!

**Comment by edhartnett** [comment]
Howdy!

Best would be to use the autotools build system instead of cmake.

Ed

**Comment by daxiawj** [comment]
Thanks for your reply. while use autotools. 
it says: "
```
libtool:   error: cannot find the library '/usr/lib64/libpmi.la' or unhandled argument '/usr/lib64/libpmi.la'
```
I don't know what's wrong with this and how to deal with.

**Comment by edhartnett** [comment]
You need to set CC to mpicc or whatever the MPI-enabled C compiler is. You
also need to set CPPFLAGS and LDFLAGS to point at whatever directories you
need to find netCDF and parallel-netcdf.

See https://ncar.github.io/ParallelIO/install.html
