### ISSUE TITLE
request to add PIO_Short datatype 

### ISSUE THREAD

**Issue by jedwards4b** [NCAR/ParallelIO#1652]
In order to read and write [era5 data](https://cds.climate.copernicus.eu/cdsapp#!/dataset/reanalysis-era5-single-levels?tab=form)

**Comment by edwardhartnett** [comment]
Don't we already have all data types, including short?

**Comment by jedwards4b** [comment]
I didn't see it in the fortran interface, maybe it just needs to be added
there.
