### ISSUE TITLE
pio_meta.h not completed 

### ISSUE THREAD

**Issue by jedwards4b** [NCAR/ParallelIO#1663]
Maybe I did something wrong in my build but pio_meta.h looks like:
#define PIO_VERSION_MAJOR @PIO_VERSION_MAJOR@ /*!< pio-c major version. */
#define PIO_VERSION_MINOR @PIO_VERSION_MINOR@ /*!< pio-c minor version. */
#define PIO_VERSION_PATCH @PIO_VERSION_PATCH@ /*!< pio-c patch version. */
#define PIO_VERSION       "2.5.1-development"

#define PIO_HAS_SZIP_WRITE @PIO_HAS_SZIP_WRITE@ /*!< szip write support */
#define PIO_HAS_PNETCDF   1 /*!< PnetCDF support. */
#define PIO_HAS_PAR_FILTERS 0 /* NetCDF supports parallel I/O with filters. */

**Comment by edwardhartnett** [comment]
Something got messed up! Stand by...
