### ISSUE TITLE
Code coverage for PIO

### ISSUE THREAD

**Issue by jayeshkrishna** [NCAR/ParallelIO#167]
We need to add code coverage support for PIO. This involves,
- Adding build flags and the necessary mechanism to optionally turn on code coverage report generation (Initially only gnu compilers will be supported)
- Adding documentation on how to view the code coverage output generated.

**Comment by jayeshkrishna** [comment]
@jedwards4b : Please add your thoughts.

**Comment by edhartnett** [comment]
Some requirements:
* Must be able to be turned on and off from configure (default should be off).
* Must be completely automated so it can be run by continuous integration.
* C library coverage should be separate from Fortran coverage.
* GNU compilers only is fine. 

This is a great idea and I can't wait to see the results!!

**Comment by edhartnett** [comment]
Any progress on this? I would love to know what code is not tested yet.

**Comment by dqwu** [comment]
Branch dqwu/code_coverage has been tested on Jenkins server of MCS at ANL. You can download the latest coverage report from the link below:
https://jenkins-ci.mcs.anl.gov/job/ParallelIO/30/

You can also view more detailed information in the Console Output.

We will merge this branch to master soon.

**Comment by edhartnett** [comment]
Awesome! Thanks!

**Comment by edhartnett** [comment]
Is there a way to see the coverage report thru your jenkins server?

I was able to download it, unpack it, and use my browser to look locally, but I can't find a way to look at it through your jenkins page.

Thanks!

**Comment by dqwu** [comment]
I think that requires a plugin of HTML publisher on Jenkins server. We need request the Jenkins admin to install it and it will take some time.

**Comment by edhartnett** [comment]
We are up to 69% code coverage for the C library.

I just went through each code file and added a ticket for each function that was untested.

**Comment by edhartnett** [comment]
I will close this issue since we have had code coverage for some time now.
