### ISSUE TITLE
Issue when appending existing files

### ISSUE THREAD

**Issue by jedwards4b** [NCAR/ParallelIO#1670]
I am running into an error when appending to an existing netcdf file and have attached a simple example below.
When the file is initially created and written all works fine, but then the file is closed and reopened to append.
The issue is that in the vardesc data structure the rec_var variable is not initialized, this causes the 1d and 2d variables to 
be put into the same wmb data structure which leads to an error at pio_darray.c:192

`/*piotest uses mpi but runs on 1 task*/
#include <stdio.h>
#include <mpi.h>
#include <pio.h>

main(int argc, char **argv)
{
    int node;
    int iosys;
    int ncid;
    int iotype = PIO_IOTYPE_NETCDF;
    int dimid[2], varid[2];
    int i;
    int dimsize=42;
    int var[dimsize];
    PIO_Offset compmap[dimsize];
    int ioid;
    int ierr;

    MPI_Init(&argc,&argv);
    MPI_Comm_rank(MPI_COMM_WORLD, &node);
    if (node > 0){
	printf("Test intended for a single task\n");
	MPI_Abort(MPI_COMM_WORLD, -1);
    }
    ierr = PIOc_Init_Intracomm( MPI_COMM_WORLD, 1, 1, 0, PIO_REARR_SUBSET, &iosys);
    if(ierr) printf("%d %d\n",__LINE__,ierr);
    ierr = PIOc_createfile(iosys, &ncid, &iotype, "test1.nc", PIO_CLOBBER);
    if(ierr) printf("%d %d\n",__LINE__,ierr);
    ierr = PIOc_def_dim(ncid, "dim1", PIO_UNLIMITED, dimid);
    if(ierr) printf("%d %d\n",__LINE__,ierr);
    ierr = PIOc_def_dim(ncid, "dim2", (PIO_Offset) dimsize, dimid+1);
    if(ierr) printf("%d %d\n",__LINE__,ierr);
    ierr = PIOc_def_var(ncid, "var1", PIO_INT, 1, dimid+1, varid);
    if(ierr) printf("%d %d\n",__LINE__,ierr);
    ierr = PIOc_def_var(ncid, "var2", PIO_INT, 2, dimid, varid+1);
    if(ierr) printf("%d %d\n",__LINE__,ierr);
    ierr = PIOc_enddef(ncid);
    if(ierr) printf("%d %d\n",__LINE__,ierr);

    for(i=0;i<dimsize;i++){
	var[i] = i;
	compmap[i] = i+1;
    }

    ierr = PIOc_InitDecomp(iosys, PIO_INT, 1, &dimsize, dimsize,  compmap, &ioid, NULL, NULL, NULL);
    if(ierr) printf("%d %d\n",__LINE__,ierr);
    ierr = PIOc_write_darray(ncid, varid[0], ioid, (PIO_Offset) dimsize, var, NULL);
    if(ierr) printf("%d %d\n",__LINE__,ierr);
    ierr = PIOc_setframe(ncid, varid[1], 0);
    if(ierr) printf("%d %d\n",__LINE__,ierr);
    ierr = PIOc_write_darray(ncid, varid[1], ioid, (PIO_Offset) dimsize, var, NULL);
    if(ierr) printf("%d %d\n",__LINE__,ierr);

    ierr = PIOc_closefile(ncid);
    if(ierr) printf("%d %d\n",__LINE__,ierr);

    ierr = PIOc_openfile(iosys, &ncid, &iotype, "test1.nc", PIO_WRITE);
    if(ierr) printf("%d %d\n",__LINE__,ierr);
    ierr = PIOc_inq_varid(ncid, "var1", varid);
    if(ierr) printf("%d %d\n",__LINE__,ierr);
    ierr = PIOc_inq_varid(ncid, "var2", varid+1);
    if(ierr) printf("%d %d\n",__LINE__,ierr);
    ierr = PIOc_write_darray(ncid, varid[0], ioid, (PIO_Offset) dimsize, var, NULL);
    if(ierr) printf("%d %d\n",__LINE__,ierr);
    ierr = PIOc_setframe(ncid, varid[1], 1);
    if(ierr) printf("%d %d\n",__LINE__,ierr);
    ierr = PIOc_write_darray(ncid, varid[1], ioid, (PIO_Offset) dimsize, var, NULL);
    if(ierr) printf("%d %d\n",__LINE__,ierr);

    ierr = PIOc_closefile(ncid);
    if(ierr) printf("%d %d\n",__LINE__,ierr);

    MPI_Finalize();
}
`

**Comment by edwardhartnett** [comment]
@jedwards4b this is fixed and this issue may be closed, correct?

**Comment by jedwards4b** [comment]
Yes I thought it would autoclose when mentioned in the PR.
