### ISSUE TITLE
who ever heard of FPPFLAGS?

### ISSUE THREAD

**Issue by edwardhartnett** [NCAR/ParallelIO#1684]
@jedwards4b you just added FPPFLAGS to the summary.

I literally have never seen that before. ;-)

Is FPPFLAGS respected by the build? I don't believe it is.

So what do you mean by FPPFLAGS? Who sets it? The user, or the CMake build?

I see that you are setting them in src/flib/CMakeLists.txt:

```
foreach(x IN LISTS fppdefs)
  string(APPEND FPPFLAGS " -D${x}")
endforeach()
foreach(x IN LISTS fincludes)
  if (x)
    string(APPEND FPPFLAGS " -I${x}")
  endif()
endforeach()
set(FPPFLAGS ${FPPFLAGS} PARENT_SCOPE)
```

How does this get honored by the fortran comile? I see where it is set, but I don't see where it is used.

**Comment by jedwards4b** [comment]
The name FPPFLAGS is not used by cmake at all.  I am just using it to convey the information back to the libpio.settings file.

**Comment by edwardhartnett** [comment]
OK, let's not introduce the term FPPFLAGS. Soon we will have users trying to set FPPFLAGS and asking why it doesn't work. ;-)
