### ISSUE TITLE
change in tag naming convention starting 2_5_1?

### ISSUE THREAD

**Issue by aerorahul** [NCAR/ParallelIO#1711]
It seems that the naming convention of tags changed with tag 2.5.1.

v2.5.1 is tagged as `pio_2_5_1` where as all tags leading up to v2.5.0 are tagged as `pio2_5_0`.

Is this an oversight or a change that will be followed going forward?

**Comment by edwardhartnett** [comment]
Whoops! That was not intentional.

Rahul I am surprised to see you using PIO. Is it used somewhere at NOAA?

**Comment by aerorahul** [comment]
@edhartnett 
[CMEPS/nems](https://github.com/ESCOMP/CMEPS/tree/master/nems/lib)
Trying to build ParalleIIO as an external dependency instead of as a submodule.

PIO is also a IO option in [CICE](https://github.com/DeniseWorthen/CICE/tree/dd5ecc934646cdaf9e9350827abeeb4b5c023e15/cicecore/cicedynB/infrastructure/io/io_pio2)

Both are components of the UFS-s2s-model.

**Comment by edwardhartnett** [comment]
OK, I will close this ticket and hopefully will tag the next release correctly.
