### ISSUE TITLE
cmake build out of source broken if source directory not writable 

### ISSUE THREAD

**Issue by jedwards4b** [NCAR/ParallelIO#1712]
cmake build should work even if the source directory is not writable.  However I am getting an error:
CMake Error: Could not open file for write in copy operation /glade/u/home/turuncu/UFS/ufs-hafs-app/cime/src/externals/pio2/src/clib/pio_meta.h.tmp
CMake Error: : System Error: Permission denied

**Comment by edwardhartnett** [comment]
OK, I see what is going on. Stand by...
