### ISSUE TITLE
CMake build calling FindNetCDF() in multiple places

### ISSUE THREAD

**Issue by edwardhartnett** [NCAR/ParallelIO#1724]
Seems like the cmake build tries to find netCDF at least three times, once in the main level cmake file, once in src/clib, and once again (which seems to be failing, see #1721) in src/flib.

I am adding netCDF integration and I am copying this idiom so now there will be another call in src/ncint.

I know that cmake is considerably sloppier than autotools, but finding netCDF over and over again seems to be a bit much. Perhaps we can just find it one time and use the results everywhere? I'm not quite sure how to do this in CMake...

**Comment by jedwards4b** [comment]
I'll try to look into this soon.
