### ISSUE TITLE
pio_iosystem_tests3.F90 fails to build on trunk...

### ISSUE THREAD

**Issue by edhartnett** [NCAR/ParallelIO#174]
I just checked out a clean clone of master, and attempted to build:

[ed@localhost ParallelIO]$ cd build/
[ed@localhost build]$ rm -rf * && CFLAGS=-g FFLAGS=-g CC=mpicc FC=mpifort cmake -DPIO_ENABLE_LOGGING=On -DNetCDF_C_PATH=/usr/local -DNetCDF_Fortran_PATH=/usr/local -DPnetCDF_PATH=/usr/local -DPIO_HDF5_LOGGING=On .. && make VERBOSE=1 all tests check

The build fails when trying to put pio_iosystem_tests3.F90 together:

cd /home/ed/pio5/ParallelIO/build/tests/general && ../../../tests/general/util/pio_tf_f90gen.pl --annotate-source --out=/home/ed/pio5/ParallelIO/build/tests/general/pio_iosystem_tests3.F90 /home/ed/pio5/ParallelIO/tests/general/pio_iosystem_tests3.F90.in
Can't use global $_ in "my" at ../../../tests/general/util/pio_tf_f90gen.pl line 486, near "($_"
Global symbol "$ref_templ_typenames" requires explicit package name (did you forget to declare "my $ref_templ_typenames"?) at ../../../tests/general/util/pio_tf_f90gen.pl line 486.
Global symbol "$ref_templ_typenames" requires explicit package name (did you forget to declare "my $ref_templ_typenames"?) at ../../../tests/general/util/pio_tf_f90gen.pl line 511.
Execution of ../../../tests/general/util/pio_tf_f90gen.pl aborted due to compilation errors.
tests/general/CMakeFiles/pio_iosystem_tests3.dir/build.make:61: recipe for target 'tests/general/pio_iosystem_tests3.F90' failed
make[3]: *** [tests/general/pio_iosystem_tests3.F90] Error 255
make[3]: Leaving directory '/home/ed/pio5/ParallelIO/build'
CMakeFiles/Makefile2:1913: recipe for target 'tests/general/CMakeFiles/pio_iosystem_tests3.dir/all' failed
make[2]: *** [tests/general/CMakeFiles/pio_iosystem_tests3.dir/all] Error 2
make[2]: Leaving directory '/home/ed/pio5/ParallelIO/build'
CMakeFiles/Makefile2:1259: recipe for target 'tests/CMakeFiles/tests.dir/rule' failed
make[1]: *** [tests/CMakeFiles/tests.dir/rule] Error 2
make[1]: Leaving directory '/home/ed/pio5/ParallelIO/build'
Makefile:589: recipe for target 'tests' failed
make: *** [tests] Error 2

If this cannot be fixed quickly, let's comment this test out of the master branch, and let development continue on a branch.

I have just moved to a new system, so this may be related to missing tools or libraries. I will investigate further.

**Comment by jedwards4b** [comment]
works for me on yellowstone - what version of perl do you have?

**Comment by jayeshkrishna** [comment]
Let us not comment out any tests on master.

**Comment by jayeshkrishna** [comment]
Is this error (bug in perl) -https://rt.cpan.org/Public/Bug/Display.html?id=108203  - the same ?

**Comment by jayeshkrishna** [comment]
What version of perl do you have? I have 5.22.1 on my laptop.
Let me see if I can recreate with a newer version of perl.

**Comment by jedwards4b** [comment]
It's not too old but too new for the script.  I'll fix it.

**Comment by jayeshkrishna** [comment]
@jedwards4b : Are you going to fix the script (replacing the lexical decl of $_ with a subsequent assignment to $_ should work, right?)?

**Comment by jedwards4b** [comment]
yes, testing the change now

**Comment by edhartnett** [comment]
Thanks for the quick fix.
