### ISSUE TITLE
Error: Can't find or link to the netcdf library.

### ISSUE THREAD

**Issue by afernandezody** [NCAR/ParallelIO#1757]
Hello,
I keep getting the following error while trying to install PIO:
```
./configure --prefix=$PIO
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking build system type... aarch64-unknown-linux-gnu
checking host system type... aarch64-unknown-linux-gnu
checking how to print strings... printf
checking whether make supports the include directive... yes (GNU style)
checking for gcc... /opt/openmpi5/bin/mpicc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether /opt/openmpi5/bin/mpicc accepts -g... yes
checking for /opt/openmpi5/bin/mpicc option to accept ISO C89... none needed
checking whether /opt/openmpi5/bin/mpicc understands -c and -o together... yes
checking dependency style of /opt/openmpi5/bin/mpicc... gcc3
checking for a sed that does not truncate output... /usr/bin/sed
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for fgrep... /usr/bin/grep -F
checking for ld used by /opt/openmpi5/bin/mpicc... ld
checking if the linker (ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 1572864
checking how to convert aarch64-unknown-linux-gnu file names to aarch64-unknown-linux-gnu format... func_convert_file_noop
checking how to convert aarch64-unknown-linux-gnu file names to toolchain format... func_convert_file_noop
checking for ld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for ar... ar
checking for archiver @FILE support... @
checking for strip... strip
checking for ranlib... ranlib
checking command to parse /usr/bin/nm -B output from /opt/openmpi5/bin/mpicc object... ok
checking for sysroot... no
checking for a working dd... /usr/bin/dd
checking how to truncate binary pipes... /usr/bin/dd bs=4096 count=1
checking for mt... no
checking if : is a manifest tool... no
checking how to run the C preprocessor... /opt/openmpi5/bin/mpicc -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for dlfcn.h... yes
checking for objdir... .libs
checking if /opt/openmpi5/bin/mpicc supports -fno-rtti -fno-exceptions... no
checking for /opt/openmpi5/bin/mpicc option to produce PIC... -fPIC -DPIC
checking if /opt/openmpi5/bin/mpicc PIC flag -fPIC -DPIC works... yes
checking if /opt/openmpi5/bin/mpicc static flag -static works... no
checking if /opt/openmpi5/bin/mpicc supports -c -o file.o... yes
checking if /opt/openmpi5/bin/mpicc supports -c -o file.o... (cached) yes
checking whether the /opt/openmpi5/bin/mpicc linker (ld) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... yes
checking for gcc... (cached) /opt/openmpi5/bin/mpicc
checking whether we are using the GNU C compiler... (cached) yes
checking whether /opt/openmpi5/bin/mpicc accepts -g... (cached) yes
checking for /opt/openmpi5/bin/mpicc option to accept ISO C89... (cached) none needed
checking whether /opt/openmpi5/bin/mpicc understands -c and -o together... (cached) yes
checking dependency style of /opt/openmpi5/bin/mpicc... (cached) gcc3
checking whether we are using the GNU Fortran compiler... yes
checking whether /opt/openmpi5/bin/mpif90 accepts -g... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... yes
checking for /opt/openmpi5/bin/mpif90 option to produce PIC... -fPIC
checking if /opt/openmpi5/bin/mpif90 PIC flag -fPIC works... yes
checking if /opt/openmpi5/bin/mpif90 static flag -static works... no
checking if /opt/openmpi5/bin/mpif90 supports -c -o file.o... yes
checking if /opt/openmpi5/bin/mpif90 supports -c -o file.o... (cached) yes
checking whether the /opt/openmpi5/bin/mpif90 linker (ld) supports shared libraries... yes
checking dynamic linker characteristics... (cached) GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether a PIO_BUFFER_SIZE was specified... 134217728
checking whether debug logging is enabled... no
checking whether GPTL timing library is used... no
checking whether PAPI should be enabled (if enable-timing is used)... yes
checking whether test runs should be enabled for make check... yes
checking whether Fortran library should be built... no
checking whether use of MPE library is enabled... no
checking whether pnetcdf is to be used... yes
checking whether documentation should be build (requires doxygen)... no
checking whether PIO developer documentation should be build (only for PIO developers)... no
checking whether a user specified program to run mpi programs... mpiexec
checking for doxygen... no
configure: processing doxyfile
configure: finding libraries
checking for MPI_Init... yes
checking for nc_create in -lnetcdf... no
configure: error: Can't find or link to the netcdf library.
```
The compilation script is:
```
cd pio-2.5.2
export MPIFC=mpif90
export PNETCDF_PATH=/opt/netcdf
export PIO=/root/PIO
./configure --prefix=$PIO
```
I went back and reinstalled netcdf-c, netcdf-fortrand and netcdf4 in the same directory (/opt/netcdf). It seems not to be able to find nc_create but I'm not sure where it's looking for it. Thanks.

**Comment by jedwards4b** [comment]
The netcdf path is required in NETCDF_PATH, pnetcdf is a separate library and is an optional library.  https://parallel-netcdf.github.io/

**Comment by afernandezody** [comment]
Hi @**jedwards4b**, 
Yesterday I tried different combinations and I just tried again with NETCDF_PATH to /opt/netcdf (location for netcdf-c, netcdf-fortrand and netcdf4). However, it's still failing with the same error. Thanks.

**Comment by edwardhartnett** [comment]
Firstly, this business of NETCDF_PATH is strictly a CMake deal. Autotools doesn't use bizarre once-off environment variables because of all the silly confusion they cause.  ;-)

With the autotools build, the relevant environment variables are the standard (and always the same) CPPFLAGS, CFLAGS, LDFLAGS, etc.

So you need to have the netCDF install library directory in LDFLAGS and include directory in CPPFLAGS like this: 

```
export LDFLAGS=-L/some/dir/with/netcdf/lib
export CPPFLAGS=-I/some/dir/with/netcdf/include
configure --prefix=$PIO

```

When configure runs, it creates an output file called config.log.

Please take a look in your config.log to see why the attempt to link with nc_create is failing. The compile command that was attempted, and the error output, will be in config.log and will tell us what the problem was. If you can't figure it out attach the config.log file and I'll take a look.

**Comment by afernandezody** [comment]
Hi,
I checked the config.log yesterday but it was simply complaining about not finding the netcdf libraries (a copy of  the log is attached). The netcdf libraries are there (even w/o LDFLAGS or CPPFLAGS):
```
 ldconfig -p | grep netcdf
        libnetcdff.so.7 (libc6,AArch64) => /opt/netcdf/lib/libnetcdff.so.7
        libnetcdff.so (libc6,AArch64) => /opt/netcdf/lib/libnetcdff.so
        libnetcdf.so.18 (libc6,AArch64) => /opt/netcdf/lib/libnetcdf.so.18
        libnetcdf.so (libc6,AArch64) => /opt/netcdf/lib/libnetcdf.so
```
The log had two gcc errors but not sure what to make out of them. 
[config.log](https://github.com/NCAR/ParallelIO/files/5256331/config.log)

**Comment by edwardhartnett** [comment]
Try setting LDFLAGS=-L/opt/netcdf/lib and rerun configure.

**Comment by afernandezody** [comment]
Not really sure why my 1st attempt setting LDFLAGS failed (it was like if the system was ignoring it) but the configuration finally went through. I had a similar problem with CPPFLAGS as $CPPFLAGS was pointing to the right subdirectory but was showing empty in the 'Makefile" file (had to type it manually). The system is in alpha phase so there might be some glitches. Then, the compilation failed while at clib with the error:```

/usr/bin/ld: /opt/netcdf/lib/libpnetcdf.a(attr_getput.o): relocation R_AARCH64_ADR_PREL_PG_HI21 against symbol `ompi_mpi_int' which may bind externally can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /opt/netcdf/lib/libpnetcdf.a(attr_getput.o)(.text+0x9c): unresolvable R_AARCH64_ADR_PREL_PG_HI21 relocation against symbol `ompi_mpi_int'
/usr/bin/ld: final link failed: Bad value
collect2: error: ld returned 1 exit status
make[3]: *** [Makefile:485: libpioc.la] Error 1
make[3]: Leaving directory '/root/pio-2.5.2/src/clib'
make[2]: *** [Makefile:400: all-recursive] Error 1
make[2]: Leaving directory '/root/pio-2.5.2/src'
make[1]: *** [Makefile:449: all-recursive] Error 1
make[1]: Leaving directory '/root/pio-2.5.2'
make: *** [Makefile:379: all] Error 2
```
Not sure if this error rings any bell. Maybe compiling with -fPIC will fix it but it has to wait for a couple of hours as I'm a bit late for something else.

**Comment by edwardhartnett** [comment]
OK, one tricky thing about pnetcdf is that they have turned off shared libraries by default. So I believe you must rebuild pnetcdf with --enable-shared as a configure option. Also make sure you do a make clean in the pnetcdf directory before rebuilding it.

Also, you should never be editing the generated Makefiles and that is unlikely to lead to a good result.

Please attach or post the full output of configure and make, and the config.log file, and we can see what is going on.

**Comment by afernandezody** [comment]
I recompiled PnetCDF with `--enabled-shared` but the (PIO) configuration was failing at conftest while processing the MPI_Offset instruction.
NOTE: I don't disagree with what you're saying about manually modifying Makefiles. However, the system is in alpha testing and I have until tomorrow to test as much as possible (then they'll wipe it clean). I'm occasionally
[config1.log](https://github.com/NCAR/ParallelIO/files/5257595/config1.log)
 taking some liberties when, otherwise, would look for more orthodox solutions.

**Comment by afernandezody** [comment]
I might have been able to push this through by not reconfiguring, simply using the previous makefile with the new PnetCDF installation.

**Comment by afernandezody** [comment]
Hi @**edhartnett**, 
I was able to do a clean installation, which passed the check, and everything seemed fine (libraries & headers are there). However, compilations (e.g. -I/PATH-TO-PIO/pio-2.5.2/include pio2.f90) are not able to find pio.mod and return. 
`Fatal Error: Cannot open module file 'pio.mod' for reading at (1): No such file or directory`
Any idea on why compilers cannot find the module? Thanks.

**Comment by edwardhartnett** [comment]
OK, so PIO built and tested OK?

You built with --enable-fortran?

And you ran make check and it succeeded?

Did you provide a --prefix option to configure to tell it where to install PIO?

**Comment by afernandezody** [comment]
Hi @**edwardhartnett**,
It's now working. I was following a MPAS tutorial, which didn't specify to compile PIO with --enable-fortran. It was my bad because, after reading the README.md, my first attempts at compiling included the flag, but I dropped it at some point and forgot about it. 
Thank you for all your help. I'm closing the issue.

**Comment by edwardhartnett** [comment]
Great! Glad we got it all working in the end. ;-)
