### ISSUE TITLE
Integration with WRF?

### ISSUE THREAD

**Issue by MichaelLaufer** [NCAR/ParallelIO#1766]
Hi,
I was wondering if PIO2 is supported in [WRF v4 ](https://github.com/wrf-model/WRF)?

There appears to be initial support for PIO  in WRF, but the code has not been touched in 6+ years. 
Is there any chance that the moden PIO2 library witll work with WRF as is?
Also, is there any comparison of the PIO library to the built in WRF "quilt server" functionality?

Any leads would be most appreciated.
Thanks,

**Comment by jedwards4b** [comment]
I think that you need to take this question to the WRF developers.

**Comment by edwardhartnett** [comment]
Also consider that the new PIO netCDF integration feature means that existing netCDF code can be used for PIO.
