### ISSUE TITLE
PIO compilation problem (PIO 2.4.4)

### ISSUE THREAD

**Issue by Enea2301** [NCAR/ParallelIO#1777]
Hi! I'm trying to compile PIO for use with MPAS (GPU version) model.

So far, I've been installing all other requested libraries nice. openmpi is installed on it's 4.0.5 version, and apparently without errors. This is also reinforced by the perfect compilation of pnetcdf (all tests were ok and this library can't be compiled without proper openmpi).

The problem arises when I try to compile PIO. All flags, libraries and everything are set correctly. Nevertheless, PIO keeps spamming one error:

"checking for MPI_Init... no
configure: error: Can't link to MPI library. MPI is required."

Where could the problem be? Any help would be appreciated, as I'm totally stuck. I'll keep trying, but I don't expect to solve it.

Thanks!

Roberto

**Comment by edwardhartnett** [comment]
Did you set CC=mpicc?

**Comment by Enea2301** [comment]
> Did you set CC=mpicc?

Nope. I've just tried it and it seems to work fine. I'd never thought it was that it needed to be set as CC=mpicc, and don't recall reading it elsewhere... Doesn't surprise me though, I'm still quite new to many of this libraries.

One question arises:
Fortran compiler has to be "normal" (ie: pgfortran) or the parallel-enabled version (ie: mpif90)?

Thanks for your help!

**Comment by edwardhartnett** [comment]
No fortran compiler must also be the MPI version. ;-)

Good luck!
