### ISSUE TITLE
error in pio_get_att (async only)

### ISSUE THREAD

**Issue by jedwards4b** [NCAR/ParallelIO#1783]
If PIOc_get_att is called on an attribute that does not exist in the file there is a problem.  
The compute tasks (only) call PIOc_inq_att at line 268 of pio_getput_int.c which correctly returns
ierr = -43 (NC_ENOTATT) but the iotasks do not take note of this error and get hung at line 704 of
pio_msg.c waiting for ncid.

**Comment by edwardhartnett** [comment]
Good catch!

**Comment by jedwards4b** [comment]
I have a solution, it turns out to be pretty elaborate though, and currently failing some regression tests.
