### ISSUE TITLE
Sort out where NF_PIO constant should be, and put it there

### ISSUE THREAD

**Issue by edwardhartnett** [NCAR/ParallelIO#1787]
In tests/fncint/ftst_pio.f90 we have:

 ```
 ! Create a file.
  ierr = nf_create(FILE_NAME, 64, ncid)
  if (ierr .ne. nf_noerr) call handle_err(ierr)

```

The 64 is the constant that should be defined somewhere as NF_PIO.

**Comment by jedwards4b** [comment]
Shouldn't this be defined in netcdf not pio?  Or should it be in pio but only defined with NETCDF_INTEGRATION?

**Comment by edwardhartnett** [comment]
It should be in PIO and is only  used with netCDF integration. 

There is a netCDF integration mod file, so I could put it there...

**Comment by jedwards4b** [comment]
I have a PR incoming and will include this change.
