### ISSUE TITLE
Failed test not detected?

### ISSUE THREAD

**Issue by edwardhartnett** [NCAR/ParallelIO#1792]
Build on hera this morning, I see this:

```
running test_darray_async_many
1 Error 1112 in test_darray_async_many.c, line 227
2 Error 1112 in test_darray_async_many.c, line 227
3 Error 1112 in test_darray_async_many.c, line 227
1 Error 1112 in test_darray_async_many.c, line 227
2 Error 1112 in test_darray_async_many.c, line 227
3 Error 1112 in test_darray_async_many.c, line 227

```

Yet the make check target succeeded! That's not good.

**Comment by jedwards4b** [comment]
I'm not able to reproduce this.  Can you elaborate on the setup?

**Comment by edwardhartnett** [comment]
This is on hera, with HDF5 1.12.0. I am going to try again shortly...

**Comment by edwardhartnett** [comment]
This is still happening on hera:
```
running test_darray_async_many
1 Error 1112 in test_darray_async_many.c, line 231
2 Error 1112 in test_darray_async_many.c, line 231
3 Error 1112 in test_darray_async_many.c, line 231
1 Error 1112 in test_darray_async_many.c, line 231
2 Error 1112 in test_darray_async_many.c, line 231
3 Error 1112 in test_darray_async_many.c, line 231
1 Error 13 in test_darray_async_many.c, line 460
2 Error 13 in test_darray_async_many.c, line 460
3 Error 13 in test_darray_async_many.c, line 460
```

However, now the test hangs instead of thinking it succeeded. So that's some improvement, but we still need to investigate why a failure in the test did not cause make check to fail.

**Comment by edwardhartnett** [comment]
The first thing I notice is that the error codes are incorrect. There is no error code 1112 or 13, so what's going on with that?

Here was a problem. In the test_darray_async_many.c code I had this:

            case PIO_INT64:
                if (((long long *)norec_data_in)[r] != expected_int64[r])
                    PBAIL(ERR_WRONG);
                break;

This calls the PBAIL macro in case of problems, which is defined in src/clib/pio_error.h:

```
/**
 * Handle non-MPI errors by printing error message and goto exit. This
 * is used in test code.
 */
#define PBAIL(e) do {                                                    \
        fprintf(stderr, "%d Error %d in %s, line %d\n", my_rank, e, __FILE__, __LINE__); \
        goto exit;                                                      \
    } while (0)

```

Note that this uses a goto exit as a way to clean up resources. The exit label looks like this:
```
exit:
    if (data_in)
        free(data_in);
    if (norec_data_in)
        free(norec_data_in);
    return ret;

```

Well in the case of this error, ret is never set. So I have changed the PBAIL macro to this:

```
/**
 * Handle non-MPI errors by printing error message and goto exit. This
 * is used in test code.
 */
#define PBAIL(e) do {                                                    \
        fprintf(stderr, "%d Error %d in %s, line %d\n", my_rank, e, __FILE__, __LINE__); \
	ret = e;                                                        \
        goto exit;                                                      \
    } while (0)

```

This does not explain why the test didn't fail, but it does explain and fix the weird error numbers.

**Comment by edwardhartnett** [comment]
OK, actually, there is an error 1112:

```
(base) ed@mikado:~/ParallelIO$ find . -name '*.h'|xargs grep ERR_WRONG
./tests/ncint/pio_err_macros.h:#define ERR_WRONG 99
./tests/cunit/pio_tests.h:#define ERR_WRONG 1112
```

I will define both values of ERR_WRONG to 99.

**Comment by edwardhartnett** [comment]
OK, I have added a new error macro for async tests:

```
/**
 * For async tests, handle non-MPI errors by finalizing the IOsystem
 * and exiting with an exit code.
 */
#define AERR(e) do {                                                     \
        fprintf(stderr, "%d Async Error %d in %s, line %d\n", my_rank, e, __FILE__, __LINE__); \
	PIOc_free_iosystem(iosysid);                                    \
        return e;                                                       \
    } while (0)


```

Then I used this macro in test_darray_async_many.c. Now errors cause the make check to fail.

**Comment by edwardhartnett** [comment]
Still some things to fix in these tests. I'll close this when both are completely fixed.
