### ISSUE TITLE
What is up with really crappy performance from test_async_perf.c?

### ISSUE THREAD

**Issue by edwardhartnett** [NCAR/ParallelIO#1795]
From hera. Yuck.

```
 srun ./test_async_perf
ntasks  nio     rearr   fill    format  time(s) data size (MB)  performance(MB/s)
128     1       1       0       0          1.060             6.0           5.663
128     1       1       0       1          1.027             6.0           5.841
128     1       1       0       2          1.015             6.0           5.911
128     1       1       0       3          1.024             6.0           5.859
128     4       1       0       0          1.069             6.0           5.611
128     4       1       0       1          1.013             6.0           5.920
128     4       1       0       2          1.010             6.0           5.938
128     4       1       0       3          1.020             6.0           5.884
128     16      1       0       0          1.091             6.0           5.498
128     16      1       0       1          1.009             6.0           5.949
128     16      1       0       2          1.010             6.0           5.943
128     16      1       0       3          1.019             6.0           5.889
128     64      1       0       0          1.171             6.0           5.125
128     64      1       0       1          1.009             6.0           5.945
128     64      1       0       2          1.011             6.0           5.932
128     64      1       0       3          1.093             6.0           5.490

```

**Comment by jedwards4b** [comment]
Same test on cheyenne:
ntasks, nio,	rearr,	fill,	IOTYPE,	time(s),	data size(MB),	performance(MB/s)
144,  1,	box,	nofill,	pnetcdf,	   2.509,	  1488.0,	 592.972
144,  1,	box,	nofill,	classic,	   1.805,	  1488.0,	 824.459
144,  1,	box,	nofill,	serial4,	   1.865,	  1488.0,	 797.897
144,  1,	box,	nofill,	parallel4,	   2.226,	  1488.0,	 668.605
144,  1,	subset,	nofill,	pnetcdf,	  12.804,	  1488.0,	 116.215
144,  1,	subset,	nofill,	classic,	  12.158,	  1488.0,	 122.390
144,  1,	subset,	nofill,	serial4,	  12.289,	  1488.0,	 121.084
144,  1,	subset,	nofill,	parallel4,	  12.596,	  1488.0,	 118.131
144,  4,	box,	nofill,	pnetcdf,	   2.274,	  1488.0,	 654.294
144,  4,	box,	nofill,	classic,	   1.877,	  1488.0,	 792.706
144,  4,	box,	nofill,	serial4,	   1.984,	  1488.0,	 749.979
144,  4,	box,	nofill,	parallel4,	   2.384,	  1488.0,	 624.154
144,  4,	subset,	nofill,	pnetcdf,	   3.862,	  1488.0,	 385.301
144,  4,	subset,	nofill,	classic,	   3.801,	  1488.0,	 391.476
144,  4,	subset,	nofill,	serial4,	   4.655,	  1488.0,	 319.635
144,  4,	subset,	nofill,	parallel4,	   4.531,	  1488.0,	 328.427
144,  16,	box,	nofill,	pnetcdf,	   1.734,	  1488.0,	 858.335
144,  16,	box,	nofill,	classic,	   1.747,	  1488.0,	 851.847
144,  16,	box,	nofill,	serial4,	   2.854,	  1488.0,	 521.394
144,  16,	box,	nofill,	parallel4,	   1.975,	  1488.0,	 753.368
144,  16,	subset,	nofill,	pnetcdf,	   2.286,	  1488.0,	 650.900
144,  16,	subset,	nofill,	classic,	   2.337,	  1488.0,	 636.654
144,  16,	subset,	nofill,	serial4,	   3.967,	  1488.0,	 375.051
144,  16,	subset,	nofill,	parallel4,	   2.614,	  1488.0,	 569.160
144,  64,	box,	nofill,	pnetcdf,	   2.015,	  1488.0,	 738.572
144,  64,	box,	nofill,	classic,	   2.779,	  1488.0,	 535.422
144,  64,	box,	nofill,	serial4,	  12.559,	  1488.0,	 118.482
144,  64,	box,	nofill,	parallel4,	   2.320,	  1488.0,	 641.463
144,  64,	subset,	nofill,	pnetcdf,	   3.652,	  1488.0,	 407.459
144,  64,	subset,	nofill,	classic,	   8.594,	  1488.0,	 173.148
144,  64,	subset,	nofill,	serial4,	  19.863,	  1488.0,	  74.915
144,  64,	subset,	nofill,	parallel4,	   4.908,	  1488.0,	 303.175

**Comment by edwardhartnett** [comment]
Thanks! I will use that.

AS you can see the problem was mostly addressed by increasing the size of the data being written. I'm my output above, I was writing 6 MB of data. As you see from your output, I increased the size of the data to a more reasonable 1488 MB, and now we get some more reasonable numbers. I am seeing better results.

BUT, async runs are still not working for me with SUBSET...

**Comment by jedwards4b** [comment]
I don't have access to hera, but I do have an orion account - any chance you can reproduce the problem there?
