### ISSUE TITLE
Test with OMPIO

### ISSUE THREAD

**Issue by jedwards4b** [NCAR/ParallelIO#1814]
We need to test against the OpenMPI IO library:

https://www.open-mpi.org/faq/?category=ompio

**Comment by edwardhartnett** [comment]
We do: https://github.com/NCAR/ParallelIO/blob/master/.github/workflows/a3.yml

This tests with openmpi-4.0.4.

**Comment by jedwards4b** [comment]
Yes, I misunderstood the docs and thought that ompio was still an option but not the default.   We've been testing this for some time.
