### ISSUE TITLE
release version 2.5.3

### ISSUE THREAD

**Issue by edwardhartnett** [NCAR/ParallelIO#1818]
The goal was to release a version in concert with the paper, so that the paper would describe released code. Can we do a release?

**Comment by edwardhartnett** [comment]
@jedwards4b I propose to do a release with the current master.

Any objections?

**Comment by jedwards4b** [comment]
No objections.

**Comment by edwardhartnett** [comment]
OK, lets get this done...

**Comment by jedwards4b** [comment]
Thanks!

**Comment by edwardhartnett** [comment]
Something's wrong with our github ci runs. I'm checking now. It's not our code, because the travis build works fine. Something about the caching on github...
