### ISSUE TITLE
Failed to run the ctest command from a PBS job on OLCF platform

### ISSUE THREAD

**Issue by dqwu** [NCAR/ParallelIO#182]
I submitted a PBS job to run the ctest command on OLCF platform (Eos/Titan) and the job failed:
1/73 Testing: test_darray
Unable to find executable: MPIEXEC-NOTFOUND

Apparently this is because OLCF is not supported by PIO yet. To run the ctest command from a job submission script on OLCF, we can add a new file mpiexec.olcf and modify LibMPI.cmake to use it.

We might also consider adding CDash ctest run scripts for OLCF in the future (create another issue for this feature). This will introduce a few more new files like CTestEnvironment-olcf.cmake, runcdash-olcf-gnu.sh, runcdash-olcf-intel.sh, runctest-olcf.sh

**Comment by jedwards4b** [comment]
I have no objections and we will be glad to advise.

**Comment by Katetc** [comment]
I think that's a great idea. I would be happy to advise if you need help as well.
