### ISSUE TITLE
testing improvements: new pnetcdf, hdf5 versions, netcdf integration

### ISSUE THREAD

**Issue by jedwards4b** [NCAR/ParallelIO#1827]
pnetcdf 1.12.2 is available, we should test with it.

**Comment by edwardhartnett** [comment]
I will add it today...

**Comment by edwardhartnett** [comment]
We can also test with hdf5-1.12.0.

**Comment by edwardhartnett** [comment]
We are not actually testing netcdf integration! I will add tests for that too.
