### ISSUE TITLE
Need to prefill var in pio_darray_read

### ISSUE THREAD

**Issue by jedwards4b** [NCAR/ParallelIO#1834]
@edhartnett do you recall why[ this code ](https://github.com/NCAR/ParallelIO/blob/master/src/clib/pio_darray.c#L963) is commented out?  I think that we need to set the array to the fillvalue here.

**Comment by edwardhartnett** [comment]
Because netcdf already does it?

**Comment by jedwards4b** [comment]
Actually it doesn't in this case, but I'm now thinking that it isn't pio's responsibility either.   The issue is
when a user provides a dof that contains 0 values.  This value in the dof means that pio shouldn't do anything at that location in the array.  The problem comes in when you read from fortran - in the fortran interface pio_read_darray the array variable has intent(out) which means that any values in the array prior to the call may be overwritten.   So the user cannot pre-initialize the array and those values corresponding to the 0's in the dof are uninialized.  I am considering changing the intent on the fortran side to inout so that the user can pre-initialize before reading.

**Comment by edwardhartnett** [comment]
OK, I get it. I did not really understand that about fortran out vs. inout...

**Comment by edwardhartnett** [comment]
@jedwards4b can we close this issue?
