### ISSUE TITLE
Configure missing from directory

### ISSUE THREAD

**Issue by jmalevesque** [NCAR/ParallelIO#1880]

**Comment by edwardhartnett** [comment]
Can you provide more detail?

**Comment by jedwards4b** [comment]
The configure file is not provided in github, if you download a parallelio release tar file you will find it there, otherwise you must use the autotools to generate it.

**Comment by edwardhartnett** [comment]
This is intentional. None of the autotools generated files are stored in the repo. The original source to generate them is stored in the repo - use autoreconf -if after cloning the repo to generate them on your system.
