### ISSUE TITLE
Release version 2.5.5

### ISSUE THREAD

**Issue by edwardhartnett** [NCAR/ParallelIO#1884]
As requested by @jedwards4b we will release version 2.5.5.

Things that have to be done:
* Change version numbers in configure.ac and CMakeLists.txt.
* Generate and update documentation on gh-pages.
* Release notes.
* Start a new GitHub project and draft release notes for 2.5.6.

**Comment by jedwards4b** [comment]
I think that I'll have one more PR today with some cleanup i found with address sanitizer.

**Comment by edwardhartnett** [comment]
We can do this today if you are ready...

**Comment by jedwards4b** [comment]
@edwardhartnett Not quite ready yet.   Have a great Thanksgiving.

**Comment by edwardhartnett** [comment]
OK, that's fine. Let me know when you are ready. I have a version change PR up, which is the first step...

**Comment by jedwards4b** [comment]
Released
