### ISSUE TITLE
PIO 2.5.4 and NetCDF-4.8.1 (HDF5-1.12.1)

### ISSUE THREAD

**Issue by rjdave** [NCAR/ParallelIO#1889]
I have not tried auto-tools, but cmake (v3.19.1) configure fails with NetCDF-4.8.1 because `NC_DISPATCH_VERSION` has changed from 2 to 3 in the latest release. I changed line 369 in `CMakeLists.txt` to:

`#if !(NC_DISPATCH_VERSION == 2 || NC_DISPATCH_VERSION == 3)`

and configure completed and make, make tests completed but I get 7 failed tests with ctest:

```
The following tests FAILED:
         43 - pio_file_fail (Timeout)
        104 - tst_async_multi (Failed)
        105 - tst_ncint_async_perf (Failed)
        106 - tst_ncint_perf (Failed)
        107 - tst_pio_async (Failed)
        108 - tst_pio_udf (Failed)
        109 - tst_var_compress (Failed)
```

 I found this [pull request](https://github.com/Unidata/netcdf-c/pull/1945) and this [issue](https://github.com/Unidata/netcdf-c/issues/1924) about `NC_DISPATCH_VERSION` so I'm betting you already know some changes (possibly to `src/ncint/ncintdispatch.{c&h}`) are probably necessary to account for the switch from `filter_actions` to `filter_ids` and `filter_info`. Unfortunately, I don't know nearly enough about filters or dispatch tables to help much.

**Comment by jedwards4b** [comment]
@edwardhartnett Can you help with this issue?

**Comment by edwardhartnett** [comment]
Try building PIO without the --enable-netcdf-integration and see if that works...

**Comment by jedwards4b** [comment]
@edwardhartnett that does work, the issue is supporting the NC_DISPATCH_VERSION=3

**Comment by jedwards4b** [comment]
@edwardhartnett I would like to make a new PIO tag - any chance we can make NC_DISPATCH_VERSION=3
work before I do that?   Thanks.

**Comment by jedwards4b** [comment]
Resolved
