### ISSUE TITLE
add support for quantize functions

### ISSUE THREAD

**Issue by edwardhartnett** [NCAR/ParallelIO#1898]
netcdf-c now has (in master branch) nc_def_var_quantize()/nc_inq_var_quantize(), allowing users to set a significant number of digits for a float/double, and discard uneeded bits, making compression much better. (That is - lossy compression.)

I need to add the functions to PIO to call the C functions in netcdf-c. Fortunately they are dead simple.

**Comment by jedwards4b** [comment]
Been done for some time.
