### ISSUE TITLE
Spack installation error

### ISSUE THREAD

**Issue by EnricoDeg** [NCAR/ParallelIO#1903]
Hello,

I tried to install PIO using Spack and I get the following output/error:
```
==> Installing parallelio-2_5_4-tde3st2vsurgp3rmhgksaphtkkuuk2na
==> No binary for parallelio-2_5_4-tde3st2vsurgp3rmhgksaphtkkuuk2na found: installing from source
==> Fetching https://mirror.spack.io/_source-cache/archive/e5/e51dc71683da808a714deddc1a80c2650ce847110383e42f1710f3ba567e7a65.tar.gz
==> Error: FetchError: All fetchers failed for resource-CMake_Fortran_utils-tde3st2vsurgp3rmhgksaphtkkuuk2na

/sw/spack-workplace/spack/lib/spack/spack/package.py:1386, in do_fetch:
       1383
       1384        self.stage.create()
       1385        err_msg = None if not self.manual_download else self.download_instr
  >>   1386        start_time = time.time()
       1387        self.stage.fetch(mirror_only, err_msg=err_msg)
       1388        self._fetch_time = time.time() - start_time
       1389
```
I enabled `pnetcdf` option (variant) and I set the following dependencies:
 - `openmpi@4.1.2`
 - `netcdf-c@4.8.1`
 - `parallel-netcdf@1.12.2`

Have you seen this error before?

**Comment by EnricoDeg** [comment]
Ah okay, I see. PIO is available on Spack (package name: `parallelio`) and I was thinking it was integrated by the developers. If this is not the case and the integration is buggy, this is not a problem and it is good to know. I haven't done anything specific, just tried to install the library with Spack as a user. Thanks for the quick answer.

**Comment by jedwards4b** [comment]
Spack 'parallelio" package:
maintainers = ['tkameyama']

**Comment by jedwards4b** [comment]
I have taken over maintainence of parallelio in spack and have resolved this issue.
