### ISSUE TITLE
./configure.ac: line 5: syntax error near unexpected token `pio,'

### ISSUE THREAD

**Issue by mayavy** [NCAR/ParallelIO#1909]
I cloned master branch on my HPC(centos) . (for MPAS-A ver-7)
set up env as in instructions .
than ran ./configure.ac --prefix=/usr/local/pio-2.4.2 --enable-fortran
got this
./configure.ac: line 5: syntax error near unexpected token `pio,'
./configure.ac: line 5: `AC_INIT(pio, 2.5.5)'

*********
<img width="478" alt="bug" src="https://user-images.githubusercontent.com/96287842/155889236-a1fc165d-ba52-4504-ae1c-63ab5f948861.png">

**Comment by edwardhartnett** [comment]
When checking code out of the repo do this:

```
autoreconf -i
./configure --prefix=/whatever
make -j check
```

You did not run autoreconf -i...

**Comment by Syize** [comment]
This issue was opened 2 years ago, and the [Building PIO](https://github.com/NCAR/ParallelIO?tab=readme-ov-file#building-pio) section in README is still missing the command `autoreconf -i` before `./configure`
