### ISSUE TITLE
Incorrect minimum supported CMake version

### ISSUE THREAD

**Issue by ckhroulev** [NCAR/ParallelIO#1919]
`cmake_minimum_required (VERSION 2.8.12)` in `CMakeLists.txt` appears to be wrong: `src/clib/CMakeLists.txt` uses `string(APPEND ...)`, which was added in CMake 3.4 (see https://cmake.org/cmake/help/v3.4/command/string.html).

**Comment by jedwards4b** [comment]
Thanks for pointing this out.  I have changed the minimum version to 3.9.1 based on the oldest version I have easy access to and can test.

**Comment by ckhroulev** [comment]
@jedwards4b Thanks!
