### ISSUE TITLE
decomp tests failing on cdash

### ISSUE THREAD

**Issue by edhartnett** [NCAR/ParallelIO#192]
*Tests failing* (first 5)
pio_decomp_tests_2d_4p_2iop_2str (http://my.cdash.org/testDetails.php?test=28218303&build=1081961)
pio_decomp_tests_3d_4p_2agg (http://my.cdash.org/testDetails.php?test=28218310&build=1081961)
pio_decomp_tests_3d_4p_2iop (http://my.cdash.org/testDetails.php?test=28218314&build=1081961)
pio_decomp_frame_tests (http://my.cdash.org/testDetails.php?test=28218319&build=1081961)
pio_decomp_tests_3d_3p (http://my.cdash.org/testDetails.php?test=28232692&build=1081961)

**Comment by jayeshkrishna** [comment]
As I mentioned before, I don't have access to the NCAR machines ( @jedwards4b should I apply for access to these machines). Someone else might have to take a look at it.

**Comment by jayeshkrishna** [comment]
But these error messages looks like the netcdf4p hang with the box rearranger that I saw before (Upgrading the netcdf libs to the latest version solved the issue). See PR #162

**Comment by jedwards4b** [comment]
I am looking into it.

**Comment by jedwards4b** [comment]
I'm still getting this error with netcdf 4.4.0, it's hanging if a task enters the call nc_get_vara_int with count[0]=0.   I think that the problem is probably with the hdf5 that netcdf is built against.  Mine is 
1.8.16 @jayeshkrishna what hdf5 are you using?

**Comment by jedwards4b** [comment]
It looks like the variables with count = 0 are returning from the hdf5 layer while the variables with non-zero counts are calling an allreduce in H5D__mpio_opt_possible

**Comment by jayeshkrishna** [comment]
I am using hdf5 1.8.16 too.

**Comment by jayeshkrishna** [comment]
The netcdf C version is 4.4.1

**Comment by jedwards4b** [comment]
Thanks - I found a reference to this issue in the netcdf revision notes for 4.4.1 - I've requested a new install to get up to the latest version.

**Comment by edhartnett** [comment]
Should this issue be closed? These tests seem to work now...
