### ISSUE TITLE
pio 2.5.8 not listed as a release 

### ISSUE THREAD

**Issue by jedwards4b** [NCAR/ParallelIO#1933]
I messed something up.  The tag is here https://github.com/NCAR/ParallelIO/archive/refs/tags/pio2_5_8.tar.gz
but it's not listed as a release.

**Comment by edhartnett** [comment]
Don't tag do a release on GitHub...

**Comment by edwardhartnett** [comment]
I have drafted release notes. Fill in the section: New This Release...

**Comment by jedwards4b** [comment]
Thanks,
