### ISSUE TITLE
Add PIO to conda packages

### ISSUE THREAD

**Issue by apcraig** [NCAR/ParallelIO#1939]
It would be really helpful if PIO were available on conda-forge or similar.  Just a suggestion/request.  Thanks!

**Comment by edwardhartnett** [comment]
Agreed, but we have zero staffing at the moment. ;-) So is it possible that you could do this?

**Comment by apcraig** [comment]
Thanks @edwardhartnett, totally understand.  I'm no expert but will look into it if I have some time.  Happy for others to provide assistance or suggest ideas/advice/guidance on how to best proceed.

**Comment by jedwards4b** [comment]
@apcraig PIO is available in spack as parallelio.   There is also an[ open PR](https://github.com/conda-forge/staged-recipes/pull/20231) in conda-forge.

**Comment by apcraig** [comment]
Excellent, thank you @jedwards4b.

**Comment by xylar** [comment]
@apcraig, I've been working on this for awhile.  Hopefully, it will happen soon.  This would be helpful for the updated ESMF package, too (my main motivation at the moment).

**Comment by jedwards4b** [comment]
Not to discourage too much from using conda, but spack has esmf as well as parallelio.

**Comment by xylar** [comment]
@jedwards4b, yes! We use each in different contexts. If folks want esnf for their laptops, spack is waaay overkill. But for HPC, conda is definitely only the backup option (e.g. for running in serial on login nodes).
