### ISSUE TITLE
Installation error for installing ParallelIO

### ISSUE THREAD

**Issue by MuzafarWani** [NCAR/ParallelIO#1942]
I am trying to install PIO version 2_5_9. When I try to install I am getting error 

Could NOT find NetCDF_Fortran (missing: NetCDF_Fortran_LIBRARY
  NetCDF_Fortran_INCLUDE_DIR)

I have installed netcdf and pnetcdf libraries and environment variables are pointing to the installation directory of both.
[CMakeOutput.txt](https://github.com/NCAR/ParallelIO/files/10163463/CMakeOutput.txt)

**Comment by MuzafarWani** [comment]
I also later installed netcdf-fortan from  unidata.ucar.edu/pub/netcdf/netcdf-fortran-4.4.4.tar.gz but still the same issue

**Comment by jedwards4b** [comment]
Did you install netcdf-fortran in the same directory or a different one?   Are you using the autoconf or the cmake build system?

**Comment by MuzafarWani** [comment]
I installed netcdf-fortran in below directories

/home/muzafar/installs/netcdf-c
/home/muzafar/installs/netcdf-f

I am using cmake

**Comment by jedwards4b** [comment]
add these arguments to cmake -DNetCDF_C_LIBRARY=/home/muzafar/installs/netcdf-c/lib -DNetCDF_C_INCLUDE_DIR=/home/muzafar/installs/netcdf-c/include -DNetCDF_Fortran_LIBRARY=/home/muzafar/installs/netcdf-f/lib -DNetCDF_Fortran_INCLUDE_DIR=/home/muzafar/installs/netcdf-f/include

**Comment by MuzafarWani** [comment]
by cmake you mean CMake_Lists.txt or somewhere else?

**Comment by MuzafarWani** [comment]
cmake went fine but now make is giving 
Cannot open module file ‘mpi.mod’ for reading at (1): No such file or directory
mpi.mod is present in mpi install. How do I pass that as parameter

**Comment by MuzafarWani** [comment]
Yes. I have cmake already that way.
Should I pass the location of the mpi.mod as parameter

**Comment by MuzafarWani** [comment]
The last part you have mentioned "/path/to/parallelio/" which path is this. Is this where PIO will be installed or the path to the source

**Comment by jedwards4b** [comment]
It's a path to the source.   If you already have the cmake command line that way then make sure that mpi.mod exists in your mpi.  If it does you can add -DCMAKE_Fortran_FLAGS=-I/path/to/mpi/include

**Comment by jedwards4b** [comment]
Try using  -DCMAKE_CPP_FLAGS=-I/path/to/mpi/include instead.

**Comment by MuzafarWani** [comment]
Still showing the same error.
Cmake is generating the warning

CMake Warning:
  Manually-specified variables were not used by the project:

    CMAKE_CPP_FLAGS

**Comment by jedwards4b** [comment]
Then you will need both; -DCMAKE_C_FLAGS=-I/path/to/mpi/include -DCMAKE_Fortran_FLAGS=-I/path/to/mpi/include

**Comment by MuzafarWani** [comment]
-- Could NOT find MPI_C (missing: MPI_C_WORKS) 
CMake Error at /usr/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:146 (message):
  Could NOT find MPI (missing: MPI_C_FOUND) (found version "3.1")
Call Stack (most recent call first):
  /usr/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:393 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-3.16/Modules/FindMPI.cmake:1688 (find_package_handle_standard_args)
  CMakeLists.txt:172 (find_package)

**Comment by jedwards4b** [comment]
Please post the complete cmake command line you are attempting or maybe you should try the autoconf build method?

**Comment by MuzafarWani** [comment]
How to use autoconf command?

**Comment by jedwards4b** [comment]
To use autoconf run autoreconf -i from the top level directory.  
Then ./configure --help will give you a list of options.
 But I think that something about your system is messed up for this error to occur.   You may want to consult with your local system administrators.

**Comment by jedwards4b** [comment]
The instructions here are clear are they not? :  Pnetcdf not found. Set CPPFLAGS/LDFLAGS or use --disable-pnetcdf.
