### ISSUE TITLE
Conda versions of parallelio being built without PNetcdf support

### ISSUE THREAD

**Issue by nickheavens-cgg** [NCAR/ParallelIO#1966]
After a long struggle to figure out why I couldn't get MPAS-A to run with the default PNetcdf I/O but successfully with Netcdf-3 serial I/O, I have determined that the ultimate issue is that the conda version of parallelio I am using was built without PNetcdf support, as below. 2.5.10 is similar. I cannot figure out who is uploading this package; it's coming out of a general Conda pipeline account, but I would humbly request that they would build ParallelIO with such functionality, so that it doesn't break the default input/output mechanism in MPAS. 

> # PIO Configuration Summary
==============================

# General
-------
PIO Version:            2.6.0
Configured On:          Fri May 19 13:18:37 UTC 2023
Host System:            x86_64-Linux-5.15.0-1037-azure
Build Directory:        /home/conda/feedstock_root/build_artifacts/parallelio_1684502184942/work/build
Install Prefix:         /home/nheavens/.conda/envs/mpas_test3

# Compiling Options
-----------------
C Compiler:             GNU 12.2.0
CFLAGS:                 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /home/nheavens/.conda/envs/mpas_test3/include -fdebug-prefix-map=/home/conda/feedstock_root/build_artifacts/parallelio_1
684502184942/work=/usr/local/src/conda/parallelio-2.6.0 -fdebug-prefix-map=/home/nheavens/.conda/envs/mpas_test3=/usr/local/src/conda-prefix -std=gnu99  
CPPFLAGS:                -DLINUX -DCPRGNU -DLOGGING -I/home/conda/feedstock_root/build_artifacts/parallelio_1684502184942/work/build -I/home/conda/feedstock_root/build_artifacts/parallelio_1684502184942/work/src/clib -I/home/conda/feedstock_root/build_artifacts/paralle
lio_1684502184942/work/build/src/clib -I/home/conda/feedstock_root/build_artifacts/parallelio_1684502184942/work/src/clib -I/home/conda/feedstock_root/build_artifacts/parallelio_1684502184942/work/src/clib/../ncint -I/home/nheavens/.conda/envs/mpas_test3/include
LDFLAGS:                -Wl,-O2 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now -Wl,--disable-new-dtags -Wl,--gc-sections -Wl,--allow-shlib-undefined -Wl,-rpath,/home/nheavens/.conda/envs/mpas_test3/lib -Wl,-rpath-link,/home/nheavens/.conda/envs/mpas_test3/li
b -L/home/nheavens/.conda/envs/mpas_test3/lib 
Shared Library:         yes
Static Library:         no
Extra libraries:

Fortran Compiler:       GNU 12.2.0
FFLAGS:                 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /home/nheavens/.conda/envs/mpas_test3/include -fdebug-prefix-map=/home/conda/feedstock_root/build_artifacts/parallelio_1
684502184942/work=/usr/local/src/conda/parallelio-2.6.0 -fdebug-prefix-map=/home/nheavens/.conda/envs/mpas_test3=/usr/local/src/conda-prefix -fallow-argument-mismatch
FCFLAGS:                
More Fortran Flags:      -DLINUX -DCPRGNU -DNO_C_SIZEOF -I/home/conda/feedstock_root/build_artifacts/parallelio_1684502184942/work/build -I/home/conda/feedstock_root/build_artifacts/parallelio_1684502184942/work/src/flib -I/home/conda/feedstock_root/build_artifacts/par
allelio_1684502184942/work/build/src/flib -I/home/nheavens/.conda/envs/mpas_test3/include

# Features
--------
PnetCDF Support:        no
SZIP Write Support:     no
Parallel Filters:       yes
NetCDF/HDF5 Support:    yes
NetCDF/HDF5 Par I/O:    yes
NetCDF Integration:     no
PIO Logging:            no
MPIEXEC:                mpiexec
Fortran:                yes

**Comment by jedwards4b** [comment]
I have opened an issue on the conda-forge page.  https://github.com/conda-forge/parallelio-feedstock/issues/14
Note that parallelio is also in spack and can be built with pnetcdf support there.

**Comment by jedwards4b** [comment]
Resolved
