### ISSUE TITLE
Disabling GPTL timing support at run time

### ISSUE THREAD

**Issue by uturuncoglu** [NCAR/ParallelIO#1967]
I am working on CMCC WRF coupling and it seems that PIO is installed with GPTL timing support. Since I am using ESMX generic driver to couple WRF with DOCN (CDEPS), I have no way to ingest GPTL init call to the driver (at least in the version of ESMF that I am using). As a result, I am getting following errors from run (coming from CDEPS),

[1] GPTLstart name=PIO:rearrange_io2comp: GPTLinitialize has not been called
[0] GPTLstart name=PIO:read_darray_nc: GPTLinitialize has not been called
[0] GPTLstop: GPTLinitialize has not been called
[0] GPTLstart name=PIO:rearrange_io2comp: GPTLinitialize has not been called
[35] GPTLstop: GPTLinitialize has not been called

I think it would be nice to have way to turn GPTL timing off by providing environment variable or configuration option to PIO even if it is build with timing support.

**Comment by jedwards4b** [comment]
Note that these are warnings and not errors and although they are annoying they should not impede the performance or functionality of pio.

**Comment by uturuncoglu** [comment]
In my case, the code is crashing. Maybe it is because of something else. Let me double check.

**Comment by uturuncoglu** [comment]
I think you are right. It seems that the code is failing in CDEPS since it complains about the input file. I fixed in my side.

**Comment by uturuncoglu** [comment]
@jedwards4b Sure. We could close this. Thanks for your help.
