### ISSUE TITLE
PIO_createfile documentation

### ISSUE THREAD

**Issue by anton-seaice** [NCAR/ParallelIO#1976]
I think the doco for this line in PIO_createfile is wrong https://github.com/NCAR/ParallelIO/blob/76c40a7855c99403bfd9e3dee9062c7fe58b4391/src/flib/piolib_mod.F90#L1346-L1347

Valid options should be those related to creating a file, i.e. : PIO_CLOBBER, PIO_NOCLOBBER, PIO_64BIT_OFFSET, PIO_64BIT_DATA

**Comment by jedwards4b** [comment]
Thank you! https://github.com/NCAR/ParallelIO/pull/1977
