### ISSUE TITLE
PIO example run issue

### ISSUE THREAD

**Issue by Arunipm** [NCAR/ParallelIO#1983]
Hell All,
I am very new to PIO library.
I would like to run a example examplePio.F90/examplePio.c but did not get success.
Could somebody please tell me the correct procedure to run a PIO example !

Thanks & Regards
Arun

**Comment by Arunipm** [comment]
Hi Jim,
Thank you for your detailed answer.
I have already installed PIO-2.5.9 successfully.
Actually, I would like to compile and run an example such as examplePio.F90 or examplePio.c, separately. 
Is it possible to run the command **_mpif90 examplePio.F90_**  and get corresponding binary version of the program ? so that I can run it with _**mpirun**_.
What environment variables or compilers I need to set for it ?
I am interested in modifying the content of examplePio.F90 and perform some tests.

Thanks & Regards
Arun

**Comment by jedwards4b** [comment]
I recommend updating to pio.2.6.2 first.  Then after following the build instructions above you may build the examples using
make <target> where target may be exampleAsyncPio_f90 or examplePio_f90

If you want to use the examples with a spack installed version of PIO then you would need to create a Makefile with:
```
FC = 
PIO_PATH =
NETCDF_PATH=
PNETCDF_PATH=
FFLAGS = -I$(PIO_PATH)/include -I$(NETCDF_PATH)/include -I$(PNETCDF_PATH)/include 

LIBS = -L$(NETCDF_PATH)/lib -lnetcdff -lnetcdf -L$(PNETCDF_PATH)/lib -lpnetcdf -L$(PIO_PATH)/lib -lpiof -lpioc 

examplePio_f90: examplePio.F90
     $(FC) $(FFLAGS) -o $@ $< $(LIBS)
```
Filling in the blanks as appropriate for your system.

**Comment by Arunipm** [comment]
Thank you very much.
I am able to run the example now.
