### ISSUE TITLE
fail to build nco 

### ISSUE THREAD

**Issue by 1301970063** [NCAR/ParallelIO#1992]
### pwd:/data1/home/songrj/WRF_MODEL/Tar/nco-4.7.6/src/nco++/makefile

CXX = icpc
CXXCPP = icpc -E
CXXDEPMODE = depmode=gcc3
CXXFLAGS = -O3 -fPIC -ip -no-prec-div -cxxlib-gcc
CYGPATH_W = echo

make[3]: Leaving directory `/data1/home/songrj/WRF_MODEL/Tar/nco-4.7.6/src/nco_c++'
Making all in nco++
make[3]: Entering directory `/data1/home/songrj/WRF_MODEL/Tar/nco-4.7.6/src/nco++'
icpc -DHAVE_CONFIG_H -I. -I../..  -I./ -I../nco -I/data1/home/songrj/WRF_NOAH/LIBRARY/netcdf/include -I/data1/home/songrj/WRF_NOAH/LIBRARY/hdf5/include -I/data1/home/songrj/WRF_NOAH/LIBRARY/netcdf/include -I/data1/home/songrj/WRF_NOAH/LIBRARY/netcdf/include -O3 -fPIC -ip -no-prec-div  -I/data1/home/songrj/WRF_NOAH/LIBRARY/udunits/include -D_BSD_SOURCE -D_POSIX_SOURCE  -O3 -fPIC -ip -no-prec-div -cxxlib-gcc -MT Invoke.o -MD -MP -MF .deps/Invoke.Tpo -c -o Invoke.o Invoke.cc
icpc: command line remark #10148: option '-cxxlib-gcc' not supported
Invoke.cc(11): catastrophic error: cannot open source file "antlr/AST.hpp"
  #include <antlr/AST.hpp>

**Comment by jedwards4b** [comment]
Hi - thank you for reporting this issue.  It is not however a PIO issue.  It appears to be a WRF model issue.  Please report here: https://github.com/wrf-model/WRF/issues
