### ISSUE TITLE
cmake cache issue

### ISSUE THREAD

**Issue by jedwards4b** [NCAR/ParallelIO#2]
If you attempt a build and cmake can't find netcdf and/or pnetcdf the -D_NONETCDF flag is cached
you cannot currently repeat the cmake command without first removing the cache file.   Can we correct this?

**Comment by kmpaul** [comment]
I don't know if its possible to do this in a reliable fashion.  This is exactly what the cmake cache is designed to do.  There are options to the "set()" command, such as CACHE and FORCE, that can be used together to force a user variable to be caches and reset every time that "cmake" is run.  However, this doesn't necessarily work the way we need it to work.  This will force the variable to be set and saved in the cache regardless of what the user specifies on the command line.

I think the only way to get cmake to ignore the cache is to erase it.

**Comment by jedwards4b** [comment]
I think that this is a non-issue.
