### ISSUE TITLE
pnetcdf 1.8.0 pre1

### ISSUE THREAD

**Issue by jedwards4b** [NCAR/ParallelIO#202]
We should test this with pio and send feedback...

Hello to the PnetCDF community,

A new preview release of Parallel-netCDF 1.8.0.pre1, is now available for download.
This preview release is for the 1.8.0 release. We are sincerely soliciting
feedbacks from the PnetCDF community for this test release. The tar balls can
be downloaded from:
http://cucis.ece.northwestern.edu/projects/PnetCDF/download.html

Below is a brief list of noticeable changes.
1. Two new configure options were added: --disable-erange-fill and
   --enable-relax-coord-bound. The former is to disable the new, now default,
   feature that uses a variable's fill value for data elements that cause
   NC_ERANGE error and the latter is to enable a more relaxed boundary check
   for argument start in all APIs.
2. Use a hash function for checking whether the name of a variable or dimension
   has already been used.
3. Added pnetcdf-config shell script to display the options used in building
   PnetCDF.
4. Consistency check for header data has been moved to individual APIs and
   the check is only enabled when safe mode is on.

For detailed changes from the previous release can be found in
http://trac.mcs.anl.gov/projects/parallel-netcdf/browser/tags/v1-8-0pre1/sneak_peek

Regards,
Wei-keng Liao and The PnetCDF Team

**Comment by edhartnett** [comment]
I just added pnetcdf-1.8.1 to my development machine. I am adding jenkins tests for it now (in addition to the existing tests, which use 1.7.0.)

I will report on any problems I encounter.

**Comment by edhartnett** [comment]
All my jenkins runs passed.

There are some pnetcdf bugs relating to fill values in 1.7.0. If 1.8.1 has fixed these problems, that will be great.

I am going to close this ticket.
