### ISSUE TITLE
C tests can't really handle more than 4 tasks...

### ISSUE THREAD

**Issue by edhartnett** [NCAR/ParallelIO#211]
The C tests are supposed to be written so that more than the specified number of tasks can be used.

But in fact, when I run a 4-task test with 6 processors, it hangs at the end of the test and does not return.

**Comment by jedwards4b** [comment]
Which test?  This was tested and working.

**Comment by edhartnett** [comment]
It fails for me on master for test_nc4, test_names, test_darray, 

Instead of the expected output, I get:

[ed@mikado unit]$ mpiexec -n 6 ./test_darray
4 test_darray finalizing...
5 test_darray finalizing...
  C-c C-c[mpiexec@mikado] Sending Ctrl-C to processes as requested
[mpiexec@mikado] Press Ctrl-C again to force abort
[ed@mikado unit]$ mpiexec -n 6 ./test_nc4
4 test_nc4 waiting for all processes!
5 test_nc4 waiting for all processes!
4 test_nc4 Finalizing...
5 test_nc4 Finalizing...
  C-c C-c[mpiexec@mikado] Sending Ctrl-C to processes as requested
[mpiexec@mikado] Press Ctrl-C again to force abort
[ed@mikado unit]$ 

I have to break because it hangs.

This may be a change I made, in which case I should fix it. In any case, I will add a test.

This may also be a system problem. I just built and installed everything on this system, and it could be something there. I have been having some strange troubles with MPICH.

**Comment by jedwards4b** [comment]
There is a lot of red on the cdash board - looks like one of the recent commits broke everything.

**Comment by edhartnett** [comment]
Looks like a HDF5 config issue:

 0:Warning! ***HDF5 library version mismatched error***
   0:The HDF5 header files used to compile this application do not match
   0:the version used by the HDF5 library to which this application is linked.

Could it be that HDF5 was recently updated on these machines?

I don't think the HDF5 compile issue is related to the issue of tests running on more than 4 tasks.

**Comment by Katetc** [comment]
On Hobart, it is an mpi error at the very end of the test (all tests pass successfully and then: 1] 16 at [0x00000000025ff628], src/util/procmap/local_proc.c[92]
[1] 504 at [0x00000000025fedf8], src/mpi/comm/commutil.c[337]
[1] 504 at [0x00000000025fe8b8], src/mpi/comm/commutil.c[337]
[1] 56 at [0x00000000025fe168], src/mpid/ch3/src/mpid_vc.c[132]
[mpiexec@h020.cgd.ucar.edu] HYDT_bscd_pbs_wait_for_completion (tools/bootstrap/external/pbs_wait.c:67): tm_poll(obit_event) failed with TM error 17002
[mpiexec@h020.cgd.ucar.edu] HYDT_bsci_wait_for_completion (tools/bootstrap/src/bsci_wait.c:23): launcher returned error waiting for completion
[mpiexec@h020.cgd.ucar.edu] HYD_pmci_wait_for_completion (pm/pmiserv/pmiserv_pmci.c:218): launcher returned error waiting for completion
[mpiexec@h020.cgd.ucar.edu] main (ui/mpich/mpiexec.c:344): process manager error waiting for completion

Which is basically the same floating error as in #172 , so may not be related to other errors.

The two serial tests on Yellowstone that are failing (test_nc4 and tes_names) both have this error:
ERROR: Number of processors must be at least 4 for this test!
0 Error 1110 in /glade/u/home/jedwards/dashboard/src/tests/unit/test_nc4.c, line 100
This started on Tuesday, Nov 15

The other Yellowstone test failures went from 32 to 69 fails on Thursday morning, Nov 17. These have the HDF5 errors Ed was talking about above.

**Comment by Katetc** [comment]
I tried a full clean checkout and build on Yellowstone to ensure there isn't any cached HDF5 library information causing problems with the nightlies. Still got the same error about mis-matched headers in the library. Should we send a ticket to CISL?

**Comment by edhartnett** [comment]
Did we change the LD_LIBRARY_PATH anywhere recently?

**Comment by Katetc** [comment]
As far as I know, we never set LD_LIBRARY_PATH. That's handled by the Yellowstone modules, isn't it?

**Comment by edhartnett** [comment]
The LD_LIBRARY_PATH is set somewhere, and is the path that is searched for
shared libraries.

What can cause the problem we are seeing is a mismatch between the include
directory (which is where .h files are found, and is specified on the
compile command line with a -I option), and the LD_LIBRARY_PATH.

There are two versions of HDF5 installed. THe include files are from one,
the LD_LIBRARY_PATH is finding the other version first when it comes time
to load the libraries.

So if you did not install HDF5 on this machine (I know I did not), then I
guess you have to ask the people who did install it.

Recently weren't there some changes in the ctest files? Could those account
for this?

Ed

**Comment by jayeshkrishna** [comment]
Not sure if this is related, but @dqwu found some issues related to CMake+linking/searching_of_wrong_version_of_io_libs on Eos.

@dqwu : Did you already create an issue for this case on github?

**Comment by jedwards4b** [comment]
I believe that the problems on yellowstone are due to the system support group messing up modules on that machine.   I am working with them to straighten it out.

**Comment by dqwu** [comment]
CMake does have some strange behaviors on Eos and I will create an issue later, but that might not be related to #211.

On Cray environment dynamic linking is not preferred. On Eos, we tried to build PIO with netcdf 4.4.1 but ldd shows it is linked to netcdf 4.40 shared library.

Could you try building pure static tests (use -DPREFER_STATIC=TRUE for cmake) and see what the result is? This way, LD_LIBRARY_PATH will not be an issue as the built executables are static.

**Comment by jedwards4b** [comment]
Support has repaired module issues - all tests now passing for intel on yellowstone.

**Comment by jedwards4b** [comment]
yellowstone pgi now working.
