### ISSUE TITLE
Check if unlimdim exists in a file.   

### ISSUE THREAD

**Issue by jedwards4b** [NCAR/ParallelIO#22]
@douglasjacobsen reports that in pio1.7.2 checking if the unlimited dimension exists in a file
does not return PIO_EBADID as expected.   

Can we verify if this is the case in the latest pio1_0 and pio2?   

The test would be to open a file which does not have an unlimited dimension and
ierr = pio_inquire(File, UnLimDimid=unlimdimid)
The expected result is ierr = PIO_EBADID.

**Comment by jedwards4b** [comment]
I tried this with a straight netcdf program:
program nctest
  use netcdf
  implicit none
  integer :: ierr, nfid, unlimdimid  

  ierr = nf90_open('piotest_netcdf.nc', NF90_NOWRITE, nfid);
  ierr = nf90_inquire(nfid, unlimitedDimId = unlimdimid)
  print *,__FILE__,__LINE__,ierr, unlimdimid
end 

It also does not return an error.  Is this expected @edhartnett ?

**Comment by jedwards4b** [comment]
Resolved in latest master

**Comment by edhartnett** [comment]
Howdy Jim! I didn't see this issue the first time around, but I'm puzzled too. I would have expected netcdf to return an error in this case.

What was the resolution?

**Comment by jedwards4b** [comment]
It was an issue on the fortran c interface, when i get a dimension id back
from c I add 1 to it for the fortran,
when unlimdimid was returning -1 for not found, I was adding one anyway.
So the solution is to add 1 to the dim
only if dim >= 0.

On Thu, Feb 4, 2016 at 1:42 PM, Imperial Fleet Commander Tarth <
notifications@github.com> wrote:

> Howdy Jim! I didn't see this issue the first time around, but I'm puzzled
> too. I would have expected netcdf to return an error in this case.
>
> What was the resolution?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NCAR/ParallelIO/issues/22#issuecomment-180038984>.
>



-- 
Jim Edwards

CESM Software Engineer
National Center for Atmospheric Research
Boulder, CO

**Comment by edhartnett** [comment]
Hah! Thanks for satisfying my curiosity. ;-)
