### ISSUE TITLE
Resolve inconsistent error handling in C library

### ISSUE THREAD

**Issue by edhartnett** [NCAR/ParallelIO#225]
The C code responds to errors in a variety of ways, and we should settle on the best way, and use it everywhere.

Some of the ways currently in use:
* Ignore return codes - for some calls we ignore the result.
* Return error code - good in normal C library, but sometimes causes one or more tasks to hang and program has to time out.
* Print error message and continue - error messages are helpful and need to be preserved, but we should not continue after error.

Our requirements:
* Code must stop and return error as soon as an error is detected.
* Sensible error messages are provided to users.
* PIO error handler for file is followed, if error occurs on file access.
* PIO default error handler is followed, if error occurs before file is open. (?)
* We must handle 3 kinds of errors: netCDF, MPI, and PIO.

What should we do?

Here's an example for MPI Calls:
```
    int mpierr;  /* Return code from MPI functions. */    

        if ((mpierr = MPI_Alltoallw(sendbuf, sendcounts, sdispls, sendtypes, recvbuf,
                                    recvcounts, rdispls, recvtypes, comm)))
            return check_mpi(NULL, mpierr, __FILE__, __LINE__);


```

The first parameter of check_mpi() (NULL in the code above), is the file pointer, or NULL if there is none available.

The check_mpi function will print an MPI error message, then call check_netcdf with the error code PIO_EIO. This will consult the error handler set for the file (if there is a file). The error handler may call MPI_Abort() and end everything.

The PIO_EIO error code is then returned to the calling program (if MPI abort was not called by the error handler).

Here's what I am doing for netCDF error codes:

```
    /* Broadcast and check the return code. */
    if ((mpierr = MPI_Bcast(&ierr, 1, MPI_INT, ios->ioroot, ios->my_comm)))
        return check_mpi(file, mpierr, __FILE__, __LINE__);
    if (ierr)
        return check_netcdf(file, ierr, __FILE__, __LINE__);

```
In this case ierr is the return code. I broadcast it to all tasks (from ioroot), and the all tasks can call check_netcdf() if ierr is not zero.

**Comment by edhartnett** [comment]
For the errors that are neither MPI nor netCDF errors, we do error handling inconsistently. Sometimes we return an error code:

  ```
  /* Find the info about this file. */
    if ((ierr = pio_get_file(ncid, &file)))
        return ierr;
```

This is not correct because it does not consult the user error handler for the file/iosystem. The error handler may specify PIO_INTERNAL_ERROR, which is supposed to cause an abort.

Other times we use piodie():

    ```
/* Check inputs. */
    if (!ndims || !gdims || !fmaplen || !map)
        piodie("Invalid arg ",  __FILE__, __LINE__);
```

This is also not correct, because the user may have set error handling to PIO_RETURN_ERROR, which means the error code should be returned.

And I don't understand what the third error handler is supposed to do:

```
    /** Error codes are broadcast to all tasks. */
    PIO_BCAST_ERROR = (-52),

```

Does that mean that with an async setup, with multiple computation components, that ALL components will hear about an error in any of them?

I think the way forward is to introduce a new function called pio_err(). It will check the error handling and either call piodie() to abort, or return an error code, or so whatever PIO_BCAST_ERROR should do.

Then I will change all existing return statement whcih are PIO errors, and change them to call pio_err().

Comments welcome.

**Comment by jedwards4b** [comment]
There are three error modes in PIO which can be set by the user 
PIO_BCAST_ERROR, PIO_INTERNAL_ERROR, PIO_RETURN_ERROR 

The default setting is PIO_INTERNAL_ERROR which, if an error occurs 
will report the error on the tasks on which it occurs and abort those tasks without returning to the calling function.  It is a catastrophic failure.  

PIO_BCAST_ERROR causes the error to be broadcast to all calling tasks (all of the compute tasks).
This is an important mode for situations such as querying a file for a variable or dimension which may or may not be present.   With an async setup this error would be returned only to the compute tasks associated with the call that triggered it.   

Finally PIO_RETURN_ERROR simply returns the error on the task or tasks on which they occur.  I can't think of a single instance where this mode is used in practice.

**Comment by edhartnett** [comment]
jedwards4b 23 hours ago collaborator

> Broadcast the error message to all calling tasks. That would be all compute tasks in ios. I can't think of a non-fatal error from pio that didn't originate in netcdf so I'm not sure of a case of a non-fatal error for which this mode would be useful.


@edhartnett
edhartnett 22 hours ago collaborator

> For example you do a PIOc_createfile() with an invalid iosystemid. That would cause an error, but you may just want to return to the calling program on the compute nodes, instead of calling MPI abort.
> 
> But I am not sure how to accomplish this. I can't think of any case where the error would not be returned on all compute nodes already. For example if all compute nodes call PIOc_createfile() with a bad iosystemid, then they will already all get the error code PIO_EBADID, without any additional effort on our part.
> 
> If only one compute node calls PIOc_createfile() with a bad ID, and the rest call with a good ID, how am I supposed to distribute that error?
