### ISSUE TITLE
Fix memory leaks in C tests

### ISSUE THREAD

**Issue by edhartnett** [NCAR/ParallelIO#245]
From Danqing:

> I also created a new Jenkins builder for valgrind check, currently it uses feature branch dqwu/valgrind_check
> https://jenkins-ci.mcs.anl.gov/job/ParallelIO_valgrind
> 
> Almost every tests have memory leaks. For the first one (1/74 Test: test_darray), I have looked at 
> definitely lost: 1,459 bytes in 36 blocks
> 
> In tests/unit/test_darray.c, there is a function check_file() that has memory leaks on MPI types (MPI_Type_commit is called, but MPI_Type_free is NOT)
> 
> In function main() we call PIOc_InitDecomp(), and we later call PIOc_freedecomp() that can invoke MPI_Type_free for cleaning.
> In check_file(), we call create_decomposition(), which calls PIOc_InitDecomp(), but there is no call to PIOc_freedecomp() at the end of this function for cleaning like main().
> Note: in check_file() we have a locally defined variable ioid that will have a different value as ioid defined in main()
> 
> After I apply a local fix, definitely lost bytes reduced from 1,459 bytes to 32 bytes.

**Comment by edhartnett** [comment]
These are not actually in the test code, they are in the library. ;-)

**Comment by edhartnett** [comment]
Are we clear of memory leaks now, or are there still some left?

**Comment by dqwu** [comment]
For Jenkins builder ParallelIO_valgrind_develop, there are no memory leaks on build 46. However, on build 47 there are new leaks from pio_rearr_opts. On build 48, test_pioc_putget and pio_rearr_opts failed due to timeout. We need look at recent PRs that got merged to the develop.

**Comment by jayeshkrishna** [comment]
@dqwu: Please create issues for mem leaks associated with pio rearranger opts and assign it to me.

**Comment by dqwu** [comment]
On build 49, test_pioc_putget and pio_rearr_opts passed. Maybe the timeout issue on build 48 is a false positive caused by the load of build server.

**Comment by jayeshkrishna** [comment]
Yes, the pio_rearr_opts is a relatively long test (~40s on my laptop) and must have timed out due to load on the server.

**Comment by edhartnett** [comment]
I will close this ticket. New leaks should be fixed before merge, and if not, will be given their own issues.
