### ISSUE TITLE
Failed to build statically linked PIO tests or examples on Eos/Titan with default CMake

### ISSUE THREAD

**Issue by dqwu** [NCAR/ParallelIO#252]
On Eos/Titan, "module avail cmake" shows only two choices:
cmake/2.8.11.2 cmake3/3.2.3(default)
Since PIO requires minimum CMake version of 2.8.12, we will use "module load cmake3" to load the default 3.2.3 version.

For Cray systems, statically linked binaries are highly recommended. The default configuration of the Cray Programming Environment is to only support static libraries. This can be overridden by setting the CRAYPE_LINK_TYPE environment variable to dynamic, or passing "-dynamic" to Cray cc/CC wrappers (add LDFLAGS="-dynamic" when running the cmake command) 

By using cmake 3.2.3 and -DPREFER_STATIC=TRUE, we are unable to build statically linked PIO tests or examples. "ldd examples/c/example1" shows that executable is dynamically linked, and it could not be run at all:
a) On bash shell of a login node
-bash: examples/c/example1: No such file or directory
b) Run with a PBS script on a compute node
cannot execute: exit(107) exec failed
One workaround is to set CRAYPE_LINK_TYPE to dynamic or use LDFLAGS="-dynamic" such that the executable can run normally, but the executable is still NOT statically linked as desired.

If we run "cat examples/c/CMakeFiles/example1.dir/link.txt", we will see that it contains something like:
/opt/cray/craype/2.4.2/bin/cc ... -Wl,-Bstatic -lnetcdf -lhdf5 ...  -Wl,-Bdynamic -ldl -lm ...

This seems to be a CMake bug: flags like -Wl,-Bstatic -lhdf5 -Wl,-Bdynamic is used to help the linker to select libhdf5.a instead of libhdf5.so, but then LEAK dynamic linking to following libraries (like -ldl -lm). Note that the cc wrapper implicitly contains a "-static" flag, which conflicts with -Wl,-Bdynamic. That is , the link command is mixing "global statically linking (-static)" and "local dynamically linking (-Wl,-Bdynamic -ldl -lm)".

We can reproduce this linking issue with a simple test:
/* Test.c */
int main() {
  return 0;
}
gcc -static Test.c -Wl,-Bdynamic -lrt
./a.out
bash: ./a.out: No such file or directory
Here -static and -Wl,-Bdynamic are conflicting

For CMake 3.4.3 or lower versions on Eos/Titan, with -DPREFER_STATIC=TRUE, -Wl,-Bstatic and -Wl,-Bdynamic pairs are always introduced in the link command.

For CMake 3.5.0 or higher versions, this issue has been fixed: we will no longer see -Wl,-Bstatic and -Wl,-Bdynamic pairs in the link command.

This issue is not reproducible on Edison though. Even for CMake 3.4.3 or lower versions, -Wl,-Bstatic and -Wl,-Bdynamic pairs are NOT generated in the link command.

Also, this issue has NOTHING to do with the arguable -rdynamic flag in Linux-GNU.cmake. It is optional whether the user support would like to comment out -rdynamic flag in that file or keep it there.

[Summary]
If we want to build statically linked PIO tests and examples on Eos/Titan, we cannot just use the default CMake module which is 3.2.3. Before CMake 3.5.0 or higher modules are available on Eos/Titan, we can install one in a user specified directory:
wget https://cmake.org/files/v3.5/cmake-3.5.0.tar.gz --no-check-certificate
tar zxf cmake-3.5.0.tar.gz
cd cmake-3.5.0
./bootstrap --prefix=some_cmake_install_path
make
make install
When run cmake, use some_cmake_install_path/bin/cmake in the command line.

To verify that a statically linked example is built, try "ldd examples/c/example1" and we should get:
not a dynamic executable

**Comment by jedwards4b** [comment]
I believe that the cmake flag -DCMAKE_SYSTEM_NAME=Catamount may fix this issue.

**Comment by dqwu** [comment]
Thanks, I tried -DCMAKE_SYSTEM_NAME=Catamount with CMake 3.2.3 and it worked: no Wl,-Bstatic or -Wl,-Bdynamic generated in the link command. So for CMake 3.4.3 or lower versions, this option should be used to build statically linked PIO tests or examples.

**Comment by jedwards4b** [comment]
Note that this flag should be used for all Cray systems.  I don't know if I understand your comment about 3.4.3 - you no longer need the flag in that version?  How do you know that?

**Comment by dqwu** [comment]
For 3.4.3 (or lower) we still need that flag. For 3.5.0 (or higher) versions that flag seems to be optional. I have tested both 3.4.3 and 3.5.0 CMake on Eos/Titan.

**Comment by jedwards4b** [comment]
I see - thanks for clarifying.
