### ISSUE TITLE
Check whether special MPI serial abort() function can be removed

### ISSUE THREAD

**Issue by edhartnett** [NCAR/ParallelIO#274]
From pioc_support.c:

 ```
/* Should we abort? */
    if (err_handler == PIO_INTERNAL_ERROR)
    {
#ifdef MPI_SERIAL
        /* Why the special abort() call for MPI_SERIAL??? */
        abort();
#else
        MPI_Abort(MPI_COMM_WORLD, -1);
#endif
    }
```

From Jim:

> Not sure why - I just checked the mpi-serial library and there is an abort function.

So probably this can be removed. But I will wait until I have error handling working and well-tested.

**Comment by rljacob** [comment]
Oh I think at one time mpi_serial did *not* have an abort function.
