### ISSUE TITLE
Fortran testing framework does not return error if a customized test driver fails

### ISSUE THREAD

**Issue by dqwu** [NCAR/ParallelIO#284]
Simple steps to reproduce it on latest master branch:
a) Edit pio_file.c, add a line of testing code before line 190.
file->iotype = 5; /* bad iotype for testing \*/
switch (file->iotype) /* now becomes line 191 */
Note: this will intentionally make PIOc_createfile() call iotype_error() and return an error code PIO_EBADIOTYPE (-500)

b) Build tests and run "ctest -R pio_unit_test"
The test will print out some error messages and call MPI_Abort, but still be marked as "Test Passed"

testing PIO_createfile...
ERROR: iotype 5 not defined in build src/clib/pio_file.c 222
...
ERROR: iotype 5 not defined in build src/clib/pioc_support.c 410
application called MPI_Abort(MPI_COMM_WORLD, 0) - process 0
...
Test Passed.

It is confirmed that this error code is returned to the caller in basic_tests.F90
ret_val = PIO_createfile(pio_iosystem, pio_file, iotype, filename)
if (ret_val .ne. PIO_NOERR) then
...

All affected C tests will fail as expected. If we run "ctest -R test_darray":
ERROR: iotype 5 not defined in build src/clib/pio_file.c 222
...
ERROR: iotype 5 not defined in build src/clib/pioc_support.c 410
0 Error -500 in tests/unit/test_darray.c, line 126
...
Test Failed.

There are two other Fortran tests that have the same issue: ncdf_simple_tests and ncdf_fail
Even the Test driver is marked as "FAILED" in the log, the test is marked as "Passed"
...
ERROR: iotype 5 not defined in build src/clib/pioc_support.c 410
            PIO_TF:                               Test driver  ------  FAILED
\<end of output>
...
Test Passed.

Why should these Fortran tests pass despite of printed error messages and failed Test driver? Is this an expected behavior or a test framework bug?

Note:
It will be helpful if these affected Fortran tests fail as expected (that is the purpose of unit tests), otherwise it will be hard to be noticed on CDash (the tests pass anyway). Though we reproduce this issue with artificial code (set iotype to 5), in real testing iotype can have bad values. In issue #276, the uninitialized file_desc_t type pointer (file) might contain a random junk value like 0x4078a4 (which is known as a wild pointer), and the member variable file->iotype might contain a bad value like 1238417607.

**Comment by jayeshkrishna** [comment]
Are these expected failures (Making sure that the library returns error when passing in an invalid parameter)?

**Comment by dqwu** [comment]
When there is a segmentation fault (invalid memory access) a unit test would fail. But it seems that for a bad iotype value a unit test would pass anyway. In issue #276, for some CDash/Jenkins builders the file_desc_t pointer is a wild pointer (non-NULL but invalid pointer value) and PIO can detect a bad iotype value(1, 2, 3, 4 are valid values). However, the test still passed (error messages printed out in the log, though), thus failed to catch this kind of bugs.

**Comment by jayeshkrishna** [comment]
So the issue seems to be that if the user customizes the testing framework and runs tests (and the tests fail) the framework does not exit with an error code (Initially the test driver was not supposed to be customized). i.e., Test driver fail does not result in a test fail

**Comment by jayeshkrishna** [comment]
Fixed by PR #298
