### ISSUE TITLE
Need to decide what versions of netcdf, pnetcdf we support, and test them

### ISSUE THREAD

**Issue by edhartnett** [NCAR/ParallelIO#285]
Our library depends on netcdf and pnetcdf.

I am building right now with the latest release of both (netcdf-4.4.1, pnetcdf-1.7.0).

What older versions of these libraries do we support?

When I tried to build with the previous versions of both libraries (4.4.0 and 1.6.1) I ran into some test timeouts in the fortran decomp tests. I didn't spend any time to figure out what is going on there yet.

We don't have to test every possible combination, but if we say we support pnetcdf-1.6.1, we need to test for it. And moving forward, if we want to continue supporting pnetcdf-1.7.0 after their next release, we will have to add tests for the new version, while keeping the 1.7.0 tests running.

So how about a definitive list of versions we support?

**Comment by jedwards4b** [comment]
There is a known bug in pnetcdf-1.6.1 which is fixed in 1.7.0, most but not all of pio is functional in 1.6.1.   
There is a known bug in netcdf-4.4.0 and older, again most of pio is functional in older versions.  

So at this point for a fully functional pio we need netcdf-4.4.1 or newer and pnetcdf-1.7.0 or newer.

**Comment by jayeshkrishna** [comment]
@jedwards4b : What was the bug that was in pnetcdf-1.6.1 (which was fixed in pnetcdf-1.7.0) that pio2 depended on?

**Comment by edhartnett** [comment]
I will let you guys work out the details of past versions in email.

This ticket was about specifying the exact versions I had to set up testing for. Looks like it is the easiest possible answer - the latest version of each.

I have set up my local Jenkins server with those versions. When new versions come out I will add them to the testing. Thanks!
