### ISSUE TITLE
add install capability to make process

### ISSUE THREAD

**Issue by jedwards4b** [NCAR/ParallelIO#29]

**Comment by edhartnett** [comment]
Would you like me to take care of this? As I noted in the requirements, it's a key feature for NOAA programmers to better use the ParallelIO library, so I'm happy to take it on.

**Comment by jedwards4b** [comment]
Sure

**Comment by edhartnett** [comment]
OK, will do.

**Comment by jedwards4b** [comment]
Kate pointed out to me that we already have an install target, documented here:
http://ncar.github.io/ParallelIO/install.html

Basically you need to define CMAKE_INSTALL_PREFIX to cmake
then run make install
Install the project...
-- Install configuration: ""
-- Installing: /glade/u/home/jedwards/dashboard/mytests/install/lib/libgptl.a
-- Installing: /glade/u/home/jedwards/dashboard/mytests/install/include/gptl.h
-- Installing: /glade/u/home/jedwards/dashboard/mytests/install/include/perf_mod.mod
-- Installing: /glade/u/home/jedwards/dashboard/mytests/install/include/perf_utils.mod
-- Installing: /glade/u/home/jedwards/dashboard/mytests/install/lib/libpioc.a
-- Installing: /glade/u/home/jedwards/dashboard/mytests/install/include/pio.h
-- Installing: /glade/u/home/jedwards/dashboard/mytests/install/lib/libpiof.a
-- Installing: /glade/u/home/jedwards/dashboard/mytests/install/include/pio.mod
-- Installing: /glade/u/home/jedwards/dashboard/mytests/install/include/pio_nf.mod
-- Installing: /glade/u/home/jedwards/dashboard/mytests/install/include/pio_types.mod
-- Installing: /glade/u/home/jedwards/dashboard/mytests/install/include/piolib_mod.mod
-- Installing: /glade/u/home/jedwards/dashboard/mytests/install/include/pionfget_mod.mod
-- Installing: /glade/u/home/jedwards/dashboard/mytests/install/include/pio_kinds.mod
-- Installing: /glade/u/home/jedwards/dashboard/mytests/install/include/pio_support.mod
-- Installing: /glade/u/home/jedwards/dashboard/mytests/install/include/piodarray.mod
-- Installing: /glade/u/home/jedwards/dashboard/mytests/install/include/pionfatt_mod.mod
-- Installing: /glade/u/home/jedwards/dashboard/mytests/install/include/pionfput_mod.mod
