### ISSUE TITLE
timeouts for unit tests 

### ISSUE THREAD

**Issue by jedwards4b** [NCAR/ParallelIO#295]
Where do you adjust the timeout time for unit tests.   When running on cori-knl I am running into a problem where most tests are timing out, but if I run the individual test by hand it passes.

**Comment by jayeshkrishna** [comment]
Changing the DEFAULT_TEST_TIMEOUT in CMakeLists.txt should work for you for tests in tests/general (right now it is set to 4 mins)

**Comment by jedwards4b** [comment]
thanks - it's actually different for different test directories and set to 1 minute for unit tests.
