### ISSUE TITLE
pio_unit_test does not fail when a Fortran function returns an error

### ISSUE THREAD

**Issue by dqwu** [NCAR/ParallelIO#312]
How to reproduce:
1) Check out the latest master branch.

2) Edit tests/unit/basic_tests.F90, change the returned value from PIO_createfile() to a nonzero value like -777 for testing:
ret_val = PIO_createfile(pio_iosystem, pio_file, iotype, filename)
ret_val = -777 _! Add this line to test an error code_
if (ret_val .ne. PIO_NOERR) then
...
call mpi_abort(MPI_COMM_WORLD, 0, ret_val2)
end if

3) Build tests and run "ctest -R pio_unit_test", the test does not fail as expected:
...
testing PIO_createfile...
ret_val =  -777
...
application called MPI_Abort(MPI_COMM_WORLD, 0) - process 0
...
Test Passed.

When mpi_abort() is called, the error code to return to invoking environment is set to 0:
call mpi_abort(MPI_COMM_WORLD, 0, ret_val2)

To properly signal pio_unit_test as failed for the test framework, mpi_abort() should be called with a nonzero error code as the second argument.

**Comment by jayeshkrishna** [comment]
Looks like the solution is replace
```
mpi_abort(MPI_COMM_WORLD, 0, ret_val2)
```
with 
```
mpi_abort(MPI_COMM_WORLD, 1, ret_val2)
```

**Comment by edhartnett** [comment]
This ticket has been open for a year. Has the fix been implemented?

**Comment by edwardhartnett** [comment]
OK, I have confirmed this is still a problem. I have a fix.
