### ISSUE TITLE
List of changes PIO1 vs PIO2

### ISSUE THREAD

**Issue by jayeshkrishna** [NCAR/ParallelIO#343]
It would be great to have a list of behavioural changes ("This works in PIO1 but not in PIO2" and vice versa) between PIO1 and PIO2.

**Comment by jayeshkrishna** [comment]
It would be great if we can document all changes btw PIO1 and PIO2 (changes required for user code that uses PIO1, new features available in PIO2) somewhere.

**Comment by edhartnett** [comment]
One big feature not yet in pio2 is the async. Not sure of any others.

If we can identify any other pio1 features that are not in pio2, but should be, let's start tickets for them and get them implemented.

I think it would be good if we marked a release, and then made such a list in reference to that release.
