### ISSUE TITLE
Add activation of netcdf logging to PIOc_set_log_level

### ISSUE THREAD

**Issue by edhartnett** [NCAR/ParallelIO#355]
If nc_set_log_level() is available, set it to the PIO logging level - 3.

This will allow users to start seeing netCDF logging messages at PIO logging level 4.

**Comment by edhartnett** [comment]
I am having a hard time figuring out how to get cmake to run the nc-config command to find out how to link netcdf, and then to be able to run a test to find out of nc_set_log_level() is present.

I confess to being frustrated working with cmake, knowing as I do that I will have to redo the build system for the C library, using autotools, in accordance with usual unix practice, and also to fit into the netCDF family.

So I will defer this feature until I have the autotools answer in place, then I can do it easily that way.

**Comment by jedwards4b** [comment]
Even when we move back to autotools I expect to maintain the cmake build.  The nc-config tool has been a difficult interface to try to use -  netcdf developers have changed the interface from version to version making it impossible to rely on.   The find tools in the cmake subdirectory of pio are intended to figure out the link requirements.   A test for nc_set_log_level can be added there.

**Comment by jedwards4b** [comment]
I have added a test in branch add_cmake_check_for_nc_logging, and added a test there.  
I need to build netcdf with logging enabled to test further but maybe you would like to give it a try.

**Comment by jedwards4b** [comment]
The branch now sets cmake variable NetCDF_C_LOGGING_ENABLED if nc_set_log_level is available.

**Comment by edhartnett** [comment]
OK, I've tested your CMake changes, and they seem to work fine. Thanks! CMake drives me mental.

I do not believe you are correct about nc-config. This has been the same for 15 years or so:

```
nc-config --libs
-L/usr/local/netcdf-4.4.1.1/lib -lnetcdf
```

I have added the code changes to call nc_set_log_level() and am checking them now. PR will be up shortly. Thanks for the help!

**Comment by edhartnett** [comment]
There is a bit of a problem. The value of NetCDF_C_LOGGING_ENABLED is set correctly by CMake, but is apparently not making it into the code build in src/clib.

That is, I can see this in CMakeCache.txt:

```
//Have function nc_set_log_level
NetCDF_C_LOGGING_ENABLED:INTERNAL=1

```

But when I include this in my code, it never evaluates to defined:

```
#if NetCDF_C_LOGGING_ENABLED
    /* If nc_set_log_level() is available, call it with the pio log
     * level minus 3. */
    if (level - 3 > 0)
    {
        printf("calling nc_set_log_level(%d)\n", level - 3);
        if ((ret = nc_set_log_level(level - 3)))
            return ret;
    }
#endif /* NetCDF_C_LOGGING_ENABLED */

```

So it does not work because it does not include my code. Is there some magic needed to get NetCDF_C_LOGGING_ENABLED to work in the code?

Thanks!
