### ISSUE TITLE
PIOc_createfile() does not free allocated memory upon failure

### ISSUE THREAD

**Issue by dqwu** [NCAR/ParallelIO#357]
This type of leak is found in both ncdf_fail.F90 and basic_tests.F90:
(1) Create a nc file and close it
(2) Try to create a file with exactly the same name (with noclobber option), error expected
In (2), when PIOc_createfile() fails (as expected), it has already allocated some memory with calloc:
if (!(file = calloc(sizeof(file_desc_t), 1)))
The allocated memory are not deleted when PIOc_createfile() returns an expected error code.

This is quite similar to issue 2 of #356: when PIOc_openfile() is called on a nonexistent nc file and fails as expected, the allocated memory from calloc will leak.

**Comment by edhartnett** [comment]
Ok I will fix.  Thanks for finding this.
