### ISSUE TITLE
NULL IOBUF parameter in some tests?

### ISSUE THREAD

**Issue by edhartnett** [NCAR/ParallelIO#373]
In pio_darray_int.c there is a function:

int pio_write_darray_multi_nc(file_desc_t *file, int nvars, const int *vid, int iodesc_ndims,
                              MPI_Datatype basetype, const PIO_Offset *gsize, int maxregions,
                              io_region *firstregion, PIO_Offset llen, int maxiobuflen,
                              int num_aiotasks, void *IOBUF, const int *frame)

I should be able to assert IOBUF, but I can't. SOmetimes, in testing, it is apparently NULL. Probably this is a bug somewhere, perhaps in the test code.

**Comment by jedwards4b** [comment]
no I think NULL is valid - say for example we have 8 ionodes and a distributed array with global size 4, then at least 4 nodes will have a null IOBUF.   In practice the box rearranger trys to have at least blocksize bytes on each io task and so if the total number of bytes to write is less than blocksize*numiotasks then some iotasks will have a NULL IOBUF.

**Comment by edhartnett** [comment]
OK I will document and close this issue. Thanks for the info!! ;-)
