### ISSUE TITLE
calculation of num_elem incorrect

### ISSUE THREAD

**Issue by jedwards4b** [NCAR/ParallelIO#377]
for (int vd = 0; vd < ndims; vd++)
     num_elem *= (rcount[vd] - rstart[vd])/rstride[vd];

At line 127 of pio_getput_int.c Is an incorrect calculation of num_elem.  
Take for example a variable with dims 4,5,6 and you want to read start(0,0,5) and count(4,5,1)
this would result in a num_elem of (4-0) * (5-0) * (1-5) = -80 which is clearly incorrect.

**Comment by jedwards4b** [comment]
I think that the correct equation is
for (int vd = 0; vd < ndims; vd++)
   num_elem *= rcount[vd] /rstride[vd];

The mistake is that rcount is being treated as you would an ending index, since count is the number of elements in the array start doesn't enter into the equation.

**Comment by edhartnett** [comment]
Duh.

I will fix and look for similar mistakes elsewhere. Stand by for PR. I'm going to merge the one I submitted this morning before I do this...
