### ISSUE TITLE
What is pre-processor macro PNET_READ_AND_BCAST

### ISSUE THREAD

**Issue by edhartnett** [NCAR/ParallelIO#380]
In pio_getput_int.c I see:

> #ifdef PNET_READ_AND_BCAST

What is that all about?

**Comment by jedwards4b** [comment]
On some systems - I believe it was the mira system, it was observed to be faster to have pnetcdf read on task 0 and broadcast then to do a distributed read, this macro implements that option.

**Comment by edhartnett** [comment]
Support and test?

Or remove?
