### ISSUE TITLE
Mark a release...

### ISSUE THREAD

**Issue by edhartnett** [NCAR/ParallelIO#383]
Let's tag a formal release.

I believe we agreed on version 2.1.

Can we tag this now?

**Comment by edhartnett** [comment]
OK, any idea when? Not in a rush, just would like to get it marked at some point.

**Comment by jedwards4b** [comment]
I am still working on issues in cesm.  But we have a pio landing page
http://www.cesm.ucar.edu/models/pio/

**Comment by edhartnett** [comment]
Very nice. ;-)

**Comment by edhartnett** [comment]
What I suggest is that you do a daily snapshot release of PIO, in addition to a numbered release every 6 months or so.

The daily snapshot release uses a date/time string as a version, and is released daily (automatically) after a successful build/test cycle.

This is a better option for users than just grabbing the head of the repo.

**Comment by jedwards4b** [comment]
So I think that we can do a numbered release whenever you think it suitable, and I have no objections to the daily if you want to set that up.

**Comment by edhartnett** [comment]
OK, what version number are we using for this release? 2.2.0?

Usually instead of a tag in git I use a branch for a release. It works just like a tag, but if you want to patch the release, it works very easily in git.

I will create a branch like pio2_2_0 to match the style of the v1 branch names. I will do this for today's master.

**Comment by jedwards4b** [comment]
Don't you need both a branch, pio2_2 and a tag pio2.2.0?

**Comment by rljacob** [comment]
Is it PIO version 2.2.0  or PIO2  version 2.0 ?

**Comment by jedwards4b** [comment]
The former I think.

**Comment by edhartnett** [comment]
OK, I marked the 2.2.0 release on github.

We will try and get 2.3.0 out before Summer. I will close this ticket.
