### ISSUE TITLE
darray tests memory leaks in test_pioc.c

### ISSUE THREAD

**Issue by dqwu** [NCAR/ParallelIO#396]
For now the darray tests in test_pioc.c are only run for non-async cases.

```
if (!async)
{
    /* Decompose the data over the tasks. */
    if ((ret = create_decomposition(my_test_size, my_rank, iosysid, &ioid)))
        return ret;

     if ((ret = test_darray(iosysid, ioid, num_flavors, flavor, my_rank)))
        return ret;
}
```
create_decomposition() calls PIOc_InitDecomp(), but there is no PIOc_freedecomp() call after test_darray(), which has caused some memory leaks.

If we want to make darray tests work for async cases later (#388), this leak should also be avoided.

**Comment by edhartnett** [comment]
Thanks! I have a PR up with a fix.
