### ISSUE TITLE
IO comm created by PIOc_Init_Async() not freed

### ISSUE THREAD

**Issue by dqwu** [NCAR/ParallelIO#404]
In PIOc_Init_Async(), a shared IO comm is created:
```
/* There is one shared IO comm. Create it. */
if ((ret = MPI_Comm_create(world, io_group, &io_comm)))
    return check_mpi(NULL, ret, __FILE__, __LINE__);
```
Only a copy (dup) of the IO comm is saved in my_iosys (iosystem_desc_t struct):
```
/* If this is the IO component, remember the
 * comm. Otherwise make a copy of the comm for each
 * component. */
if (in_io)
    if (cmp)
    {
        LOG((3, "making a dup of io_comm = %d io_rank = %d", io_comm, io_rank));
        if ((ret = MPI_Comm_dup(io_comm, &my_iosys->io_comm)))
            return check_mpi(NULL, ret, __FILE__, __LINE__);
        ...
    }
```
Two minor issues with the code above:
1) The comment seems to be out of date (probably for old code)
2) It is better to add {} to the first if statement, to achieve better code readability

In PIOc_finalize() where we will free MPI resources, only the copy of the IO comm is freed
```
if (ios->io_comm != MPI_COMM_NULL)
    MPI_Comm_free(&ios->io_comm);
```
All of the async tests have this leak. We need to save the original io_comm in some variable, such that we can call MPI_Comm_free on it later in PIOc_finalize().

**Comment by edhartnett** [comment]
Thanks I will take a look...

**Comment by edhartnett** [comment]
The original io_comm is no longer needed, once dupes are made for the user (if desired) and all the computation components. So now I just free io_comm at the end of PIOc_Init_Async().

I will have a PR up shortly.
