### ISSUE TITLE
pioperf test issue

### ISSUE THREAD

**Issue by jedwards4b** [NCAR/ParallelIO#410]
Trying to reduce some rather complex problems into small test cases.   This case uses the pioperf
executable in tests/performance on 4 tasks with 2 io tasks.  The namelist is
```
&pioperf
  decompfile= 'simple.4', 'simple.4_1hole'
  pio_typenames = 'pnetcdf'
  rearrangers = 2
  niotasks = 2
  nframes = 1
  nvars = 1
  varsize = 4
  unlimdimindof = .false.
/
```
the first decomp file works correctly, the second writes correctly but then fails on the open file
for read.   The two decomp files are attached (with a txt extension)
[simple.4.txt](https://github.com/NCAR/ParallelIO/files/688003/simple.4.txt)
[simple.4_1hole.txt](https://github.com/NCAR/ParallelIO/files/688004/simple.4_1hole.txt)

**Comment by jedwards4b** [comment]
I have confirmed this problem on a second machine - the first was laramie, the second yellowstone.

**Comment by jayeshkrishna** [comment]
What is the error message that you are getting? On my laptop I get,
```
Abort with message No such process in file /home/jayeshkrishna/acme/pio/tmp_ParallelIO/src/clib/pioc_support.c at line 1160
```
I had to,
* Create the namelist file, pioperf.nl, as shown above
* download & rename simple.4*.txt to remove ".txt"
* Run pioperf with 4 procs

**Comment by jedwards4b** [comment]
Yes that's the error message I'm getting as well.  You can remove simple.4 from the namelist and just run the simple.4_1hole file.  I provided simple.4 to illustrate expected behavior.

**Comment by jayeshkrishna** [comment]
Looks like the issue is that the refactored check_netcdf() - pioc_support.c - does not distinguish between different file iotypes. Although the file is being opened correctly the return value (success) is not being propogated to all tasks.

**Comment by jedwards4b** [comment]
That doesn't sound correct to me - if that were the case why is it only failing for some decomps? and why wouldn't it be caught with any of our tests.  
However I think that you are on the right track - looking at the logging files i see:
```
:) grep Bcasting pio_log_[0123].txt 
pio_log_0.txt:		0 Bcasting error code ierr = 0 ios->ioroot = 0 ios->my_comm = -1006632960
pio_log_1.txt:		1 Bcasting error code ierr = 0 ios->ioroot = 0 ios->my_comm = -2080374779
pio_log_2.txt:		2 Bcasting error code ierr = 0 ios->ioroot = 0 ios->my_comm = -2080374779
pio_log_3.txt:		3 Bcasting error code ierr = 0 ios->ioroot = 0 ios->my_comm = -2080374779
:) grep 'Bcast err' pio_log_[0123].txt 
pio_log_0.txt:		0 Bcast error code ierr = 0
pio_log_1.txt:		1 Bcast error code ierr = 3
pio_log_2.txt:		2 Bcast error code ierr = 3
pio_log_3.txt:		3 Bcast error code ierr = 3
```
I think that the real issue is that the tasks are out of sync with respect to MPI - all those values should be the same on return from Bcast.

**Comment by jayeshkrishna** [comment]
Also, in pioc_support.c:1163 it looks like the error code is only propogated among io procs. The issue seems to be with error code propogation+checking.

**Comment by jayeshkrishna** [comment]
Should that like have union_comm instead of my_comm ?

**Comment by jayeshkrishna** [comment]
FYI: The only error handler tested in the fortran tests in the bcast handler.
