### ISSUE TITLE
Use malloc not bget in malloc_iodesc() in pioc_support.c

### ISSUE THREAD

**Issue by edhartnett** [NCAR/ParallelIO#413]
All our other metadata structs are allocated with malloc/calloc, except the io_desc_t, which is allocated using bget.

The advantages of using malloc/calloc are:
* more standard
* does not involve complex bget code
* allows for performant initialization by using calloc, and 0/NULL for expected initialization values.

So while we continue to use bget with data, there is no need to use it for metadata like the io_desc_t. It can be changed to calloc and many lines of code removed.

**Comment by jedwards4b** [comment]
okay, sounds fine
