### ISSUE TITLE
Tests for functions in pio_smpd.c

### ISSUE THREAD

**Issue by edhartnett** [NCAR/ParallelIO#438]
The code in pio_spmd.c is almost completely untested.

**Comment by jayeshkrishna** [comment]
The pio runtime flow control options that I am working on (Issue #120) will bring in some tests for functions in this file,

**Comment by edhartnett** [comment]
The pio_spmd.c file is being tested much more now, up fro <10% coverage to 60%, which is great progress.

The pio_swapm() function is now tested.

The only remaining function that is not tested is pio_fc_gatherv(). This function is a future optimization so is not currently used in the library.

**Comment by edhartnett** [comment]
I will close this ticket since I think this is all the tests we are are planning on adding right now.
