### ISSUE TITLE
Unused buffer in test_intercomm2.c

### ISSUE THREAD

**Issue by dqwu** [NCAR/ParallelIO#462]
There is a buffer allocated in test_intercomm2.c, line 380:
`char *buf111 = malloc(19999);`
However, this buffer is never used or freed (memory leak detected in test_intercomm2)

The same code is commented out in test_common.c, line 633
`/* char *buf111 = malloc(19999); */`

Should we comment out line 380 in test_intercomm2.c? Or should we completely delete these two lines if they will never be used in the future?

**Comment by edhartnett** [comment]
Thanks for catching this.

Those two lines are not needed, and I have deleted them. The change will be in my next PR.
