### ISSUE TITLE
Build error when HAVE_MPE macro is not defined

### ISSUE THREAD

**Issue by ScottWales** [NCAR/ParallelIO#472]
I am getting the following error when I `make` PIO version 2.0.31 with Intel compilers:

```
pio/2.0.31/src/examples/c/example2.c(154): error: identifier "NUM_EVENTS" is undefined
  init_logging(int my_rank, int event_num[][NUM_EVENTS])
```

This appears to be caused by the macro `NUM_EVENTS` not being defined when `HAVE_MPE` is false. The function `init_logging()` doesn't appear to get called at all without `HAVE_MPE`, perhaps the `#ifdef` around the contents of that function could be moved so it covers the whole definition, or the `NUM_EVENTS` macro could be defined unconditionally.

**Comment by edhartnett** [comment]
Can you tell me how you built the library?

**Comment by ScottWales** [comment]
I'm working on the [NCI](http://nci.org.au) 'Raijin' HPC

Cmake command was
```
CC=mpicc FC=mpif90 cmake ../src \
    -DMPI_Fortran_LIBRARIES=$OPENMPI_ROOT/lib/Intel/libmpi_f90.so \
    -DMPI_Fortran_INCLUDE_PATH=$OPENMPI_ROOT/include/Intel \
    -DWITH_PNETCDF=OFF \
    -DNetCDF_PATH=$NETCDF_ROOT \
    -DNetCDF_Fortran_INCLUDE_DIR=$NETCDF_ROOT/fortran/Intel \
    -DNetCDF_Fortran_LIBRARY=$NETCDF_ROOT/lib/Intel/libnetcdff.so \
    -DCMAKE_INSTALL_PREFIX=$DIR/install \
    -DCMAKE_C_FLAGS="-std=gnu99"
```
Libraries used were
 * Intel Compiler Suite 17.0.1.132
 * OpenMPI 1.10.2
 * Netcdf 4.3.3.1

**Comment by edhartnett** [comment]
Can you try getting the HEAD of the repo and build that?

Also to get all pnetcdf tests to pass you need to use netcdf-4.4.1. There were some bugs in 4.3.x which cause problems for PIO.

**Comment by ScottWales** [comment]
HEAD is compiling fine, thank you. I'll also look into updating our netCDF version
