### ISSUE TITLE
Early return in ncdf_tests.F90 for netCDF-4/HDF5 iotypes

### ISSUE THREAD

**Issue by dqwu** [NCAR/ParallelIO#492]
For netCDF-4/HDF5 iotypes, even when there are no test errors, the subroutine test_nc4 unexpectedly return early, see the code below (a comment is added to the return line):
```
! Should not have worked except for netCDF-4/HDF5 iotypes.
if (iotype .eq. PIO_iotype_netcdf4c .or. iotype .eq. PIO_iotype_netcdf4p) then
   if (ret_val .ne. PIO_NOERR) then
      err_msg = "Could not set chunk cache"
      call PIO_closefile(pio_file)
   endif
   if (chunk_cache_size_in .ne. chunk_cache_size .or. chunk_cache_nelems_in .ne. chunk_cache_nelems .or. &
        chunk_cache_preemption_in .ne. chunk_cache_preemption) then
      err_msg = "Incorrect chunk cache values!"
      call PIO_closefile(pio_file)
   endif
   return /* NOTE: early return here */
else if (iotype .eq. PIO_iotype_pnetcdf .and. ret_val .eq. PIO_NOERR) then
   err_msg = "Did not get expected error when trying to set chunk cache for pnetcdf file"
   call PIO_closefile(pio_file)
   return
else if (iotype .eq. PIO_iotype_netcdf .and. ret_val .eq. PIO_NOERR) then
   err_msg = "Did not get expected error when trying to set chunk cache for netcdf classic file"
   call PIO_closefile(pio_file)
   return
end if
```
This unexpected early return has two issues:
1) The following code are not tested for netCDF-4/HDF5 iotypes (code coverage issue)
2) There are observed memory leaks (for pio_unit_test), as PIO_freedecomp() at the end of test_nc4 will not be called for netCDF-4/HDF5 iotypes

The return statement should go to the two inner if statements (early return for errors only)

**Comment by edhartnett** [comment]
When I run the tests, everything succeeds for me.

When you run the tests you get a failure?

**Comment by dqwu** [comment]
No failures, only issue is memory leaks and untested code. I will push a fix soon.

**Comment by dqwu** [comment]
"When I run the tests, everything succeeds for me." This is expected, because the issue here is that some test code after the return is not covered for netCDF-4/HDF5 iotypes.

**Comment by edhartnett** [comment]
Is the code you are showing your fix? Or is it the original code?

Where in the file is the leak happening?

**Comment by dqwu** [comment]
It is the original code (I only add a comment for the return line). Because of this unexpected early return, " call PIO_freedecomp(pio_iosystem, iodesc_nCells)" is skipped for netCDF-4/HDF5 iotypes.

**Comment by edhartnett** [comment]
Ah, I was looking for this code in test_pioc.c, but this is fortran. ;-)

Stand by...

**Comment by dqwu** [comment]
After this fix, we will have no memory leaks reported by Valgrind check.

**Comment by edhartnett** [comment]
OK, now I see. I agree that the return is in the wrong place. It should be in each of the if statemetnts, like this:

```
    if (iotype .eq. PIO_iotype_netcdf4c .or. iotype .eq. PIO_iotype_netcdf4p) then
       if (ret_val .ne. PIO_NOERR) then
          err_msg = "Could not set chunk cache"
          call PIO_closefile(pio_file)
          return
       endif
       if (chunk_cache_size_in .ne. chunk_cache_size .or. chunk_cache_nelems_in .ne. chunk_cache_nelems .or. &
            chunk_cache_preemption_in .ne. chunk_cache_preemption) then
          err_msg = "Incorrect chunk cache values!"
          call PIO_closefile(pio_file)
           return
   endif

```
