### ISSUE TITLE
PIO Performance Tests don't check for parallel support before trying to run pnetcdf tests

### ISSUE THREAD

**Issue by Katetc** [NCAR/ParallelIO#5]
The performance tests produce unhelpful errors if you compile and run them on a machine without PNetcdf support (i.e., Hobart using gnu and -DWITH_PNETCDF=FALSE) and then choose to run a test with pio_typenames = 'pnetcdf' in the namelist. In this case, the test outputs "ERROR: Operation on undefined file /scratch/cluster/katec/ParallelIO/src/clib/pio_lists.c 74" continuously until you kill the job. It makes more sense for the performance test to check for parallel support and exit with an error that indicates the requested test can't be performed on this system.

**Comment by jedwards4b** [comment]
Moved to Jira PIO-2
