### ISSUE TITLE
Move function init_rearr_opts() to file of internal functions

### ISSUE THREAD

**Issue by edhartnett** [NCAR/ParallelIO#510]
Every function in pioc.c has it's documentation put in the public documentation.

So internal functions need to be in one of the internal files, which does not get it's documentation included in the manual.

**Comment by jayeshkrishna** [comment]
Is there another way to distinguish between developer and user documentation? There is a benefit in restricting internal utility functions used only within a file to be defined inside the file (rather than giving the functions a global scope by defining it in a separate file)

**Comment by edhartnett** [comment]
I don't know of any better way to have internal and public functions in doxygen, but you are welcome to take a look and see what you come up with.

I moved the function to pio_rearranger.c in my current PR. If you can figure out a better way to do the docs, I can move it back.

**Comment by jayeshkrishna** [comment]
Yes, let us explore and see if we can find an alternative solution. Meanwhile, it would be great if you can remove the moving of function in PR #513 (The move should have a separate PR and I can work on it if we decide that moving the function is the best way to get the documentation right).

@jedwards4b , @Katetc , @dqwu : Any ideas?

**Comment by jayeshkrishna** [comment]
I would have preferred that the function was not moved in PR #513 . Let us may be have a discussion here on how to address separating developer and user documentation (atleast that is what I think the issue is).
Does "@internal" tags help here (PIO_INTERNAL_DOC)?
Any thoughts @jedwards4b / @edhartnett / @Katetc / @dqwu ?

**Comment by edhartnett** [comment]
If you want the function in that file, you have to change the documentation situation first.

**Comment by jayeshkrishna** [comment]
Yes, let us discuss on how to fix the documentation issue here. I will try the "@internal" flag and see if that works. 
Meanwhile, @edhartnett can you clarify on the issue with the documentation (Is the issue like I understand about hiding internal developer documentation from the user documentation?)? Do we need a separate issue for this?

**Comment by edhartnett** [comment]
The requirements are:
* Produce user documentation with all public library functions.
* Produce developer documentation with all public and all internal function documentation.

According to this:
http://stackoverflow.com/questions/11025971/separate-internal-from-external-documentation-in-doxygen

It should be possible to do this with an internal flag.

I will put this up as an issue, but I don't think I will get around to doing it until after our next (first) version is released.

**Comment by edhartnett** [comment]
I am going to close this issue. Further work on this will be under issue #535.
