### ISSUE TITLE
Mem leak in pio_rearr_opts test

### ISSUE THREAD

**Issue by jayeshkrishna** [NCAR/ParallelIO#520]
The test, pio_rearr_opts.F90.in, does not free all the MPI comms that it creates/dups (dup inside
loop but the free is outside the loop - looks like error during code refactoring).

@dqwu : Mentioned this bug in #245

**Comment by dqwu** [comment]
Unfortunately this is in master now. Next time if we find new memory leaks in the develop branch, that PR should fix the leak before it goes to master.

**Comment by jayeshkrishna** [comment]
Yes, I agree.
