### ISSUE TITLE
MPI Info object not freed in PIOc_finalize()

### ISSUE THREAD

**Issue by dqwu** [NCAR/ParallelIO#533]
PIOc_set_hint() has not been tested before. PR #513 updated test_iosystem3.c to test it. New memory leaks are detected as the MPI Info object created by PIOc_set_hint() is not freed in PIOc_finalize()

@edhartnett @jedwards4b @jayeshkrishna 
I have updated Jenkins builder ParallelIO_valgrind_develop such that it will fail on newly detected memory leaks. If it is confirmed that a PR merged to develop caused it to fail, that PR should fix the leaks before it will be merged to master.

**Comment by rljacob** [comment]
Are those memory leak results visible on cdash?

**Comment by dqwu** [comment]
Not sure if there is a cdash builder using PIO_VALGRIND_CHECK, like the Jenkins builders ParallelIO_valgrind_develop and ParallelIO_valgrind. We can create such a builder on cdash if possible.

**Comment by jayeshkrishna** [comment]
@jedwards4b / @edhartnett  can create a new build config with "cmake ... -DPIO_VALGRIND_CHECK=ON " to get valgrind checks on to cdash. Is there anything else required, @dqwu ?

**Comment by dqwu** [comment]
@jayeshkrishna 
Adding that option when calling cmake is sufficient.

In addition, the build script can use grep to extract the leak information from LastTest.log
LEAK_INFO=`find . -type f | grep LastTest.log | xargs grep "definitely lost:\|still reachable:" | grep -v "0 bytes in 0 blocks"`

**Comment by dqwu** [comment]
Then we can let the build script return -1 upon detected leaks.
```
if [ -n "$LEAK_INFO" ]
then
 echo "Memory leaks detected!"
 exit -1
fi
```
