### ISSUE TITLE
Making PNET_READ_AND_BCAST default in pio_getput_int.c?

### ISSUE THREAD

**Issue by dqwu** [NCAR/ParallelIO#537]
In PIOc_get_vars_tc(), we have two code sections for PIO_IOTYPE_PNETCDF. The default is not using PNET_READ_AND_BCAST, unless that macro is explicitly defined by users when building PIO. 
```
#ifdef PNET_READ_AND_BCAST
    LOG((1, "PNET_READ_AND_BCAST"));
    ...
    if (ios->iomaster == MPI_ROOT)
    ...
#else
    LOG((1, "not PNET_READ_AND_BCAST"));
    ...
#endif /* PNET_READ_AND_BCAST */
...
if ((mpierr = MPI_Bcast(buf, num_elem * typelen, MPI_BYTE, ios->ioroot, ios->my_comm)))
    return check_mpi(file, mpierr, __FILE__, __LINE__);
```

It seems that using PNET_READ_AND_BCAST is better, that is: only the IO master does the IO.

With current PIO model, all IO tasks in above code will have exactly the same start and count. If we are not using PNET_READ_AND_BCAST, we are actually not utilizing the features of PNETCDF here as the IO tasks will get exactly the same data in the buffer (start and count used are the same). Also, the MPI broadcast will send the same data again from IO master to other IO tasks. So for some IO tasks, they get data from netcdf file first, then get the same data from the IO master.

Using PNET_READ_AND_BCAST does not have this duplicated data issue (less overhead): only the IO master reads the data, and sends it to other IO tasks.

Unless the model is updated such that each IO tasks can have different start and count here (true parallel read), we can change to use PNET_READ_AND_BCAST by default.

**Comment by jedwards4b** [comment]
I think that you are correct - unless we can figure out a more selective way to send the data to compute nodes that don't already have it then the READ_AND_BCAST should always be better.

**Comment by edhartnett** [comment]
There has already been some discussion in #380.
