### ISSUE TITLE
classic only build is failing

### ISSUE THREAD

**Issue by edhartnett** [NCAR/ParallelIO#550]
The netcdf classic-only build is failing. (That is, netcdf classic only, with no pnetcdf or netcdf-4).

I would be good to get one of these on cdash or the the other jenkins server. I have this build on my jenkins server, but unfortunately not on my branches, just on the develop and master branches. I will add my own branches and hopefully avoid this.

**Comment by edhartnett** [comment]
This has to do with the LONG type.

**Comment by jedwards4b** [comment]
Is this not it?  http://my.cdash.org/buildSummary.php?buildid=1122951
