### ISSUE TITLE
test_pioc_putget failed with netcdf classic

### ISSUE THREAD

**Issue by dqwu** [NCAR/ParallelIO#555]
This issue could be related to #550

A cdash build caught this failure:
http://my.cdash.org/testDetails.php?test=29641908&build=1123875
The output shows:
0 Error 1112 in /scratch/cluster/katec/dashboard/src/tests/cunit/test_pioc_putget.c, line 371
1 Error 1112 in /scratch/cluster/katec/dashboard/src/tests/cunit/test_pioc_putget.c, line 371
2 Error 1112 in /scratch/cluster/katec/dashboard/src/tests/cunit/test_pioc_putget.c, line 371
3 Error 1112 in /scratch/cluster/katec/dashboard/src/tests/cunit/test_pioc_putget.c, line 371

The netcdf version used by this build (/usr/local/netcdf_c-4.3.2_f-4.4.1-nag-6.0) was likely built with option --disable-netcdf-4, thus _NETCDF4 is not defined in the PIO code.

In test_pioc_putget.c, there are two places using long type:
```
if (expected[PIO_INT] != PIOc_get_att_long(ncid, NC_GLOBAL, name, long_array_in))
    return ERR_WRONG;
...
/* Use long on same int var. */
if ((ret = PIOc_put_att_long(ncid, varid[3], LONG_ATT_NAME, PIO_INT,
                             ATT_LEN, (long int *)long_array)))
    return ret;
```
When the flavor (iotype) is PIO_IOTYPE_NETCDF, if _NETCDF4 is not defined (--disable-netcdf-4 was configured to build netcdf), both  PIOc_get_att_long() and PIOc_put_att_long() will fail while calling nc_inq_type() with type NC_INT64.

**Comment by edhartnett** [comment]
I am working on a fix for this now. I hope to have a fix by Monday morning.
