### ISSUE TITLE
set PIO_NOFILL as default

### ISSUE THREAD

**Issue by jedwards4b** [NCAR/ParallelIO#568]
In pio1 the default when opening a file to write is PIO_NOFILL 
this does not appear to be happening in PIO2 and it's a significant performance hit.

**Comment by edhartnett** [comment]
I can add this to the PIOc_openfile()/PIOc_createfil() functions.

I will refrain from adding it to the netCDF-compatible PIOc_open()/PIOc_create() functions. Instead, users that want fill mode turned off should use NC_NOFILL in the mode field.

**Comment by edhartnett** [comment]
OK, this seems kind of sleazy to me. So I have done it in PIOc_createfile() (which will be deprecated) but not in PIOc_create() (which is the future).

The reason it is sleazy is that it overrides the user's choice, and in a non-obvious way. There is no way for the user to set the fill mode to on if we always set it to off.

This also introduces an incompatibility with netCDF which will cause users confusion. Seems likes it's not too hard for users to specify NC_FILL or NC_NOFILL when the file is opened. In any case that's what netcdf does, so I don't think we should change it.

I will have a PR up shortly that makes the change for createfile() for backwards compatibility.
