### ISSUE TITLE
Change PIOc_set_rearr_opts() to reject bad input

### ISSUE THREAD

**Issue by edhartnett** [NCAR/ParallelIO#618]
Currently, if the input is bad, there is a warning printed to the log and a sensible value is used instead.

This is not good because we cannot depend on users to look at the log, or even be running the log. So we must check the parameters and return PIO_EINVAL for invalid ones, just like all the other functions.

**Comment by jayeshkrishna** [comment]
I am with you on more strict user argument requirements. However note that the reset is done only for the parameters that the user is not interested (e.g. if flow control is disabled what are the valid values for parameters that control flow control from compute to io procs? etc). We are doing initialization here.
We don't reset user supplied parameters that are of interest to the user and I don't think we should force the user to supply "valid " values for parameters that are of no interest to the user.

**Comment by jayeshkrishna** [comment]
However I think we could probably have some more arg checking here.

**Comment by jayeshkrishna** [comment]
@edhartnett : Do you want to take this issue ? If not, please reassign it to me and I can add some more arg checking here.

**Comment by edhartnett** [comment]
I will take this issue.

**Comment by jayeshkrishna** [comment]
Ok, in that case please make sure that you add more arg checking (not remove the current resets/inits in the code that is required to make the user's life easier)

**Comment by edhartnett** [comment]
What would help a lot is to document requirements for this.

For example, what is going on with this code:

 ```
 else if (ios->rearr_opts.comm_type == PIO_REARR_COMM_P2P)
    {
        if (ios->rearr_opts.fcd == PIO_REARR_COMM_FC_2D_DISABLE)
        {
            /* Compare and log user and default opts. */
            cmp_rearr_comm_fc_opts(&(ios->rearr_opts.comm_fc_opts_comp2io),
                                   &def_comm_nofc_opts);
            cmp_rearr_comm_fc_opts(&(ios->rearr_opts.comm_fc_opts_io2comp),
                                   &def_comm_nofc_opts);
            /* Hard reset flow control opts to defaults. */
            ios->rearr_opts.comm_fc_opts_comp2io = def_comm_nofc_opts;
            ios->rearr_opts.comm_fc_opts_io2comp = def_comm_nofc_opts;
        }
```

**Comment by edhartnett** [comment]
If you want to take a stab at this, that would be great.

What would also be welcome is unit tests for all these functions. I have started, but there is much left to do. Unit tests will also serve to demonstrate how you expect the functions to work.

I suggest that somewhere you add to the docs a detailed explanation for the end user of how to use these features. I've been looking at the code and it's not really clear to me. I think I get the general idea, but a real-world example of valid settings would be really helpful. And of course most users will not be looking at the code.

It's not clear to me why you are "resetting" values. We don't do that anywhere else, so what makes it necessary here? The custom throughout PIO and netCDF is generally not to correct user mistakes, but to simply return error codes and let the user correct their own mistakes. Is this code an exception for some reason? But I have not quite figured out if that is what is happening. ;-)

Note that most users will not use logging. Logging has performance implications and is not compiled in by default. If you want to present info to the end-user, you can define a new error code in pio.h - there is a section for PIO specific codes. Add a text message to go with it in PIOc_strerror().

When pio_err() is called with an error, eventually, PIOc_strerror() is called. So if you add error messages they will be seen when the program crashes. ;-)
