### ISSUE TITLE
Add functions to write/read decomp files in netCDF format (instead of text)

### ISSUE THREAD

**Issue by edhartnett** [NCAR/ParallelIO#627]
NetCDF files are more self-documenting and convenient, and it helps us "eat our own dogfood" if we use PIO to write/read the decomp files.

Here's what I have right now as the output. This is for a very simple case, a 1-D array of 4 elements, distributed over 4 tasks. Each task gets one element. (This is from test_pioc.c. More complex examples will follow.)

```
netcdf nc_decomp_test_pioc_rank_0_async_0 {
dimensions:
	dims = 1 ;
	task = 4 ;
	map_element = 1 ;
variables:
	int global_size(dims) ;
	int maplen(task) ;
	int map(task, map_element) ;

// global attributes:
		:version = 2017 ;
		:max_maplen = 1 ;
		:title = "Very Simple Test Decompositon" ;
		:history = "Added to PIO automatic testing by Ed in February 2017." ;
		:source = "Decomposition file produced by PIO library." ;
data:

 global_size = 4 ;

 maplen = 1, 1, 1, 1 ;

 map =
  0,
  1,
  2,
  3 ;
}


```

Some things to note:
* This is netCDF classic, which means I have to use 32-bit ints for the map values. By using netCDF-4 I could use 64-bit ints.
* It is zero-based, in accordance with C and netCDF custom. The C API will take 0-based data. We can still used 1-based assignments in Fortran, but the data file represents the C output and that's what ncdump will show. We will use fill-value where zero is used in the text decomp files.

**Comment by jedwards4b** [comment]
so map_element is maxval(maplen)?  This should work fine - I think that for some of the largest maps we may need to use 64-bit ints, but we should be able to make that transition without user intervention or awareness shouldn't we?

**Comment by edhartnett** [comment]
The problem with going to 64-bits is that we then must require netCDF-4, right?

There is no easy way to store 64-bit ints in netCDF classic.

**Comment by edhartnett** [comment]
Here's what I have now...

```
netcdf nc_decomp_test_pioc_rank_0_async_0 {
dimensions:
	dims = 1 ;
	task = 4 ;
	map_element = 1 ;
variables:
	int global_size(dims) ;
	int maplen(task) ;
	int map(task, map_element) ;

// global attributes:
		:version = "2017" ;
		:max_maplen = 1 ;
		:title = "Very Simple Test Decompositon" ;
		:history = "Added to PIO automatic testing by Ed in February 2017." ;
		:source = "Decomposition file produced by PIO library." ;
		:array_order = "C" ;
data:

 global_size = 4 ;

 maplen = 1, 1, 1, 1 ;

 map =
  0,
  1,
  2,
  3 ;
}

```
