### ISSUE TITLE
test_spmd failed on some builds

### ISSUE THREAD

**Issue by dqwu** [NCAR/ParallelIO#629]
test_spmd failed Valgrind check.
In test_rearranger_opts1(), ro1, ro2 and ro3 are not freed after use:
```
if (!(ro1 = calloc(1, sizeof(rearr_comm_fc_opt_t))))
    return ERR_AWFUL;
if (!(ro2 = calloc(1, sizeof(rearr_comm_fc_opt_t))))
    return ERR_AWFUL;
if (!(ro3 = calloc(1, sizeof(rearr_comm_fc_opt_t))))
    return ERR_AWFUL;
...
return 0;
```

test_spmd also failed Address Sanitizer check.
In test_rearranger_opts2(), ios (uninitialized) passed to check_and_reset_rearr_opts() is an invalid (wild) pointer:
```
iosystem_desc_t *ios;
check_and_reset_rearr_opts(ios);
```
This issue has been fixed in PR #626:
```
iosystem_desc_t my_ios;
iosystem_desc_t *ios = &my_ios;
check_and_reset_rearr_opts(ios);
```

We should continue to fix the memory leaks issue.

**Comment by edhartnett** [comment]
I am working on this test today. I will fix. Thanks.
