### ISSUE TITLE
pio_swapm() test coverage shows that it is not being tested

### ISSUE THREAD

**Issue by edhartnett** [NCAR/ParallelIO#637]
We have a function pio_swapm() in pio_spmd.c.

It is like MPI_Alltoallw() with flow control.

But in our tests, we never use the flow control. I'm not sure if we do in the code either. (I believe this is an intended optimization that has not yet be achieved.)

Is this similar to the flow control that Jayesh just added? Or is that different?

**Comment by jayeshkrishna** [comment]
The fortran tests that test rearranger options should test this part of the code.

**Comment by edhartnett** [comment]
I check the code coverage today and it is not covered. Actually I have noticed that it is not covered for quite a while - I didn't know that your tests should be hitting it. There are only a handful of big functions that are mostly or entirely untested, and this is one of them.

So you may want to take a look at those tests.

From your answer I understand that the flow control you added and the flow control used by swapm are the same, right?

Thanks!

**Comment by jayeshkrishna** [comment]
Yes, the code was already there (added by @jedwards4b ), my code made using it easier. I would have expected the fortran tests to cover this code, I will take a look at this one

**Comment by edhartnett** [comment]
OK, I changed the title to reflect the issue. Thanks!

**Comment by jayeshkrishna** [comment]
Good catch ! Looks like we are only hitting the mpi_alltoallw() in our tests (after the reorganization of the code there is a missing set for the options in the fortran interface), I will fix this one.

**Comment by jayeshkrishna** [comment]
Hmm, the code is there to set the options. I will dig into this and update this issue.

**Comment by jayeshkrishna** [comment]
Looks like the the test needs a little tweaking.
