### ISSUE TITLE
is documentation of ceil2() function in pio_spmd.c correct?

### ISSUE THREAD

**Issue by edhartnett** [NCAR/ParallelIO#645]
When writing a test for the ceil2() function, I found that it's documentation is wrong. It says:

> Returns the smallest power of 2 greater than i.

But it should be

> greater than or equal to i.

Mistake in code? Or mistake in documentation?

This function is used only one place, in pio_swapm().

**Comment by jayeshkrishna** [comment]
Mistake in doc (as of the current code).
I am currently working on this code right now (and fixing docs as needed). You can assign this to me.

**Comment by jayeshkrishna** [comment]
Doc added in 5fbe4c235f7dc4391324a6ed49f6a4bf194e12da

**Comment by edhartnett** [comment]
OK, sounds good.
