### ISSUE TITLE
pair() function may be incorrect

### ISSUE THREAD

**Issue by edhartnett** [NCAR/ParallelIO#646]
In pio_spmd.c we have this function:

```
/**
 * Given integers p and k between 0 and np-1,
 * if (p+1)^k <= np-1 then return (p+1)^k else -1.
 *
 * @param np
 * @param p integer between 0 and np - 1.
 * @param k integer between 0 and np - 1.
 * @returns (p + 1) ^ k else -1.
 */
int pair(int np, int p, int k)
{
    int q = (p + 1) ^ k ;
    int pair = (q > np - 1) ? -1 : q;
    return pair;
}

```
I didn't notice this until I tested it, but of course the ^ does not work as exponentiation in C, it is actually the bitwise XOR function, which I suspect is not what is intended here. Should pair be using the pow function instead?

**Comment by jayeshkrishna** [comment]
There are several bugs in the pio_swapm() function. For now, please don't create any more issues related to functions in pio_spmd.c - we can do that once I finish the cleanup (once #637 is done).

**Comment by jayeshkrishna** [comment]
xor is what is required here though.

**Comment by edhartnett** [comment]
OK, very good. Suggest you mention the xor in the documentation for this function.

**Comment by jayeshkrishna** [comment]
Although the code in pair() function can be refactored, there are no bugs in the function. Closing this issue.
