### ISSUE TITLE
21 Fortran tests failed memory leak check

### ISSUE THREAD

**Issue by dqwu** [NCAR/ParallelIO#681]
This issue is caused by PR #680, which is reproducible in both develop and master branches.

[Root cause of the leaks]
In flush_buffer(), pio_darray_int.c, the code is updated by the PR such that if PIOc_write_darray_multi() returns an error, flush_buffer() will return that error, without executing the following clean up code.
```
/* If there are any variables in this buffer... */
if (wmb->validvars > 0)
{
    /* Write any data in the buffer. */
    if ((ret = PIOc_write_darray_multi(ncid, wmb->vid,  wmb->ioid, wmb->validvars,
                                       wmb->arraylen, wmb->data, wmb->frame,
                                       wmb->fillvalue, flushtodisk)))
        return pio_err(NULL, file, ret, __FILE__, __LINE__);

    wmb->validvars = 0;

    /* Release the list of variable IDs. */
    brel(wmb->vid);
    wmb->vid = NULL;
    ...
}
```

[Code that triggers the leaks]
On the other hand, in PIOc_write_darray_multi(), pio_darray.c, the code is updated by the PR to check returned value from flush_output_buffer(). For the 21 failed Fortran tests, flush_output_buffer() does return an error code (e.g. PIO_EBADID), which is then returned by PIOc_write_darray_multi().
```
/* Flush data to disk. */
if (file->iotype == PIO_IOTYPE_PNETCDF)
    if ((ierr = flush_output_buffer(file, flushtodisk, 0)))
        return pio_err(ios, file, ierr, __FILE__, __LINE__);
```

[How to fix]
We should make sure that the clean up code is executed even if PIOc_write_darray_multi() fails.

**Comment by edhartnett** [comment]
Let me fix this since I made the change.

**Comment by edhartnett** [comment]
I have a PR up now, take a look...

**Comment by edhartnett** [comment]
@dqwu do your tests fail automatically? Or do you check the results manually?

In the past when I have tried to do automatic valgrind testing, I get so many false positives with MPI programs, that it doesn't work. Do you have some settings that catch only memory leaks?

I would like to make this part of my one automatic testing...

**Comment by dqwu** [comment]
@edhartnett 
You can put something like below to your build script (change the paths). 
--error-exitcode=1 is set such that a test will fail if Valgrind finds leaks. --undef-value-errors=no so uninitialized values will not be count as errors.
PIO_VALGRIND_CHECK=ON to turn on Valgrind check for CMake
CFLAGS="-O0 -g" FFLAGS="-O0 -g" to show line numbers in the Valgrind log.

```
export VALGRIND_OPTS="--error-exitcode=1 --undef-value-errors=no"

CFLAGS="-O0 -g" FFLAGS="-O0 -g" CC=mpicc FC=mpifort cmake \
-DHDF5_PATH=/soft/apps/packages/climate/hdf5/1.8.16-parallel/gcc-6.2.0 \
-DNetCDF_PATH=/soft/apps/packages/climate/netcdf/4.4.1c-4.2cxx-4.4.4f-parallel/gcc-6.2.0 \
-DPnetCDF_PATH=/soft/apps/packages/climate/pnetcdf/1.7.0/gcc-6.2.0 \
-DPIO_VALGRIND_CHECK=ON \
..
```

**Comment by edhartnett** [comment]
Thanks I'll try it...
