### ISSUE TITLE
In iodesc_t rename basetype to mpitype

### ISSUE THREAD

**Issue by edhartnett** [NCAR/ParallelIO#690]
We keep the MPI type in a field called basetype. Let's change that field to be "mpi_type" which is more clear.

**Comment by jayeshkrishna** [comment]
I don't know about that. I think basetype is a better name. It is @jedwards4b 's call.

**Comment by edhartnett** [comment]
On further examination of the code, I am beginning to wonder whether basetype is really needed at all.

It is used here:
```
                          /* Call the netCDF functions to write the data. */
                            if (basetype == MPI_INTEGER)
                            {
                                LOG((3, "about to call nc_put_vara_int()"));
                                ierr = nc_put_vara_int(file->fh, vid[nv], start, count, (const int *)bufptr);
                            }
                            else if (basetype == MPI_DOUBLE || basetype == MPI_REAL8)
                            {
                                LOG((3, "about to call nc_put_vara_double()"));
                                ierr = nc_put_vara_double(file->fh, vid[nv], start, count, (const double *)bufptr);
                            }
                            else if (basetype == MPI_FLOAT || basetype == MPI_REAL4)
                            {
                                LOG((3, "about to call nc_put_vara_float()"));
                                ierr = nc_put_vara_float(file->fh, vid[nv], start, count, (const float *)bufptr);
                            }
                            else
                                fprintf(stderr, "Type not recognized %d in pioc_write_darray\n", (int)basetype);
```

There are several issues with the above code. (See #674, for example).

But what occurs to me is that if we carried the pio type of the variable in the variable info array, we would not need basetype at all.

Furthermore, it seems like that would easily allow us to mix pio_types (with a little extra work to handle different lengths) in the same decomposition. That is, the decomposition would still contain variables with the same dimensions, but they could be of any type (float, double, short, all mixed in).

I am not going to attempt this until I have a bunch of test code in place (#669, #670, #671, #665, #664).

**Comment by edhartnett** [comment]
Some additional basetype confusion:

int PIOc_InitDecomp(int iosysid, int basetype, int ndims, const int *dims, int maplen,
                    const PIO_Offset *compmap, int *ioidp, const int *rearranger,
                    const PIO_Offset *iostart, const PIO_Offset *iocount)

But this basetype is expected to be a PIO type. It is converted to MPI type in malloc_iodesc(). So basetype sometimes means PIO type and sometimes MPI type. I think we can clear that up...

**Comment by edhartnett** [comment]
I believe that we will not need basetype at all. See #473.

**Comment by edhartnett** [comment]
I have changed cases where basetype was actually a PIO type into pio_type. So all the remaining uses of basetype in the code are MPI types.

**Comment by edhartnett** [comment]
We now have the PIO type in the iodesc, field piotype.

I will change the name of basetype to mpitype, so it will match and be more clear. In the code now, basetype is always the mpi type, never the PIO type of the variable.
