### ISSUE TITLE
What is difference between llen and ndof in io_desc_t?

### ISSUE THREAD

**Issue by edhartnett** [NCAR/ParallelIO#700]
In io_desc_t we have:

```
    /** Local size of the decomposition array. */
    int ndof;
    /** Length of the iobuffer on this task for a single field */
    PIO_Offset llen;

```

Aren't these always the same?

**Comment by jedwards4b** [comment]
ndof is on a compute node and llen is on an io node

**Comment by edhartnett** [comment]
Are they always the same number?

**Comment by edhartnett** [comment]
I have changed the comments in pio.h to read:

```
    /** Local size of the decomposition array on the compute node. */
    int ndof;
    /** Length of the iobuffer on this task for a single field on the
     * IO node. */
    PIO_Offset llen;

```

Still not sure if these refer to the same array size. ;-) Are they sometimes different?

No doubt all will become clear to me as I continue to test and examine code...

**Comment by jedwards4b** [comment]
On each compute task the application program passes a compmap array of length ndof.    
This array describes the arrangement of data in memory on that task.

These arrays are gathered and rearranged to the io-nodes (which are sometimes collocated with compute nodes), each io task contains data from the compmap of one or more compute tasks in the iomap array and the length of that array is llen.

**Comment by edhartnett** [comment]
OK, so since the IO nodes are aggregating data from compute nodes, and there are in general more data nodes than compute nodes (at least in the async case) I can expect that llen will be much larger than ndof, because one IO node will hold a lot more data that one compute node.

Do I have that right? I will add your explanation to the comments in the code...

**Comment by jedwards4b** [comment]
yes
