### ISSUE TITLE
recent commit breaks cesm 

### ISSUE THREAD

**Issue by jedwards4b** [NCAR/ParallelIO#719]
I have been testing in cesm, most recently trying to track down a bug in netcdf4 on the ncar cheyenne system.   I recently updated to the head of master and got a new error: 

0:ERROR: 0 NetCDF: Not a valid ID err_num = -33 fname = /glade/scratch/jedwards/forbrian/cesm2_0_alpha06/cime/externals/pio2/src/clib/pio_darray.c line = 261

I've traced this back to commit f9bee9e Merge pull request #680 from NCAR/ejh_ret_codes

I do not get this error in commit 6ad90b0 Merge pull request #651 from NCAR/jayeshkrishna/more_1d_tests

**Comment by edhartnett** [comment]
Can you try with a new master?

What is happening when the error occurs? Can you turn on logging?

Thanks

**Comment by edhartnett** [comment]
The line in question is here:

```
    /* Flush data to disk. */
    if (file->iotype == PIO_IOTYPE_PNETCDF)
        if ((ierr = flush_output_buffer(file, flushtodisk, 0)))
            return pio_err(ios, file, ierr, __FILE__, __LINE__);

```

Unfortunately a lot is going on here. Can you try a sync earlier in your code to see if that triggers the error?

**Comment by edhartnett** [comment]
Looking at the code, another very important question is what IO type were you using at the time of the error?

**Comment by edhartnett** [comment]
What I would dearly love would be to get a copy of CESM running on my machine so I could do these tests myself. Is that possible?

**Comment by jedwards4b** [comment]
I am using type pnetcdf and yes I found the problem at the head of master and traced back to this commit.   Here is the end of the log for task 1 (first io task)
```	1 about to write darray for iotype = 1
	1 pio_write_darray_multi_nc nvars = 6 iodesc_ndims = 2 basetype = 10 maxregions = 1 llen = 3888 maxiobuflen = 3888 num_aiotasks = 4
	1 PIOc_inq_var ncid = 17 varid = 1
		1 pio_get_file ncid = 17
		1 got file and iosystem
		1 Calling the netCDF layer
		1 from pnetcdf ndims = 3
		1 PIOc_inq_var ndims = 3 ierr = 0
		1 PIOc_inq_var about to Bcast ndims = 3 ios->ioroot = 1
		1 PIOc_inq_var Bcast ndims = 3
		1 fndims = 3 tsize = 8
			1 maxregions = 1
			1 start[0] = 0 count[0] = 1
			1 start[1] = 0 count[1] = 27
		1 PIOc_sync ierr = 0
		1 pio_get_iosystem_from_id iosysid = 65536
```

**Comment by jedwards4b** [comment]
Task 0 has this though
```	0 PIOc_inq_var ncid = 17 varid = 1
		0 pio_get_file ncid = 17
		0 got file and iosystem
		0 PIOc_inq_var about to Bcast ndims = 0 ios->ioroot = 1
		0 PIOc_inq_var Bcast ndims = 3
		0 fndims = 3 tsize = 8
	0 PIOc_strerror pioerr = -33
ERROR: 0 NetCDF: Not a valid ID err_num = -33 fname = /glade/scratch/jedwards/forbrian/cesm2_0_alpha06/cime/externals/pio2/src/clib/pio_darray.c line = 263
		0 pio_err chose error handler = -51
```

**Comment by jedwards4b** [comment]
Task 0 is not an io-task so I assume there is an if(io) block missing someplace?

**Comment by jedwards4b** [comment]
yes you can get cesm: start with git clone https://github.com/ESMCI/cime.git

**Comment by edhartnett** [comment]
OK, I will take a stab at this tomorrow first thing...
