### ISSUE TITLE
Why does needsfill go with decomposition?

### ISSUE THREAD

**Issue by edhartnett** [NCAR/ParallelIO#788]
From pio_darray.c:

```
    /* If we need a fill value, get it. */
    if (iodesc->needsfill)

```

Why does the decomposition know or care whether we are using fill values?

**Comment by jedwards4b** [comment]
If you are using the subset rearranger and not using the netcdf fill mode then you need to do an extra write to fill in the holes with the fill value.

**Comment by edhartnett** [comment]
OK thanks I will add a comment to the code...

**Comment by edhartnett** [comment]
This comment has been added to the code, so I will close this issue.
