### ISSUE TITLE
More work on init async API

### ISSUE THREAD

**Issue by edhartnett** [NCAR/ParallelIO#806]
Jim notes:

> I think that there is something wrong here - are you assuming that this routine will define the comms for each component? and that the io tasks will consist of tasks 0, num_io_tasks-1 of comm world? I think that these are generally bad assumptions - the application task should define and pass in it's comp_comms along with world
> and the io_comm should be what's left of world when all the comp_comms are removed.

**Comment by edwardhartnett** [comment]
Thanks to Jim, this is now complete.
