### ISSUE TITLE
Should we support netCDF-4.3.3.1?

### ISSUE THREAD

**Issue by edhartnett** [NCAR/ParallelIO#815]
Over the weekend Jim tried to build PIO with netCDF-4.3.3.1/pnetcdf-1.6.1. The test for rearranger options hangs.

Checking out the repo at various points shows that these tests always failed with netCDF-4.3.3.1. We didn't notice because we were not testing with 4.3.3.1 anywhere.

If PIO is going to work with 4.3.3.1, changes are apparently required.

Or we could just say that we don't support 4.3.3.1 anymore, which is a year old, and tell users to upgrade to a more recent version of netCDF. I think we should do this, unless there is some very strong reason not to.

**Comment by mitoya** [comment]
Sorry to disturb you.
Now I use pio inside CESM1.2.2, but I cannot exactly tell its version, maybe 1.X.X/1.8.X/1.7.X
I build it with netCDF 4.4.1.1，netCDF-Fortran 4.4.4 ，pnetcdf-1.８.1，hdf5-1.8.16 which compiled with INTEL MPI/C/Fortran 2017.
If less than 4000cores, the model runs ok, but when I use >4000 in ocean and ice, the model crashs and stops.
i found that the error appears when the model write/output data (there are so many, so I cut some here):
=====================================================
 /cesm1_2_2/models/utils/pio/box_rearrange.F90.in         752
        1006                  2808                  1640                     0
                     0                  1410                     0
                  3600                  1412                    42
 box_rearrange::compute_dest:: ERROR: no destination found for compdof=
               5906809
 box_rearrange::compute_dest:: INFO: gsize=        3600        2400          42
 box_rearrange::compute_dest:: INFO: nioproc        1500  ioproc            0
  ioindex                     -1
 box_rearrange::compute_dest:: INFO io            1  start=
                     1                     1                     1  count=
                  3600                     1                    42
=====================================================

so i want to know, is it the same error with yours? how can i solve it?
Thanks.

**Comment by jayeshkrishna** [comment]
@mitoya : Can you create a new issue (rather than updating an issue)?

**Comment by mitoya** [comment]
Sorry to disturb you.
Now I use pio inside CESM1.2.2, but I cannot exactly tell its version, maybe 1.X.X/1.8.X/1.7.X
I build it with netCDF 4.4.1.1, netCDF-Fortran 4.4.4, pnetcdf-1.8.1, hdf5-1.8.16 which compiled with INTEL MPI/C/Fortran 2017.
If less than 4000cores, the model runs ok, but when I use >4000 in ocean and ice, the model crashs and stops.
i found that the error appears when the model write/output data (there are so many, so I cut some here):
====================================================
 /home/xwan/cesm/cesm1_2_2/models/utils/pio/box_rearrange.F90.in         752
       1006                  2808                  1640                     0
         0                  1410                     0
      3600                  1412                    42
 box_rearrange::compute_dest:: ERROR: no destination found for compdof=
               5906809
 box_rearrange::compute_dest:: INFO: gsize=        3600        2400          42
 box_rearrange::compute_dest:: INFO: nioproc        1500  ioproc            0
 ioindex                     -1
====================================================

so i want to know, is it the same error with yours? how can i solve it?
Thanks.

**Comment by mitoya** [comment]
sorry , the character font is so odd....

**Comment by jedwards4b** [comment]
I think that requiring a newer netcdf is okay.  It turns out that the cdash test that I run on yellowstone is already using 4.4.1 and that's why it wasn't picking up this problem.
