### ISSUE TITLE
Suggest we implement PIOc_strerr()

### ISSUE THREAD

**Issue by edhartnett** [NCAR/ParallelIO#82]
The practice in the netcdf library is to pass back error codes, which are integers, and provide a function nc_strerr() which will return an error string for each error code. We make use of this in PIO error handling, when we print out the netCDF error message.

In netCDF, unless the log_level is set, the library will never put out any string output to stdout, except through nc_strerr(). The reasoning is that libraries should not assume that anyone is reading stdout, nor should they presume to output anything to stdout, without express user permission. For example, a GUI using the netCDF API is not going to be happy with text messages on stdout.

I suggest that PIO adopt this approach. In addition to the reasons given above, running the task on potentially tens of thousands of processors means we have to be careful about outputting to stdout.

But in PIO, we have added some error conditions that are not in the netCDF library. In these cases we have our code print out an error string, for example:

	if (!(CN_bpool = malloc(PIO_CNBUFFER_LIMIT)))
	{
	    char errmsg[180];
	    sprintf(errmsg,"Unable to allocate a buffer pool of size %d on task %d:"
		    " try reducing PIO_CNBUFFER_LIMIT\n", PIO_CNBUFFER_LIMIT, ios.comp_rank);
	    piodie(errmsg, __FILE__, __LINE__);
	}

Instead, we should have a PIOc_strerr(). We should define additional error codes which do not overlap with netCDF error codes. Then, when an error is encountered, the code only has to return an error code, and not worry about the error message. The error handling routine can then print out the error message, so the user will still see it.

The advantage will be that all PIO error strings are in one place, where they can be consistently maintained, and the code throughout the library will be cleaner without the error strings. And the user only sees the output on stdout when they request it.

**Comment by jedwards4b** [comment]
Yes please implement this change.  Thanks

**Comment by edhartnett** [comment]
Merged to master...
