### ISSUE TITLE
have PIOc_write_darray return error if given an incorrect fill value parameter

### ISSUE THREAD

**Issue by edhartnett** [NCAR/ParallelIO#83]
It's not clear why PIOc_write_darray takes a fill value parameter.

Shouldn't it just use whatever fill value is set for that variable?

Seems like we risk users passing an incorrect value, and then thinking they are getting a fill value, when in fact they are just polluting the data.

So I wonder why the darray functions take a fill value?

**Comment by edhartnett** [comment]
Seems like there is some buggy code here. If the user does not provide a fill value, the default fill value for the type is used. This ignores any fill value that the user has already set.

So if the user sets a fill value of -9999 and then call PIOc_write_darray() without providing a fill value argument, the default fill value will be used for those writes.

A similar error condition will occur if the user sets a fill value, and then provides a different fill value to PIOc_darray().

**Comment by edhartnett** [comment]
I think we are going to want to eliminate the fill value parameter from the function call.

I think what we want to do instead is look up the netCDF fill value. (Attribute _FillValue). If that is not there, use the default fill value for the type.

**Comment by jayeshkrishna** [comment]
Are we changing the API here?

**Comment by edhartnett** [comment]
We may, but not necessarily the Fortran API.

**Comment by jayeshkrishna** [comment]
I thought the consensus was not to change the API

**Comment by edhartnett** [comment]
The C API may no longer be changed without good cause. In this case there is a bug in the actual API. We should not be asking the user to pass a new fill value. We should use the default, or the fill_value set in the file. If the user wants to set a fill value, he or she should do so in the standard way.

If we need to maintain backwards C compatibility we can add to the API, instead of changing it, but I think in this case the number of C API users is still low and so we can make this change. 

Areas of the C API that will be much more resistant to change are those functions that model netCDF functions, and use a copy of their parameters. However this function is a PIO-only function.

At the next meeting I will explain in more detail the policy for C API changes to anyone who is interested.

The Fortran API is a different story. I also recommend that you don't change it without excellent reason, but I have no requirements there - I'm not using that for the netCDF integration.

**Comment by jayeshkrishna** [comment]
Bugs (in the code) should be fixed. But IMO the current capabilities of PIO should not be changed.

**Comment by edhartnett** [comment]
The problem code is in pio_darray.c:

    ```
/* If we need a fill value, get it. */
    if (iodesc->needsfill)
    {
	/* If the user passed a fill value, use that, otherwise use
	 * the default fill value of the netCDF type. Copy the fill
	 * value to the buffer. */
        if (fillvalue)
            memcpy((char *)wmb->fillvalue + tsize * wmb->validvars, fillvalue, tsize);
        else
        {
            vtype = (MPI_Datatype)iodesc->basetype;
            if (vtype == MPI_INTEGER)
            {
                int fill = PIO_FILL_INT;
                memcpy((char *)wmb->fillvalue + tsize * wmb->validvars, &fill, tsize);
            }
            else if (vtype == MPI_FLOAT || vtype == MPI_REAL4)
            {
                float fill = PIO_FILL_FLOAT;
                memcpy((char *)wmb->fillvalue + tsize * wmb->validvars, &fill, tsize);
            }
            else if (vtype == MPI_DOUBLE || vtype == MPI_REAL8)
            {
                double fill = PIO_FILL_DOUBLE;
                memcpy((char *)wmb->fillvalue + tsize * wmb->validvars, &fill, tsize);
            }
            else if (vtype == MPI_CHARACTER)
            {
                char fill = PIO_FILL_CHAR;
                memcpy((char *)wmb->fillvalue + tsize * wmb->validvars, &fill, tsize);
            }
            else
                return pio_err(ios, file, PIO_EBADTYPE, __FILE__, __LINE__);
        }
    }

```
This code will work fine as long as the caller passes the correct fill value. But if the caller has set the fill value (by setting a fill value attribute), then calls this function with an incorrect, or no fill value, then there will be two fill values in use and hilarious confusion will ensue.

I can see that we need the fill value to fill in values of missing data in the arrays we are using as buffers for data. What we should do is look up the fill value of the variable, instead of trusting the user to get it right.

I guess the plan is:

* Change this function to look up the fill value (instead of assuming defaults), when the caller passes a NULL fillvalue.

* Look up the fill value in all cases, and return an error when the caller passes in a fill value, and it is incorrect.

**Comment by edhartnett** [comment]
OK, the plan has been refined. In consultation with Jim, here is the new way forward:

OK, we need fill values to fill in missing areas of the global array before we write data with darray, right?

That's why PIOc_write_darray() takes a fill value parameter.

However, that simply invites user error, as noted in issue #83.

What I initially thought was that I could just change PIOc_write_darray() to look up the real fill value, and use that instead of the one provided by the user. But then that might impact performance, even though getting metadata from an open netCDF file does not involve disk access.

So how about we store a variable's fill value in the varinfo array? I load it up when a file is opened or a var is created, and change it if PIOc_set_fill() is called, or an attribute _FillValue put.

PIOc_write_darray() would then be changed to ignore the passed-in fill value, and a new version of PIOc_write_darray() can be provided without the fill value parameter.

Backward code compatibility will be maintained, but we will make it impossible for the user to set an incorrect fill value in their data.

**Comment by jayeshkrishna** [comment]
Just my 2c, I would prefer that we don't change current functionality but warn users when they set an unexpected fillvalue (Adding a new interface that does not take a fillvalue is a great idea - without changing the behaviour of the old interface).

**Comment by edhartnett** [comment]
@jayeshkrishna how about we return a PIO_EINVAL error code when an incorrect fill value is used?

**Comment by jayeshkrishna** [comment]
We could do that too (I just want to make sure that we capture these errors that might already be there in existing user code).

**Comment by edhartnett** [comment]
This is now working, at least with netCDF-4.4.1.1. Later versions of netCDF have some fill value issues, but I will track those separately.
