### ISSUE TITLE
check_and_reset_rearr_opts() should not silently reset options to defaults

### ISSUE THREAD

**Issue by edhartnett** [NCAR/ParallelIO#837]
The function check_and_reset_rearr_opts() in pioc_support.c has this code:

 ```
   /* Reset to defaults, if needed (user did not set it correctly) */
    if (ios->rearr_opts.comm_type == PIO_REARR_COMM_COLL)
    {
        /* Compare and log the user and default rearr opts for coll. */
        cmp_rearr_opts(&(ios->rearr_opts), &def_coll_rearr_opts);
        /* Hard reset flow control options. */
        ios->rearr_opts = def_coll_rearr_opts;
    }
    else if (ios->rearr_opts.comm_type == PIO_REARR_COMM_P2P)
 
```

Although it may seem helpful, we should not silently correct user options. If the user passes in bad options, we return PIO_EINVAL. If they then choose to go with the defaults, they can do that. Alternatively, they can correct their code to take advantage of whatever feature they were attempting to use,.

Correcting the user options will result in:
* users who think they are using a feature, but are not.
* confused support questions.
* code that is harder to test, maintain, and document.

The function check_and_reset_rearr_opts() can be broken into two functions, on to check, and one to initialize the opts. The initialization can give the user the default settings.

If the user attempts to change them to something incorrect, the check function can ensure that a PIO_EINVAL is returned to the user.

**Comment by jayeshkrishna** [comment]
I think we discussed this in a different issue (will dig it up). The code only resets arguments that are of no interest to the user (and we allow users to just pass default values for them).
We decided to have some more arg checking there.

**Comment by edhartnett** [comment]
OK, I am going to leave this ticket open for discussion of this issue for a bit.

Starting with tests, as always, I am going to write some simple tests for a few of the internal functions involved, to get the ball rolling and to build my understanding of what is going on.
