### ISSUE TITLE
Unreachable code in PIOc_read_darray()

### ISSUE THREAD

**Issue by edhartnett** [NCAR/ParallelIO#849]
In PIOc_read_daray() we have:

 ```
   /* Is a rearranger in use? */
    if (iodesc->rearranger > 0)
    {
        if (ios->ioproc && rlen > 0)
        {
            /* Get the MPI type size. */
            if ((mpierr = MPI_Type_size(iodesc->basetype, &tsize)))
                return check_mpi(file, mpierr, __FILE__, __LINE__);

            /* Allocate a buffer for one record. */
            if (!(iobuf = bget((size_t)tsize * rlen)))
                return pio_err(ios, file, PIO_ENOMEM, __FILE__, __LINE__);
        }
    }
    else
    {
        iobuf = array;
    }

```

There is another if statement later in the function as well.

I believe that iodesc->rearranger must be either 1 or 2, so it is never 0. Better to pioassert it and remove the unreachable code.

**Comment by jayeshkrishna** [comment]
I remember @jedwards4b mentioning in an issue before that the idea here was to explore cases where we don't use any rearrangers.

**Comment by edhartnett** [comment]
OK, cool. I will take it out for now.

For 2.2.0 a rearranger is required, and must be BOX or SUBSET.

Future versions of the code can do other things, but we will wait until we have a PR that implements a full feature, instead of leaving partial implementations in the code.
