### ISSUE TITLE
idx_to_dim_list() documentation incorrect?

### ISSUE THREAD

**Issue by edhartnett** [NCAR/ParallelIO#858]
In the docs for function idx_to_dim_list() (in pio_rearrange.c) we have:

```
 * Convert an index into a list of dimensions. E.g., for index 4 into a
 * array defined as a[3][2], will return 1 1.

```

In the new test file test_rearr.c (will be up for PR later today), I have this code, which demonstrates that the documentation is wrong about the answer it promises:

 ```
   /* The case given in the function docs. */
    int ndims2 = 2;
    int gdims2[2] = {3, 2};
    PIO_Offset idx2 = 4;
    PIO_Offset dim_list2[2];

    /* According to function docs, we should get 1,1 */
    idx_to_dim_list(ndims2, gdims2, idx2, dim_list2);
    printf("dim_list2[0] = %lld\n", dim_list2[0]);
    printf("dim_list2[1] = %lld\n", dim_list2[1]);

    /* This is not the result that the documentation promised! */
    if (dim_list2[0] != 2 || dim_list2[1] != 0)
        return ERR_WRONG;

```

According to the docs, I should get 1,1, but instead I get 2,0.

What the heck does this function do anyway? What do we mean index?

Does this convert a multi-dimensional index into a one-dimensional one?

Part of #857.

**Comment by jedwards4b** [comment]
The intention is to map a one-d index to a multi-d array.   But I don't think that's what it's doing,
I'll have to dig deeper into the code and figure out how this is working.
