### ISSUE TITLE
test_rearr has memory leaks in develop branch

### ISSUE THREAD

**Issue by dqwu** [NCAR/ParallelIO#863]
Reported by LeakSanitizer build:
http://my.cdash.org/testDetails.php?test=30291767&build=1150084

**Comment by jayeshkrishna** [comment]
brel is missing for ior4 (alloc in test_rearr.c:404) in test_rearr.c

**Comment by edhartnett** [comment]
Stand by, I will fix...

**Comment by edhartnett** [comment]
Fixed and merged to develop.
