### ISSUE TITLE
Init rearr_opts as all 0, remove initialization function

### ISSUE THREAD

**Issue by edhartnett** [NCAR/ParallelIO#868]
If we change the order of two enums (PIO_REARR_COMM_FC_DIR and PIO_REARR_COMM_TYPE) so that the default selection is 0, then we can init the rearr_opts in all cases with no more than a calloc, removing the initialization code everywhere.

**Comment by jayeshkrishna** [comment]
Can you provide more information? Are you referring to the call to init_rearr_opts() in pioc_init_intracomm() ?
I would vote for clarity in the code here. Having explicit initialization of a structure makes the intent clear and can be changed easily later on.

**Comment by edhartnett** [comment]
In C the convention is to use 0 for initialization of structs, and then allocate the struct with a calloc. This is very efficient, takes the fewest lines of code, and is a very firmly established and well-known C idiom. In fact, this is the whole reason for the calloc() function.

You can see this in use in the malloc_iodesc() function (and other places in the liibrary):

```
    /* Allocate space for the io_desc_t struct. */
    if (!(*iodesc = calloc(1, sizeof(io_desc_t))))
        return pio_err(ios, NULL, PIO_ENOMEM, __FILE__, __LINE__);

```

After the calloc we only need to initialize the members we don't want to be 0. If we are careful when we design our structs, we can arrange it so that everything initializes nicely to 0. That reduces the initialization code to nothing, which is my favorite amount of code to maintain.

This convention is now used in many places in the PIO library, and can be used uniformly for all structs and many arrays.

The clearest and most correct code results if we stick to C conventions and not try to invent our own way of doing things. Clarity is achieved, and complexity managed, by removing lines that are excess to requirements and taking full advantage of the C language as it is intended to be used.

All library code has to be tested, and that test code has to be written and maintained as well. So it is not free to throw in some code that doesn't do anything. It is costly. Typically I would expect you to submit unit tests with all C code, but that has not been the case on this project until recently. I trust that in the future, we will see C tests with all new C code. When programmers are responsible for writing their own tests, there is a positive effect on code size, clarity, and documentation. You will become the first user of your code, and you will be the first to see whether the documentation is clear, the parameters appropriate, and the edge-cases handled properly.

I will continue to remove unneeded code from the library, whomever is the author, including me. If it is any consolation, I am as hard on my own code, and Jim's. (He will attest to that, I am sure!)

**Comment by jayeshkrishna** [comment]
In this case the rearranger has many tuning knobs and I would prefer explicitly specifying what we initialize it to.

**Comment by edhartnett** [comment]
Sorry, I do not find that case very compelling.

**Comment by gold2718** [comment]
Is this a C idiom exercise or a software engineering exercise? In the SE world, code clarity and intent trumps 'default behavior'. Yes, we all know that many things in C are initialized to zero by default, however, this is not the point in this case. There are parameters to indicate behavior and explicitly stating the intended default behavior is code engineering. Also having a test that makes sure that default behavior is followed is part of the process.
Belt _and_ suspenders

**Comment by edhartnett** [comment]
I am going to close this issue.
