### ISSUE TITLE
Memory leaks in some tests with PIO_USE_MALLOC

### ISSUE THREAD

**Issue by edhartnett** [NCAR/ParallelIO#891]
Recent fixes of build/config problems have caused us to start valgrind testing with PIO_USE_MALLOC (as well as the bget testing we have been doing for several months now).

The PIO_USE_MALLOC build has some leaks. We believe at least some are leaks that have been in the code for a while, but have never been noticed.

All the leaks are from pio_darray.c, line 158

```
if (!(vdesc0->iobuf = bget(1)))
    return pio_err(ios, file, PIO_ENOMEM, __FILE__, __LINE__);

```

**Comment by dqwu** [comment]
line 158 of pio_darray.c was a new line added by PR #890. It seems that for PIO_USE_MALLOC=OFF it is freed at some place, but for PIO_USE_MALLOC=ON it is not?

**Comment by jedwards4b** [comment]
It should be released in both cases at 1236 of pio_darray_int.c

**Comment by edhartnett** [comment]
My (possibly incorrect) current understanding:

The reason it works in bget is that bget recycles the memory, and so the memory gets freed in the end.

But using malloc, there is no recycling of memory. So when vdesc0->iobuf is allocated for a pnetcdf test case, it is not always freed.

**Comment by jedwards4b** [comment]
I guess that I would first like to understand if there are cases where the code is not reaching the 
brel referenced above and if so why not?

**Comment by jedwards4b** [comment]
I just went through the test_darray_1d test and it looks fine.   Is this test showing a memory leak and if not can you give me a list which are.

**Comment by dqwu** [comment]
@jedwards4b 
Only 21 Fortran tests show the leaks, the list is here:
http://my.cdash.org/viewTest.php?onlyfailed&buildid=1153104

**Comment by jedwards4b** [comment]
And these are showing the leak at that line?  I went through pio_decomp_tests_1d and checked that 
all of the tasks that are allocating that space are also freeing it.   I'm not seeing any mismatch.

**Comment by jedwards4b** [comment]
Finally I was able to reproduce, I've created a branch memleak_fix that I think fixes the problem.  Could you please try again with this branch?

**Comment by dqwu** [comment]
@jedwards4b 
I merged memleak_fix to develop locally and the memory leaks are fixed, thanks.

**Comment by edhartnett** [comment]
This has been merged to master. I will close this ticket.
