### ISSUE TITLE
test_pioc failed on develop branch

### ISSUE THREAD

**Issue by dqwu** [NCAR/ParallelIO#917]
Reported by AddressSanitizer build:
http://my.cdash.org/testDetails.php?test=30440214&build=1154798

I can also reproduce it in my local machine with a regular build, kind of segmentation fault.

Not reproducible in master yet. Please check recent PRs that are merged to develop.

**Comment by edhartnett** [comment]
Stand by, I will take a look...

**Comment by dqwu** [comment]
For this test, ios->ioranks pointer could be NULL in the code below (pio_rearrange.c:1269):
```
for (int i = 0; i < nioprocs; i++)
{
    int io_comprank = ios->ioranks[i];
    recvlths[io_comprank] = 1;
    rdispls[io_comprank] = i * tsize;
}
```

**Comment by edhartnett** [comment]
I have turned off that async test on the branch and on the develop branch. That will let me get the rest of today's work merged after cdash passes on the next round.

I will swing around again at that test tomorrow...

**Comment by edhartnett** [comment]
This is now building again. I will close this issue.
