### ISSUE TITLE
test_rearr failed AddressSanitizer check (invalid free)

### ISSUE THREAD

**Issue by dqwu** [NCAR/ParallelIO#923]
See http://my.cdash.org/testDetails.php?test=30501383&build=1156560
It is also reproducible in the master branch after PR #920 was merged.

The issue is that the pointer iodesc.sindex is not initialized to NULL in the code below, which might get a random value (a wild pointer). The behavior is undefined when the code is trying to free on this wild pointer which was not malloc()-ed.
```
int test_compute_counts_box(MPI_Comm test_comm)
{
    ...
    io_desc_t iodesc;
    ...
    /* Initialize iodesc. */
    iodesc.rearranger = PIO_REARR_BOX;
    iodesc.ndof = 4;
    ...
    if ((ret = compute_counts(&ios, &iodesc, maplen, dest_ioproc, dest_ioindex, test_comm)))
        return ret;
    ...
    /* Free resources allocated in compute_counts(). */
    free(iodesc.scount);
    free(iodesc.sindex);
    free(iodesc.rcount);
    free(iodesc.rfrom);
    free(iodesc.rindex);
}
```
Note that in compute_counts(), sindex will not be malloc-ed if it is non-NULL.
```
if (iodesc->sindex == NULL && iodesc->ndof > 0)
    if (!(iodesc->sindex = malloc(iodesc->ndof * sizeof(PIO_Offset))))
        return pio_err(ios, NULL, PIO_ENOMEM, __FILE__, __LINE__);
```
To fix this issue, we should initialize iodesc.sindex (to NULL) like we do for other struct members. It is suggested to initialize other pointers that will be freed (scount, rcount, rfrom, rindex) as well.

**Comment by edhartnett** [comment]
I will take a look first thing tomorrow morning...
