### ISSUE TITLE
mpi-serial build broken

### ISSUE THREAD

**Issue by jedwards4b** [NCAR/ParallelIO#925]
undefined reference to `MPI_Type_create_hvector'
I thought that there was a workaround in the code for this, did it get removed?
http://my.cdash.org/buildSummary.php?buildid=1157043

**Comment by edhartnett** [comment]
You should just define the new function in your MPI serial library. It is
exactly the same as MPI_Type_create_hvector except for the name.

**Comment by edhartnett** [comment]
Sorry, I meant its the same as MPI_Type_hvector.

**Comment by jedwards4b** [comment]
I will work on getting a change into the mpi-serial library but it's going to take a bit of time, can you please put back the workaround for backward compatibility.

**Comment by edhartnett** [comment]
Yes, I can do that. Stand by I will get up a PR...
