### ISSUE TITLE
pio_finalize should not free comp_comm

### ISSUE THREAD

**Issue by jedwards4b** [NCAR/ParallelIO#94]
Since pio did not create the comp_comm in the intracomm case - it shouldn't be freeing it in pio_finalize.   Do you agree?

**Comment by edhartnett** [comment]
Yes, I agree. The same is true for io_comm, and I also see that I am in any case only closing the first of potentially many comp_comms, so let me doublecheck that I didn't make that same mistake elsewhere...

**Comment by jedwards4b** [comment]
Thanks you're correct.
