### ISSUE TITLE
bfreespace() does not work with PIO_USE_MALLOC

### ISSUE THREAD

**Issue by dqwu** [NCAR/ParallelIO#940]
The utility function bfreespace() only works when the bget package is actually used.
```
void bfreespace(bufsize *totfree, bufsize *maxfree)
{
    struct bfhead *b = freelist.ql.flink;
    *totfree = 0;
    *maxfree = -1;
    while (b != &freelist) {
        ...
    }
}
```
If we are using native malloc (PIO_USE_MALLOC=ON), tofree will be 0 and maxfree will be -1 with this utility function being called. This will affect the following client code in pio_darray.c (maxfree is negative so needflush will always be set to true):
```
/* Find out how much free, contiguous space is available. */
bfreespace(&totfree, &maxfree);

/* maxfree is the available memory. If that is < 10% greater than
 * the size of the current request needsflush is true. */
if (needsflush == 0)
    needsflush = (maxfree <= 1.1 * (1 + wmb->validvars) * arraylen * tsize);
```
If PIO_USE_MALLOC=ON, is the behavior of the client code above as expected? Do we need special handling for this case as bfreespace() does not work?

**Comment by jedwards4b** [comment]
Between this issue and #877 I think I am beginning to understand why I was seeing more flushes than I expected the last time I checked performance in cesm.   I think that we do need special handling here - we need to try the malloc first and call flush if the malloc fails and then try the malloc again.
