### ISSUE TITLE
Incorrect code for sync call at end of PIOc_write_darray()?

### ISSUE THREAD

**Issue by edhartnett** [NCAR/ParallelIO#941]
At the end of PIOc_write_darray() we have:

```
    /* Call the sync when ??? */
    if (wmb->validvars >= iodesc->maxbytes / tsize)
        PIOc_sync(ncid);

```
As I understand the code better, I wonder if this is incorrect.

The validvars value refers to the number of vars/records currently in the multibuffer.

The maxbytes/tsize is the number of data values that can fit in the iodesc. Seems like validvars will usually be < iodesc->maxbytes / tsize.

**Comment by jedwards4b** [comment]
I agree, that looks wrong.

**Comment by edhartnett** [comment]
When I remove this code, all tests continue to pass. I will submit a PR. This should improve performance.
