### ISSUE TITLE
do we really always need  MPI_Alltoallw?

### ISSUE THREAD

**Issue by edhartnett** [NCAR/ParallelIO#950]
In some places in the code (example: compute_counts() in pio_rearrange.c) we are using pio_swapm() when seemingly a simpler MPI call would do the job.

Is there a reason to always use pio_swapm()?

**Comment by jedwards4b** [comment]
We always use swapm so that the mpi comm calls are isolated and an optimization (or bug) in a given mpi implementation can be made with minimal changes in pio.   Having said that I am aware of at least one place where pio_swapm could be replaced with the simpler pio_gatherv.

**Comment by edhartnett** [comment]
I note that there are other places where MPI calls like MPI_Gather() are used directly (for example in subset_rearrange_create()).

**Comment by edhartnett** [comment]
I will close this issue. If I want to change any of the existing all to all gathers, I will do so under another ticket.
