### ISSUE TITLE
Add test with a scalar var

### ISSUE THREAD

**Issue by edhartnett** [NCAR/ParallelIO#961]
What happens to PIO with scalar vars (number of dims = 0)?

**Comment by gold2718** [comment]
Global attributes

**Comment by gold2718** [comment]
Why is this marked as an enhancement?

**Comment by edhartnett** [comment]
Not sure what you are asking about global attributes. Those are reasonably well tested, I think.

I mark this as an enhancement because I do not know that there is a bug. I just believe we have no C tests of scalar vars, so adding such a test would be an enhancement.

**Comment by gold2718** [comment]
Sorry, I read the question but didn't review the issue title. I need to get a better email reader . . .
