### ISSUE TITLE
sizeof MPI_Offset not working with mpiserial lib

### ISSUE THREAD

**Issue by jedwards4b** [NCAR/ParallelIO#963]
It looks like the test for MPI_Offset size is happening before the MPISERIAL path is determined and so the test is failing with "cannot find mpi.h"

**Comment by edhartnett** [comment]
I have a fix for this that just sets the sizeof MPI_Offset to 8 for mpi serial builds.

A cleaner way to do this might be to set the CFLAGS etc. to find the mpiserial library, instead of the usual mpi library, without any CMake settings being involved.

I will have a PR up shortly.

**Comment by edhartnett** [comment]
OK, sounds good.

**Comment by edhartnett** [comment]
This was fixed in PR #965.
