### ISSUE TITLE
variables with and without unlimdim 

### ISSUE THREAD

**Issue by jedwards4b** [NCAR/ParallelIO#973]
We need a test in which two variables, one with and one without an unlimited dimension but defined with the same iodesc are written using pio_darray.  I think that this is currently broken.

**Comment by jayeshkrishna** [comment]
I agree. I am seeing this issue with some CLM writes on ACME side.

**Comment by jayeshkrishna** [comment]
I can add these tests.

**Comment by jayeshkrishna** [comment]
Right now it looks like the code assumes all variables sharing the iodesc have the same number of dimensions as the first variable in the list. I am planning to add tests to test this scenario.

**Comment by jedwards4b** [comment]
Thanks for jumping on this so quickly - yes I found the problem in clm, I will have a branch with the new test shortly.

**Comment by jedwards4b** [comment]
It used to be that each new variable was checked to have the same number of dimensions as the first in the list before it was added to the list - so checking only the first one was okay.   Not sure when this got lost.

**Comment by jedwards4b** [comment]
See test test_darray_multivar2.c in branch multivar2_test for a demonstration of the problem.

**Comment by edhartnett** [comment]
Do you guys want me to take a stab at fixing this one?

**Comment by jedwards4b** [comment]
Okay with me, I won't realistically be able to get to it today.    I think that there are two possible approaches:  one is to put recordvars and non-recordvars into different wmb lists on the compute nodes initially, the other is to make two passes through the wmb on the io-nodes once for record vars and a second for non-recordvars.   I'm pretty sure that we had the first approach implemented but it got lost somewhere along the way.   The second approach may allow for slightly better aggregation.

**Comment by edhartnett** [comment]
OK, I will take a look.

**Comment by jayeshkrishna** [comment]
@jedwards4b : Do you know which commit broke the earlier behaviour (removed adding vars with unlimited dims to the beginning of the list)? It might be worthwhile bringing that change back so that I can resume with my testing (and this issue can remain open until we fix the issue as suggested above)

**Comment by jedwards4b** [comment]
I do not, but I can provide a modification of clm src/main/ncdio_pio.F90.in which makes sure that
record and non-record variables use different iodesc pointers and thus avoid the problem.

**Comment by jedwards4b** [comment]
@edhartnett Have you had a chance to look into this yet?  I think I'll have some time this week.

**Comment by edhartnett** [comment]
No, but now that I've got my decomps working for async, I can take a look.
However, don't let that stop you if you haven't seen me do it yet and you
want to do it! ;-)

**Comment by edhartnett** [comment]
So what do we want to happen? Start a new multivar buffer?

**Comment by jedwards4b** [comment]
I think that the best approach is to continue to use the same buffer but identify and handle separately within the pio_write_darray_multi_nc routine.

**Comment by edhartnett** [comment]
I am looking at this now. You mean to handle it in the  pio_write_darray_multi_nc() and the pio_write_darray_multi_nc_serial() functions, right?

I am looking at pio_write_darray_multi_nc_serial()...

The issue is caused because of this code:

```
    /* Get the var info. */
    vdesc = file->varlist + vid[0];

```
As you note, this is grabbing the vdesc for the first var, and assuming it applies to all vars in the multibuffer.

The code on the io procs then goes on to determine starts/counts:

```
        /* Fill the tmp_start and tmp_count arrays, which contain the
         * start and count arrays for all regions. */
        region = firstregion;
        for (int regioncnt = 0; regioncnt < maxregions; regioncnt++)
        {
            /* Initialize the start/count arrays for this region to 0. */
            for (int i = 0; i < fndims; i++)
            {
                tmp_start[i + regioncnt * fndims] = 0;
                tmp_count[i + regioncnt * fndims] = 0;
            }

            if (region)
            {
                if (vdesc->record >= 0)
                {
                    /* This is a record based multidimensional
                     * array. Copy start/count for non-record
                     * dimensions. */
                    for (int i = fndims - iodesc_ndims; i < fndims; i++)
                    {
                        tmp_start[i + regioncnt * fndims] = region->start[i - (fndims - iodesc_ndims)];
                        tmp_count[i + regioncnt * fndims] = region->count[i - (fndims - iodesc_ndims)];
                        LOG((3, "tmp_start[%d] = %d tmp_count[%d] = %d", i + regioncnt * fndims,
                             tmp_start[i + regioncnt * fndims], i + regioncnt * fndims,
                             tmp_count[i + regioncnt * fndims]));
                    }
                }
                else
                {
                    /* This is not a record based multidimensional array. */
                    for (int i = 0; i < iodesc_ndims; i++)
                    {
                        tmp_start[i + regioncnt * fndims] = region->start[i];
                        tmp_count[i + regioncnt * fndims] = region->count[i];
                        LOG((3, "tmp_start[%d] = %d tmp_count[%d] = %d", i + regioncnt * fndims,
                             tmp_start[i + regioncnt * fndims], i + regioncnt * fndims,
                             tmp_count[i + regioncnt * fndims]));
                    }
                }

                /* Move to next region. */
                region = region->next;

            } /* endif region */
        } /* next regioncnt */
```

The tmp_start/tmp_count arrays are all sent to IO task 0. These arrays will mistakenly assume that all vars in the list have the same record/non-record status as the first one on the list.

This is challenging because it is not in the loop of vars - the same tmp_start/tmp_count is used for all arrays in the multi-buffer. One answer would be to look through the list and determine whether it contains record, non-record, or both variables. Then the code can create one or two sets of tmp_start/tmp_count arrays.

Later in the code we have this:

```
                        /* Process each variable in the buffer. */
                        for (int nv = 0; nv < nvars; nv++)
                        {
                            LOG((3, "writing buffer var %d", nv));

                            /* Get a pointer to the correct part of the buffer. */
                            bufptr = (void *)((char *)iobuf + tsize * (nv * rlen + loffset));

                            /* If this var has an unlimited dim, set
                             * the start on that dim to the frame
                             * value for this variable. */
                            if (vdesc->record >= 0)
                            {
                                if (fndims > 1 && iodesc_ndims < fndims && count[1] > 0)
                                {
                                    count[0] = 1;
                                    start[0] = frame[nv];
                                }
                                else if (fndims == iodesc_ndims)
                                {
                                    start[0] += vdesc->record;
                                }
                            }

                            /* Call the netCDF functions to write the data. */
                            ierr = nc_put_vara(file->fh, vid[nv], start, count, bufptr);

                            if (ierr)
                            {
                                for (int i = 0; i < fndims; i++)
                                    fprintf(stderr, "vid %d dim %d start %ld count %ld \n", vid[nv], i,
                                            start[i], count[i]);
                                return check_netcdf(file, ierr, __FILE__, __LINE__);
                            }
                        } /* next var */

```

Here the code once again checks the record status of the first var in the list, and based on that decides how to set start[0]/count[0]. This would be easy to fix because it is in the loop of nvars; we can just get the appropriate vdesc for each var in the list.

**Comment by jedwards4b** [comment]
Yes I think that the solution in write_darray_multi_nc_serial is straightforward since each variable is written individually.   The complication is in write_darray_multi_nc where the pnetcdf wants to write all variables as a group in a single call - these will need to be divided into two groups and written separately.

**Comment by edhartnett** [comment]
OK, let me tackle the serial case first and put it up for review...

**Comment by edhartnett** [comment]
I am working on this now.

This seems like a lot of new code. What used to happen when vars with and without record dim were included in the same decomposition? Did this used to work?

**Comment by jedwards4b** [comment]
It did used to work, the way it was handled before was that they were seperated into two different lists on the compute nodes prior to transfering to the io nodes.

**Comment by edhartnett** [comment]
How were they separated into lists? Did they have the same iodesc?

**Comment by edhartnett** [comment]
I will study the previous implementation...

**Comment by edhartnett** [comment]
OK, it looks to me like in the previous implement ion, non-record vars got their own multibuffer, with a negative ioid:

```
 /* Get a pointer to the buffer space for this file. It will hold
     * data from one or more variables that fit the same
     * description. */
    wmb = &file->buffer;

    /* If the ioid is not initialized, set it. For non record vars,
     * use the negative?? */
    if (wmb->ioid == -1)
    {
        if (recordvar)
            wmb->ioid = ioid;
        else
            wmb->ioid = -(ioid);
    }
    else
    {
        /* Handle record and non-record variables differently. */
        if (recordvar)
        {
	    /* Moving to the end of the wmb linked list to add the
	     * current variable. */
            while(wmb->next && wmb->ioid != ioid)
                if (wmb->next)
                    wmb = wmb->next;
#ifdef _PNETCDF
            /* flush the previous record before starting a new one. this is collective */
            /*       if (vdesc->request != NULL && (vdesc->request[0] != NC_REQ_NULL) ||
                     (wmb->frame != NULL && vdesc->record != wmb->frame[0])){
                     needsflush = 2;  // flush to disk
                     } */
#endif
        }
        else
        {
            while(wmb->next && wmb->ioid != -(ioid))
                if (wmb->next)
                    wmb = wmb->next;
        }
    }

    /* ?? */
    if ((recordvar && wmb->ioid != ioid) || (!recordvar && wmb->ioid != -(ioid)))
    {
	/* Allocate a buffer. */
        if (!(wmb->next = (wmulti_buffer *)bget((bufsize)sizeof(wmulti_buffer))))
            piomemerror(*ios,sizeof(wmulti_buffer), __FILE__,__LINE__);

	/* Set pointer to newly allocated buffer and initialize.*/
        wmb = wmb->next;
        wmb->next = NULL;
        if (recordvar)
            wmb->ioid = ioid;
        else
            wmb->ioid = -(ioid);
        wmb->validvars = 0;
        wmb->arraylen = arraylen;
        wmb->vid = NULL;
        wmb->data = NULL;
        wmb->frame = NULL;
        wmb->fillvalue = NULL;
    }

```

So it seems like the way this was handled was with two multibuffers, one for record, one of non-record.

That's what the negative ioid stuff is all about.
